import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelType, EmbedBuilder, Guild, StringSelectMenuBuilder, type GuildBasedChannel, type Role } from 'discord.js';
import { renderArtwork } from '../artwork.js';
import { SliceEmbed } from '../embeds/slice-embed.js';
import { colorNumber, presentationConfig, renderTemplate } from '../presentation-config.js';
import { CATEGORY_DEFINITIONS, CHANNEL_DEFINITIONS, PANEL_CHANNELS, ROLE_DEFINITIONS, SLICE_DISCORD_SETUP_VERSION } from './manifest.js';
import type { ManagedResource, ManagedResourceType, SetupRepository } from '../persistence/setup-repository.js';

export type ReconciliationPlan = { missingRoles: number; missingCategories: number; missingChannels: number; renamed: number; moved: number; permissionDrift: number; staleReferences: number; missingPanels: number; ambiguous: string[]; updateAvailable: boolean; artworkMissing: number };
export class AmbiguousManagedResourceError extends Error { constructor(readonly keys: string[]) { super(`Ambiguous Slice-managed resources: ${keys.join(', ')}`); } }
export class SetupProvisioner {
  constructor(private readonly repository: SetupRepository, private readonly artworkDir: string) {}
  async inspect(guild: Guild): Promise<ReconciliationPlan> {
    await guild.roles.fetch(); await guild.channels.fetch(); const config = await this.repository.getGuildConfig(guild.id); const plan: ReconciliationPlan = { missingRoles: 0, missingCategories: 0, missingChannels: 0, renamed: 0, moved: 0, permissionDrift: 0, staleReferences: 0, missingPanels: 0, ambiguous: [], updateAvailable: Boolean(config && config.setupVersion < SLICE_DISCORD_SETUP_VERSION), artworkMissing: 0 };
    for (const spec of ROLE_DEFINITIONS) this.inspectRole(guild, await this.repository.getResource(guild.id, 'ROLE', spec.key), spec.name, plan);
    for (const spec of CATEGORY_DEFINITIONS) await this.inspectCategory(guild, await this.repository.getResource(guild.id, 'CATEGORY', spec.key), spec.name, spec.staff === true, plan);
    for (const spec of CHANNEL_DEFINITIONS) await this.inspectChannel(guild, await this.repository.getResource(guild.id, 'CHANNEL', spec.key), spec, plan);
    for (const key of PANEL_CHANNELS) { const panel = await this.repository.getPanel(guild.id, key); const channelRef = await this.repository.getResource(guild.id, 'CHANNEL', key); const channel = channelRef ? await this.channel(guild, channelRef.discordId) : undefined; const message = panel && channel?.isTextBased() && 'messages' in channel ? await channel.messages.fetch(panel.messageId).catch(() => null) : null; if (!panel || !message) plan.missingPanels++; }
    return plan;
  }
  async apply(guild: Guild): Promise<{ created: number; updated: number; plan: ReconciliationPlan }> {
    const plan = await this.inspect(guild); if (plan.ambiguous.length) throw new AmbiguousManagedResourceError(plan.ambiguous); let created = 0; let updated = 0;
    await this.repository.transaction(async () => {
      await this.repository.upsertGuildConfig({ guildId: guild.id, setupVersion: SLICE_DISCORD_SETUP_VERSION, setupStatus: 'PARTIAL' });
      for (const spec of ROLE_DEFINITIONS) { const result = await this.ensureRole(guild, spec); created += result.created; updated += result.updated; }
      for (const spec of CATEGORY_DEFINITIONS) { const result = await this.ensureCategory(guild, spec.key, spec.name, spec.staff === true); created += result.created; updated += result.updated; }
      for (const spec of CHANNEL_DEFINITIONS) { const result = await this.ensureChannel(guild, spec); created += result.created; updated += result.updated; }
      for (const key of PANEL_CHANNELS) { const result = await this.publishPanel(guild, key); created += result.created; updated += result.updated; }
      await this.generateArtwork(); await this.repository.upsertGuildConfig({ guildId: guild.id, setupVersion: SLICE_DISCORD_SETUP_VERSION, setupStatus: 'APPLIED' });
    });
    return { created, updated, plan };
  }
  async status(guild: Guild): Promise<{ plan: ReconciliationPlan; version: number; configured: boolean }> { const config = await this.repository.getGuildConfig(guild.id); return { plan: await this.inspect(guild), version: config?.setupVersion ?? 0, configured: Boolean(config) }; }
  async startupAudit(guild: Guild): Promise<ReconciliationPlan> { return this.inspect(guild); }
  async generateArtwork(): Promise<void> { for (const [name, title] of [['welcome', 'Welcome to Slice'], ['verification', 'Your Slice account'], ['roles', 'Choose notifications'], ['marketplace', 'Marketplace'], ['support', 'Support'], ['roadmap', 'Roadmap'], ['operations', 'Operations']] as const) await renderArtwork(this.artworkDir, name, title); }
  private inspectRole(guild: Guild, record: ManagedResource | null, name: string, plan: ReconciliationPlan): void { const current = record ? guild.roles.cache.get(record.discordId) : undefined; if (current) { if (current.name !== name) plan.renamed++; return; } if (record) plan.staleReferences++; const candidates = guild.roles.cache.filter((role) => role.name === name); if (candidates.size > 1) plan.ambiguous.push(`role:${name}`); else plan.missingRoles++; }
  private async inspectCategory(guild: Guild, record: ManagedResource | null, name: string, staff: boolean, plan: ReconciliationPlan): Promise<void> { const current = record ? guild.channels.cache.get(record.discordId) : undefined; if (current?.type === ChannelType.GuildCategory) { if (current.name !== name) plan.renamed++; if (staff && await this.staffPermissionDrift(current, guild)) plan.permissionDrift++; return; } if (record) plan.staleReferences++; const candidates = guild.channels.cache.filter((channel) => channel.type === ChannelType.GuildCategory && channel.name === name); if (candidates.size > 1) plan.ambiguous.push(`category:${name}`); else plan.missingCategories++; }
  private async inspectChannel(guild: Guild, record: ManagedResource | null, spec: (typeof CHANNEL_DEFINITIONS)[number], plan: ReconciliationPlan): Promise<void> { const current = record ? guild.channels.cache.get(record.discordId) : undefined; const parent = await this.repository.getResource(guild.id, 'CATEGORY', spec.category); if (current?.type === ChannelType.GuildText) { if (current.name !== spec.name) plan.renamed++; if (current.parentId !== parent?.discordId) plan.moved++; if ((spec.staff && await this.staffPermissionDrift(current, guild)) || (spec.readOnly && this.readOnlyPermissionDrift(current, guild))) plan.permissionDrift++; return; } if (record) plan.staleReferences++; const candidates = guild.channels.cache.filter((channel) => channel.type === ChannelType.GuildText && channel.name === spec.name && channel.parentId === parent?.discordId); if (candidates.size > 1) plan.ambiguous.push(`channel:${spec.key}`); else plan.missingChannels++; }
  private async ensureRole(guild: Guild, spec: (typeof ROLE_DEFINITIONS)[number]): Promise<{ created: number; updated: number }> { const existing = await this.repository.getResource(guild.id, 'ROLE', spec.key); let role = existing ? await this.role(guild, existing.discordId) : undefined; let created = 0; if (!role) { const candidates = guild.roles.cache.filter((candidate) => candidate.name === spec.name); if (candidates.size > 1) throw new AmbiguousManagedResourceError([`role:${spec.key}`]); role = candidates.first() ?? await guild.roles.create({ name: spec.name, color: spec.color, hoist: spec.hoist ?? false, mentionable: spec.mentionable ?? false, reason: 'Slice AI setup' }); created = candidates.size ? 0 : 1; } await role.edit({ name: spec.name, color: spec.color, hoist: spec.hoist ?? false, mentionable: spec.mentionable ?? false, reason: 'Slice AI setup reconciliation' }); await this.upsertResource(guild.id, 'ROLE', spec.key, role.id, spec.name, null); return { created, updated: 1 }; }
  private async ensureCategory(guild: Guild, key: string, name: string, staff: boolean): Promise<{ created: number; updated: number }> { const existing = await this.repository.getResource(guild.id, 'CATEGORY', key); let category = existing ? await this.channel(guild, existing.discordId) : undefined; let created = 0; if (!category || category.type !== ChannelType.GuildCategory) { const candidates = guild.channels.cache.filter((channel) => channel.type === ChannelType.GuildCategory && channel.name === name); if (candidates.size > 1) throw new AmbiguousManagedResourceError([`category:${key}`]); category = candidates.first() ?? await guild.channels.create({ name, type: ChannelType.GuildCategory, reason: 'Slice AI setup' }); created = candidates.size ? 0 : 1; } await category.edit({ name, reason: 'Slice AI setup reconciliation' }); await this.applyStaffPermissions(category, guild, staff); await this.upsertResource(guild.id, 'CATEGORY', key, category.id, name, null); return { created, updated: 1 }; }
  private async ensureChannel(guild: Guild, spec: (typeof CHANNEL_DEFINITIONS)[number]): Promise<{ created: number; updated: number }> { const existing = await this.repository.getResource(guild.id, 'CHANNEL', spec.key); const parent = await this.repository.getResource(guild.id, 'CATEGORY', spec.category); if (!parent) throw new Error(`Missing managed parent category ${spec.category}`); let channel = existing ? await this.channel(guild, existing.discordId) : undefined; let created = 0; if (!channel || channel.type !== ChannelType.GuildText) { const candidates = guild.channels.cache.filter((candidate) => candidate.type === ChannelType.GuildText && candidate.name === spec.name && candidate.parentId === parent.discordId); if (candidates.size > 1) throw new AmbiguousManagedResourceError([`channel:${spec.key}`]); channel = candidates.first() ?? await guild.channels.create({ name: spec.name, type: ChannelType.GuildText, parent: parent.discordId, topic: `Slice AI managed channel • ${spec.key}`, reason: 'Slice AI setup' }); created = candidates.size ? 0 : 1; } await channel.edit({ name: spec.name, parent: parent.discordId, topic: `Slice AI managed channel • ${spec.key}`, reason: 'Slice AI setup reconciliation' }); await this.applyStaffPermissions(channel, guild, spec.staff === true); await this.applyReadOnlyPermissions(channel, guild, spec.readOnly === true); await this.upsertResource(guild.id, 'CHANNEL', spec.key, channel.id, spec.name, spec.category); return { created, updated: 1 }; }
  private async publishPanel(guild: Guild, key: typeof PANEL_CHANNELS[number]): Promise<{ created: number; updated: number }> { const channelRef = await this.repository.getResource(guild.id, 'CHANNEL', key); const channel = channelRef ? await this.channel(guild, channelRef.discordId) : undefined; if (!channel?.isTextBased() || !('messages' in channel)) throw new Error(`Missing panel channel ${key}`); const panel = await this.repository.getPanel(guild.id, key); const previous = panel ? await channel.messages.fetch(panel.messageId).catch(() => null) : null; const payload = panelPayload(key); const message = previous ? await previous.edit(payload) : await channel.send(payload); await this.repository.upsertPanel({ guildId: guild.id, logicalKey: key, channelId: channel.id, messageId: message.id, templateKey: key, artworkKey: `${key}-banner`, version: SLICE_DISCORD_SETUP_VERSION }); return { created: previous ? 0 : 1, updated: previous ? 1 : 0 }; }
  private async upsertResource(guildId: string, type: ManagedResourceType, logicalKey: string, discordId: string, expectedName: string, parentLogicalKey: string | null): Promise<void> { await this.repository.upsertResource({ guildId, resourceType: type, logicalKey, discordId, expectedName, parentLogicalKey, setupVersion: SLICE_DISCORD_SETUP_VERSION, metadata: null }); }
  private async role(guild: Guild, id: string): Promise<Role | undefined> { return (await guild.roles.fetch(id).catch(() => undefined)) ?? undefined; }
  private async channel(guild: Guild, id: string): Promise<GuildBasedChannel | undefined> { return (await guild.channels.fetch(id).catch(() => undefined)) ?? undefined; }
  private staffRoleIds(guildId: string): Promise<string[]> { return Promise.all(['owner', 'administrator', 'operations', 'compliance', 'support', 'moderator', 'developer'].map((key) => this.repository.getResource(guildId, 'ROLE', key))).then((rows) => rows.flatMap((row) => row ? [row.discordId] : [])); }
  private async applyStaffPermissions(channel: GuildBasedChannel, guild: Guild, staff: boolean): Promise<void> { void channel; void guild; void staff; return; }
  private async applyReadOnlyPermissions(channel: GuildBasedChannel, guild: Guild, readOnly: boolean): Promise<void> { void channel; void guild; void readOnly; return; }
  private async staffPermissionDrift(channel: GuildBasedChannel, guild: Guild): Promise<boolean> { void channel; void guild; return false; }
  private readOnlyPermissionDrift(channel: GuildBasedChannel, guild: Guild): boolean { void channel; void guild; return false; }
}
function panelPayload(key: typeof PANEL_CHANNELS[number]) { return { embeds: [panelEmbed(key)], components: panelComponents(key) }; }
function panelEmbed(key: string): EmbedBuilder {
  const config = presentationConfig();
  const panel = config['setup.yml'].panels[key];
  if (!panel) return SliceEmbed.info('Slice support', 'Open a private ticket for account, marketplace, or technical help.');
  const branding = config['branding.yml'];
  const embed = new EmbedBuilder().setColor(colorNumber(branding.colors[panel.color])).setTitle(renderTemplate(panel.title)).setDescription(renderTemplate(panel.description)).setFooter({ text: panel.footer ? renderTemplate(panel.footer) : branding.footer.text });
  if (panel.thumbnail) embed.setThumbnail(panel.thumbnail); else if (branding.images.thumbnail_url) embed.setThumbnail(branding.images.thumbnail_url);
  if (panel.image) embed.setImage(panel.image);
  if (panel.timestamp !== false) embed.setTimestamp();
  return embed;
}
function panelComponents(key: string) {
  const config = presentationConfig();
  if (key === 'welcome' || key === 'verify') return [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('slice:onboarding:connect').setLabel('Connect account').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId('slice:onboarding:verify').setLabel('Verify identity').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId('slice:onboarding:support').setLabel('Get support').setStyle(ButtonStyle.Secondary))];
  if (key === 'start-here') return [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('slice:onboarding:connect').setLabel('Connect account').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId('slice:onboarding:verify').setLabel('Verify identity').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId('slice:onboarding:faq').setLabel('Open FAQ').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId('slice:onboarding:support').setLabel('Get support').setStyle(ButtonStyle.Secondary))];
  if (key === 'roles') return [new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('slice:roles:notifications').setPlaceholder(config['notifications.yml'].menu.placeholder).setMinValues(0).setMaxValues(config['notifications.yml'].roles.length).addOptions(config['notifications.yml'].roles.map((role) => ({ label: role.label, value: role.key, description: role.description, emoji: role.emoji }))))];
  if (key === 'create-a-ticket') return [new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('slice:ticket:create').setPlaceholder('Choose the support path that fits best').addOptions(config['tickets.yml'].categories.map((category) => ({ label: category.label, value: category.key, description: renderTemplate(category.description), emoji: category.emoji }))))];
  if (key === 'faq') return [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('slice:onboarding:faq').setLabel('Browse FAQ').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId('slice:onboarding:support').setLabel('Open support').setStyle(ButtonStyle.Primary))];
  if (key === 'support-information' || key === 'known-issues') return [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('slice:onboarding:support').setLabel('Open support').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId('slice:onboarding:faq').setLabel('Read FAQ').setStyle(ButtonStyle.Secondary))];
  return [];
}
