import { Prisma, PrismaClient } from '../../generated/prisma/index.js';
import { DEFAULT_TICKET_FORMS, type TicketIntakeAnswer, type TicketIntakeField, validateForm } from '../advanced-ticket-forms.js';

export type TicketFormVersion = { id: string; guildId: string; category: string; version: number; fields: TicketIntakeField[]; active: boolean };
export type TicketOperationsView = { id: string; guildId: string; creatorDiscordId: string; category: string; status: string; priority: string; assignedStaffId: string | null; assignedTeamKey: string | null; createdAt: Date; lastActivityAt: Date; firstStaffResponseAt: Date | null; firstResponseDueAt: Date | null; resolutionDueAt: Date | null; tags: Array<{ key: string; label: string }> };
export type TicketPolicy = { guildId: string; category: string; routingRoleKey: string | null; defaultPriority: 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT'; firstResponseMinutes: number; resolutionMinutes: number; inactivityWarningHours: number; inactivityCloseHours: number; protectedFromAutoClose: boolean; enabled: boolean };
export type TicketSlaAlertKind = 'FIRST_RESPONSE_RISK' | 'FIRST_RESPONSE_BREACH' | 'RESOLUTION_RISK' | 'RESOLUTION_BREACH';

export class PrismaAdvancedTicketRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async activeForm(guildId: string, category: string, actorId?: string): Promise<TicketFormVersion> {
    const active = await this.prisma.discordTicketFormVersion.findFirst({ where: { guildId, category, active: true }, orderBy: { version: 'desc' } });
    if (active) return mapForm(active);
    const fields = DEFAULT_TICKET_FORMS[category] ?? DEFAULT_TICKET_FORMS['general-support'];
    return this.createFormVersion(guildId, category, fields, actorId);
  }
  async createFormVersion(guildId: string, category: string, fields: TicketIntakeField[], actorId?: string): Promise<TicketFormVersion> {
    const errors = validateForm(fields); if (errors.length) throw new Error(errors[0]);
    return this.prisma.$transaction(async (db) => { const latest = await db.discordTicketFormVersion.findFirst({ where: { guildId, category }, orderBy: { version: 'desc' } }); await db.discordTicketFormVersion.updateMany({ where: { guildId, category, active: true }, data: { active: false } }); const row = await db.discordTicketFormVersion.create({ data: { guildId, category, version: (latest?.version ?? 0) + 1, fields: fields as Prisma.InputJsonValue, createdBy: actorId } }); return mapForm(row); });
  }
  async attachIntake(ticketId: string, guildId: string, form: TicketFormVersion, answers: TicketIntakeAnswer[]): Promise<boolean> {
    return this.prisma.$transaction(async (db) => { const changed = await db.discordTicket.updateMany({ where: { id: ticketId, guildId, formVersionId: null }, data: { formVersionId: form.id } }); if (!changed.count) return false; if (answers.length) await db.discordTicketIntakeResponse.createMany({ data: answers.map((answer) => ({ ticketId, fieldKey: answer.fieldKey, fieldLabel: answer.fieldLabel, fieldType: answer.fieldType, value: answer.value })), skipDuplicates: true }); await db.discordTicketEvent.create({ data: { ticketId, type: 'INTAKE_SNAPSHOTTED', metadata: { formVersion: form.version, fieldCount: answers.length } } }); return true; });
  }
  async addInternalNote(ticketId: string, guildId: string, actorId: string, content: string, referencedMessageId?: string): Promise<string | null> { const ticket = await this.prisma.discordTicket.findFirst({ where: { id: ticketId, guildId }, select: { id: true } }); if (!ticket) return null; const note = await this.prisma.$transaction(async (db) => { const row = await db.discordTicketInternalNote.create({ data: { ticketId, authorDiscordUserId: actorId, content, referencedMessageId } }); await db.discordTicketEvent.create({ data: { ticketId, type: 'INTERNAL_NOTE_ADDED', actorDiscordId: actorId, metadata: { noteId: row.id } } }); return row; }); return note.id; }
  async notes(ticketId: string, guildId: string) { return this.prisma.discordTicketInternalNote.findMany({ where: { ticketId, ticket: { guildId } }, orderBy: { createdAt: 'asc' }, take: 100 }); }
  async addTag(ticketId: string, guildId: string, actorId: string, key: string): Promise<boolean> { const tag = await this.prisma.discordTicketTag.findFirst({ where: { guildId, key, enabled: true } }); if (!tag) return false; try { await this.prisma.$transaction(async (db) => { const ticket = await db.discordTicket.findFirst({ where: { id: ticketId, guildId }, select: { id: true } }); if (!ticket) throw new Error('Ticket unavailable.'); await db.discordTicketTagAssignment.create({ data: { ticketId, tagId: tag.id, addedBy: actorId } }); await db.discordTicketEvent.create({ data: { ticketId, type: 'TAG_ADDED', actorDiscordId: actorId, metadata: { key } } }); }); return true; } catch { return false; } }
  async removeTag(ticketId: string, guildId: string, actorId: string, key: string): Promise<boolean> { const result = await this.prisma.discordTicketTagAssignment.deleteMany({ where: { ticketId, ticket: { guildId }, tag: { key } } }); if (!result.count) return false; await this.prisma.discordTicketEvent.create({ data: { ticketId, type: 'TAG_REMOVED', actorDiscordId: actorId, metadata: { key } } }); return true; }
  async listTags(guildId: string) { return this.prisma.discordTicketTag.findMany({ where: { guildId }, orderBy: [{ enabled: 'desc' }, { sortOrder: 'asc' }, { label: 'asc' }] }); }
  async upsertTag(guildId: string, key: string, label: string, actorId: string): Promise<void> { await this.prisma.discordTicketTag.upsert({ where: { guildId_key: { guildId, key } }, create: { guildId, key, label }, update: { label, enabled: true } }); void actorId; }
  async disableTag(guildId: string, key: string, actorId: string): Promise<boolean> { const result = await this.prisma.discordTicketTag.updateMany({ where: { guildId, key, enabled: true }, data: { enabled: false } }); void actorId; return result.count === 1; }
  async policy(guildId: string, category: string): Promise<TicketPolicy | null> { const row = await this.prisma.discordTicketCategoryPolicy.findUnique({ where: { guildId_category: { guildId, category } } }); return row ? mapPolicy(row) : null; }
  async upsertPolicy(guildId: string, category: string, patch: Partial<Omit<TicketPolicy, 'guildId' | 'category'>>): Promise<TicketPolicy> {
    const row = await this.prisma.discordTicketCategoryPolicy.upsert({ where: { guildId_category: { guildId, category } }, create: { guildId, category, ...policyData(patch) }, update: policyData(patch) });
    return mapPolicy(row);
  }
  async markFirstStaffResponse(ticketId: string, guildId: string, actorId: string, at = new Date()): Promise<boolean> {
    return this.prisma.$transaction(async (db) => { const changed = await db.discordTicket.updateMany({ where: { id: ticketId, guildId, firstStaffResponseAt: null, status: { notIn: ['CLOSED'] as never[] } }, data: { firstStaffResponseAt: at, lastActivityAt: at } }); if (!changed.count) return false; await db.discordTicketEvent.create({ data: { ticketId, type: 'FIRST_STAFF_RESPONSE', actorDiscordId: actorId, metadata: { at: at.toISOString() } } }); return true; });
  }
  async ticketDetail(ticketId: string, guildId: string) {
    return this.prisma.discordTicket.findFirst({ where: { id: ticketId, guildId }, include: { formVersion: true, intakeResponses: { orderBy: { createdAt: 'asc' } }, internalNotes: { orderBy: { createdAt: 'asc' } }, tagAssignments: { include: { tag: true } }, events: { orderBy: { createdAt: 'asc' } } } });
  }
  async customerSummary(ticketId: string, guildId: string, creatorDiscordId: string) {
    return this.prisma.discordTicket.findFirst({ where: { id: ticketId, guildId, creatorDiscordId }, select: { id: true, category: true, status: true, createdAt: true, lastActivityAt: true, assignedTeamKey: true } });
  }
  async search(guildId: string, query: { reference?: string; creatorDiscordId?: string; category?: string; status?: string; tag?: string; assignedStaffId?: string; createdSince?: Date; limit?: number }): Promise<TicketOperationsView[]> {
    const rows = await this.prisma.discordTicket.findMany({ where: { guildId, ...(query.reference ? { id: { startsWith: query.reference } } : {}), ...(query.creatorDiscordId ? { creatorDiscordId: query.creatorDiscordId } : {}), ...(query.category ? { category: query.category } : {}), ...(query.status ? { status: query.status as never } : {}), ...(query.assignedStaffId ? { assignedStaffId: query.assignedStaffId } : {}), ...(query.createdSince ? { createdAt: { gte: query.createdSince } } : {}), ...(query.tag ? { tagAssignments: { some: { tag: { key: query.tag } } } } : {}) }, include: { tagAssignments: { include: { tag: true } } }, orderBy: [{ createdAt: 'desc' }], take: Math.min(query.limit ?? 25, 100) });
    return rows.map(mapTicket);
  }
  async stats(guildId: string, since: Date) {
    const rows = await this.prisma.discordTicket.findMany({ where: { guildId, createdAt: { gte: since } }, select: { category: true, priority: true, status: true, createdAt: true, firstStaffResponseAt: true, resolvedAt: true, firstResponseDueAt: true, resolutionDueAt: true } });
    const responseDurations = rows.flatMap((row) => row.firstStaffResponseAt ? [row.firstStaffResponseAt.getTime() - row.createdAt.getTime()] : []);
    const resolutionDurations = rows.flatMap((row) => row.resolvedAt ? [row.resolvedAt.getTime() - row.createdAt.getTime()] : []);
    return { opened: rows.length, open: rows.filter((row) => !['RESOLVED', 'CLOSED'].includes(row.status)).length, unassigned: await this.prisma.discordTicket.count({ where: { guildId, status: { notIn: ['RESOLVED', 'CLOSED'] as never[] }, assignedStaffId: null } }), byCategory: countBy(rows, (row) => row.category), byPriority: countBy(rows, (row) => row.priority), averageFirstResponseMs: average(responseDurations), averageResolutionMs: average(resolutionDurations), firstResponseMet: rows.filter((row) => row.firstStaffResponseAt && row.firstResponseDueAt && row.firstStaffResponseAt <= row.firstResponseDueAt).length, resolutionMet: rows.filter((row) => row.resolvedAt && row.resolutionDueAt && row.resolvedAt <= row.resolutionDueAt).length };
  }
  async listSlaAlertCandidates(_now: Date, limit = 100) {
    return this.prisma.discordTicket.findMany({ where: { status: { notIn: ['RESOLVED', 'CLOSED'] as never[] }, OR: [{ firstStaffResponseAt: null, firstResponseDueAt: { not: null } }, { resolutionDueAt: { not: null } }] }, orderBy: { createdAt: 'asc' }, take: limit });
  }
  async markSlaAlert(ticketId: string, guildId: string, kind: TicketSlaAlertKind, at = new Date()): Promise<boolean> {
    const field = { FIRST_RESPONSE_RISK: 'firstResponseRiskAlertedAt', FIRST_RESPONSE_BREACH: 'firstResponseBreachAlertedAt', RESOLUTION_RISK: 'resolutionRiskAlertedAt', RESOLUTION_BREACH: 'resolutionBreachAlertedAt' }[kind];
    const result = await this.prisma.discordTicket.updateMany({ where: { id: ticketId, guildId, [field]: null }, data: { [field]: at } });
    return result.count === 1;
  }
  async queue(guildId: string, filter: 'OPEN' | 'UNASSIGNED' | 'MINE' | 'HIGH_PRIORITY' | 'SLA_RISK' | 'SLA_BREACHED' | 'CATEGORY' | 'ALL', actorId: string, category?: string, status?: string, assignedStaffId?: string): Promise<TicketOperationsView[]> {
    const now = new Date(); const where = { guildId, status: status ? status as never : { notIn: ['CLOSED'] as never[] }, ...(filter === 'UNASSIGNED' ? { assignedStaffId: null } : {}), ...(filter === 'MINE' ? { assignedStaffId: actorId } : {}), ...(assignedStaffId ? { assignedStaffId } : {}), ...(filter === 'HIGH_PRIORITY' ? { priority: { in: ['HIGH', 'URGENT'] as never[] } } : {}), ...(filter === 'CATEGORY' && category ? { category } : {}), ...(filter === 'SLA_BREACHED' ? { OR: [{ firstStaffResponseAt: null, firstResponseDueAt: { lt: now } }, { resolutionDueAt: { lt: now } }] } : {}), ...(filter === 'SLA_RISK' ? { OR: [{ firstStaffResponseAt: null, firstResponseDueAt: { gte: now, lte: new Date(now.getTime() + 60 * 60_000) } }, { resolutionDueAt: { gte: now, lte: new Date(now.getTime() + 60 * 60_000) } }] } : {}) };
    const rows = await this.prisma.discordTicket.findMany({ where, include: { tagAssignments: { include: { tag: true } } }, orderBy: [{ priority: 'desc' }, { createdAt: 'asc' }], take: 100 });
    return rows.map(mapTicket);
  }
}
function mapForm(row: { id: string; guildId: string; category: string; version: number; fields: unknown; active: boolean }): TicketFormVersion { return { id: row.id, guildId: row.guildId, category: row.category, version: row.version, fields: row.fields as TicketIntakeField[], active: row.active }; }
function mapTicket(row: { id: string; guildId: string; creatorDiscordId: string; category: string; status: string; priority: string; assignedStaffId: string | null; assignedTeamKey: string | null; createdAt: Date; lastActivityAt: Date; firstStaffResponseAt: Date | null; firstResponseDueAt: Date | null; resolutionDueAt: Date | null; tagAssignments: Array<{ tag: { key: string; label: string } }> }): TicketOperationsView { return { id: row.id, guildId: row.guildId, creatorDiscordId: row.creatorDiscordId, category: row.category, status: row.status, priority: row.priority, assignedStaffId: row.assignedStaffId, assignedTeamKey: row.assignedTeamKey, createdAt: row.createdAt, lastActivityAt: row.lastActivityAt, firstStaffResponseAt: row.firstStaffResponseAt, firstResponseDueAt: row.firstResponseDueAt, resolutionDueAt: row.resolutionDueAt, tags: row.tagAssignments.map((assignment) => ({ key: assignment.tag.key, label: assignment.tag.label })) }; }
function mapPolicy(row: { guildId: string; category: string; routingRoleKey: string | null; defaultPriority: string; firstResponseMinutes: number; resolutionMinutes: number; inactivityWarningHours: number; inactivityCloseHours: number; protectedFromAutoClose: boolean; enabled: boolean }): TicketPolicy { return { ...row, defaultPriority: row.defaultPriority as TicketPolicy['defaultPriority'] }; }
function policyData(patch: Partial<Omit<TicketPolicy, 'guildId' | 'category'>>) { return { ...(patch.routingRoleKey !== undefined ? { routingRoleKey: patch.routingRoleKey } : {}), ...(patch.defaultPriority !== undefined ? { defaultPriority: patch.defaultPriority } : {}), ...(patch.firstResponseMinutes !== undefined ? { firstResponseMinutes: bounded(patch.firstResponseMinutes, 1, 43_200) } : {}), ...(patch.resolutionMinutes !== undefined ? { resolutionMinutes: bounded(patch.resolutionMinutes, 1, 129_600) } : {}), ...(patch.inactivityWarningHours !== undefined ? { inactivityWarningHours: bounded(patch.inactivityWarningHours, 1, 720) } : {}), ...(patch.inactivityCloseHours !== undefined ? { inactivityCloseHours: bounded(patch.inactivityCloseHours, 1, 720) } : {}), ...(patch.protectedFromAutoClose !== undefined ? { protectedFromAutoClose: patch.protectedFromAutoClose } : {}), ...(patch.enabled !== undefined ? { enabled: patch.enabled } : {}) }; }
function bounded(value: number, minimum: number, maximum: number): number { if (!Number.isInteger(value) || value < minimum || value > maximum) throw new Error(`Value must be an integer between ${minimum} and ${maximum}.`); return value; }
function average(values: number[]): number | null { return values.length ? Math.round(values.reduce((total, value) => total + value, 0) / values.length) : null; }
function countBy<T>(values: T[], key: (value: T) => string): Record<string, number> { return values.reduce<Record<string, number>>((result, value) => { const name = key(value); result[name] = (result[name] ?? 0) + 1; return result; }, {}); }
