import { Prisma, PrismaClient } from '../../generated/prisma/index.js'; import type { EmbedPayload, LinkButton } from '../embed-builder.js';
export type Draft = { id: string; guildId: string; name: string; creatorDiscordUserId: string; payload: EmbedPayload; buttons: LinkButton[]; targetChannelId: string | null; version: number; lastPublishedAt: Date | null };
export class PrismaEmbedRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async create(guildId: string, actor: string, name: string, payload: EmbedPayload = {}, buttons: LinkButton[] = []): Promise<Draft> { const row = await this.prisma.discordEmbedDraft.create({ data: { guildId, creatorDiscordUserId: actor, name, payload: payload as Prisma.InputJsonValue, linkButtons: buttons as Prisma.InputJsonValue, auditEvents: { create: { guildId, actorDiscordUserId: actor, action: 'DRAFT_CREATED' } } } }); return map(row); }
  async get(id: string, guildId: string): Promise<Draft | null> { const row = await this.prisma.discordEmbedDraft.findFirst({ where: { id, guildId, deletedAt: null } }); return row ? map(row) : null; }
  async getForPublication(id: string, guildId: string): Promise<Draft | null> { const row = await this.prisma.discordEmbedDraft.findFirst({ where: { id, guildId } }); return row ? map(row) : null; }
  async list(guildId: string): Promise<Draft[]> { return (await this.prisma.discordEmbedDraft.findMany({ where: { guildId, deletedAt: null }, orderBy: { updatedAt: 'desc' }, take: 25 })).map(map); }
  async save(id: string, guildId: string, actor: string, version: number, input: { payload: EmbedPayload; buttons: LinkButton[]; targetChannelId?: string | null }): Promise<Draft | null> { const result = await this.prisma.discordEmbedDraft.updateMany({ where: { id, guildId, version, deletedAt: null }, data: { payload: input.payload as Prisma.InputJsonValue, linkButtons: input.buttons as Prisma.InputJsonValue, targetChannelId: input.targetChannelId, version: { increment: 1 } } }); if (!result.count) return null; await this.prisma.discordEmbedAuditEvent.create({ data: { guildId, draftId: id, actorDiscordUserId: actor, action: input.targetChannelId === undefined ? 'DRAFT_EDITED' : 'TARGET_CHANGED' } }); return this.get(id, guildId); }
  async clone(id: string, guildId: string, actor: string, name: string): Promise<Draft | null> { const draft = await this.get(id, guildId); if (!draft) return null; const clone = await this.create(guildId, actor, name, draft.payload, draft.buttons); if (draft.targetChannelId) await this.save(clone.id, guildId, actor, clone.version, { payload: clone.payload, buttons: clone.buttons, targetChannelId: draft.targetChannelId }); await this.prisma.discordEmbedAuditEvent.create({ data: { guildId, draftId: clone.id, actorDiscordUserId: actor, action: 'DRAFT_CLONED' } }); return this.get(clone.id, guildId); }
  async publication(draft: Draft, actor: string, channelId: string, messageId: string) { const row = await this.prisma.discordEmbedPublication.create({ data: { draftId: draft.id, guildId: draft.guildId, channelId, messageId, publishedByDiscordUserId: actor, revisionUsed: draft.version, auditEvents: { create: { guildId: draft.guildId, draftId: draft.id, actorDiscordUserId: actor, action: 'PUBLISHED' } } } }); await this.prisma.discordEmbedDraft.update({ where: { id: draft.id }, data: { lastPublishedAt: new Date() } }); return row; }
  async publications(draftId: string, guildId: string) { return this.prisma.discordEmbedPublication.findMany({ where: { draftId, guildId }, orderBy: { publishedAt: 'desc' } }); }
  async markUpdated(id: string, guildId: string, actor: string) { const row = await this.prisma.discordEmbedPublication.updateMany({ where: { id, guildId, deletedAt: null }, data: { updatedAt: new Date() } }); if (row.count) await this.prisma.discordEmbedAuditEvent.create({ data: { guildId, draftId: (await this.prisma.discordEmbedPublication.findUniqueOrThrow({ where: { id } })).draftId, publicationId: id, actorDiscordUserId: actor, action: 'PUBLICATION_UPDATED' } }); return row.count === 1; }
  async markDeleted(id: string, guildId: string, actor: string) { const row = await this.prisma.discordEmbedPublication.updateMany({ where: { id, guildId, deletedAt: null }, data: { deletedAt: new Date(), deletedByDiscordUserId: actor } }); if (row.count) await this.prisma.discordEmbedAuditEvent.create({ data: { guildId, draftId: (await this.prisma.discordEmbedPublication.findUniqueOrThrow({ where: { id } })).draftId, publicationId: id, actorDiscordUserId: actor, action: 'PUBLICATION_DELETED' } }); return row.count === 1; }
  async archive(id: string, guildId: string, actor: string) { const row = await this.prisma.discordEmbedDraft.updateMany({ where: { id, guildId, deletedAt: null }, data: { deletedAt: new Date() } }); if (row.count) await this.prisma.discordEmbedAuditEvent.create({ data: { guildId, draftId: id, actorDiscordUserId: actor, action: 'DRAFT_DELETED' } }); return row.count === 1; }
}
function map(row: { id: string; guildId: string; name: string; creatorDiscordUserId: string; payload: unknown; linkButtons: unknown; targetChannelId: string | null; version: number; lastPublishedAt: Date | null }): Draft { return { id: row.id, guildId: row.guildId, name: row.name, creatorDiscordUserId: row.creatorDiscordUserId, payload: row.payload as EmbedPayload, buttons: row.linkButtons as LinkButton[], targetChannelId: row.targetChannelId, version: row.version, lastPublishedAt: row.lastPublishedAt }; }
