import { PrismaClient } from '../../generated/prisma/index.js';
import type { ModerationCase, ModerationRepository } from '../moderation.js';
export class PrismaModerationRepository implements ModerationRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async create(input: Omit<ModerationCase, 'caseNumber' | 'status'>): Promise<ModerationCase> { return this.prisma.$transaction(async (db) => { const counter = await db.discordModerationCounter.upsert({ where: { guildId: input.guildId }, create: { guildId: input.guildId, nextCaseNumber: 2 }, update: { nextCaseNumber: { increment: 1 } } }); const row = await db.discordModerationCase.create({ data: { ...input, caseNumber: counter.nextCaseNumber - 1, status: 'PENDING' } }); return map(row); }); }
  async mark(id: Pick<ModerationCase, 'guildId' | 'caseNumber'>, status: ModerationCase['status']): Promise<void> { await this.prisma.discordModerationCase.update({ where: { guildId_caseNumber: id }, data: { status } }); }
  async get(guildId: string, caseNumber: number): Promise<ModerationCase | null> { const row = await this.prisma.discordModerationCase.findUnique({ where: { guildId_caseNumber: { guildId, caseNumber } } }); return row ? map(row) : null; }
  async history(guildId: string, targetDiscordUserId: string, take = 10): Promise<ModerationCase[]> { return (await this.prisma.discordModerationCase.findMany({ where: { guildId, targetDiscordUserId }, orderBy: [{ createdAt: 'desc' }, { caseNumber: 'desc' }], take: Math.min(Math.max(take, 1), 25) })).map(map); }
}
function map(row: { guildId:string;caseNumber:number;targetDiscordUserId:string;moderatorDiscordUserId:string|null;action:ModerationCase['action'];source:ModerationCase['source'];status:ModerationCase['status'];reason:string;expiresAt:Date|null;relatedMessageId:string|null;relatedChannelId:string|null;evidenceExcerpt:string|null }): ModerationCase { return { guildId:row.guildId,caseNumber:row.caseNumber,targetDiscordUserId:row.targetDiscordUserId,moderatorDiscordUserId:row.moderatorDiscordUserId??undefined,action:row.action,source:row.source,status:row.status,reason:row.reason,expiresAt:row.expiresAt??undefined,relatedMessageId:row.relatedMessageId??undefined,relatedChannelId:row.relatedChannelId??undefined,evidenceExcerpt:row.evidenceExcerpt??undefined }; }
