import { Prisma, PrismaClient } from '../../generated/prisma/index.js';
import type { NewsCandidate } from '../news-feed.js';

export type NewsState = { sourceId: string; etag: string | null; lastModified: string | null; nextPollAt: Date | null; consecutiveFailures: number };
export type StoredNewsItem = { id: string; sourceId: string; canonicalUrl: string; title: string; publishedAt: Date; category: string; priority: string; summary: string; status: string };
export type PendingNewsDelivery = { id: string; guildId: string; channelId: string; attempts: number; newsItem: StoredNewsItem };

export class PrismaNewsRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async sourceState(sourceId: string): Promise<NewsState> { const row = await this.prisma.discordNewsSourceState.findUnique({ where: { sourceId } }); return row ?? { sourceId, etag: null, lastModified: null, nextPollAt: null, consecutiveFailures: 0 }; }
  async sourceSuccess(sourceId: string, data: { etag?: string | null; lastModified?: string | null }): Promise<void> { await this.prisma.discordNewsSourceState.upsert({ where: { sourceId }, create: { sourceId, lastPollAt: new Date(), lastSuccessAt: new Date(), etag: data.etag ?? null, lastModified: data.lastModified ?? null }, update: { lastPollAt: new Date(), lastSuccessAt: new Date(), etag: data.etag ?? null, lastModified: data.lastModified ?? null, nextPollAt: null, consecutiveFailures: 0 } }); }
  async sourceFailure(sourceId: string, retryAfterMs: number): Promise<void> { const row = await this.sourceState(sourceId); await this.prisma.discordNewsSourceState.upsert({ where: { sourceId }, create: { sourceId, lastPollAt: new Date(), nextPollAt: new Date(Date.now() + retryAfterMs), consecutiveFailures: 1 }, update: { lastPollAt: new Date(), nextPollAt: new Date(Date.now() + retryAfterMs), consecutiveFailures: row.consecutiveFailures + 1 } }); }
  async upsertCandidate(candidate: NewsCandidate): Promise<{ item: StoredNewsItem; created: boolean }> { try { const row = await this.prisma.discordNewsItem.create({ data: { sourceId: candidate.source.id, dedupKey: candidate.dedupKey, externalId: candidate.externalId, canonicalUrl: candidate.canonicalUrl, canonicalUrlHash: candidate.canonicalUrlHash, title: candidate.title, publishedAt: candidate.publishedAt, category: candidate.category, priority: candidate.priority.toUpperCase(), summary: candidate.summary, contentHash: candidate.contentHash } }); return { item: mapItem(row), created: true }; } catch (error) { if (!(error instanceof Prisma.PrismaClientKnownRequestError) || error.code !== 'P2002') throw error; const row = await this.prisma.discordNewsItem.findFirstOrThrow({ where: { OR: [{ dedupKey: candidate.dedupKey }, { sourceId: candidate.source.id, contentHash: candidate.contentHash }] } }); return { item: mapItem(row), created: false }; } }
  async ensureDelivery(guildId: string, channelId: string, newsItemId: string): Promise<void> { await this.prisma.discordNewsDelivery.upsert({ where: { guildId_newsItemId: { guildId, newsItemId } }, create: { guildId, channelId, newsItemId }, update: {} }); }
  async pendingDeliveries(limit: number): Promise<PendingNewsDelivery[]> { const rows = await this.prisma.discordNewsDelivery.findMany({ where: { status: { in: ['PENDING', 'RETRYABLE_FAILURE'] } }, include: { newsItem: true }, orderBy: { createdAt: 'asc' }, take: limit }); return rows.map((row) => ({ id: row.id, guildId: row.guildId, channelId: row.channelId, attempts: row.attempts, newsItem: mapItem(row.newsItem) })); }
  async claimDelivery(id: string): Promise<boolean> { return (await this.prisma.discordNewsDelivery.updateMany({ where: { id, status: { in: ['PENDING', 'RETRYABLE_FAILURE'] } }, data: { status: 'SENDING', claimedAt: new Date(), attempts: { increment: 1 } } })).count === 1; }
  async delivered(id: string, messageId: string): Promise<void> { const delivery = await this.prisma.discordNewsDelivery.update({ where: { id }, data: { status: 'DELIVERED', deliveredAt: new Date(), discordMessageId: messageId, failureCode: null }, select: { newsItemId: true } }); await this.prisma.discordNewsItem.update({ where: { id: delivery.newsItemId }, data: { status: 'PUBLISHED', postedAt: new Date() } }); }
  async failed(id: string, code: string): Promise<void> { await this.prisma.discordNewsDelivery.update({ where: { id }, data: { status: 'RETRYABLE_FAILURE', failureCode: code } }); }
  async uncertain(id: string): Promise<void> { const delivery = await this.prisma.discordNewsDelivery.update({ where: { id }, data: { status: 'DELIVERY_UNCERTAIN', failureCode: 'RECEIPT_UNCERTAIN' }, select: { newsItemId: true } }); await this.prisma.discordNewsItem.update({ where: { id: delivery.newsItemId }, data: { status: 'DELIVERY_UNCERTAIN' } }); }
}

function mapItem(row: { id: string; sourceId: string; canonicalUrl: string; title: string; publishedAt: Date; category: string; priority: string; summary: string; status: string }): StoredNewsItem { return { id: row.id, sourceId: row.sourceId, canonicalUrl: row.canonicalUrl, title: row.title, publishedAt: row.publishedAt, category: row.category, priority: row.priority, summary: row.summary, status: row.status }; }
