import { Prisma, PrismaClient } from '../../generated/prisma/index.js';
import type { EmbedPayload } from '../embed-builder.js';

export type SpotlightKind = 'COLLECTOR' | 'COLLECTIBLE';
export type SpotlightStatus = 'PENDING_APPROVAL' | 'APPROVED' | 'PUBLISHED' | 'CANCELLED' | 'BLOCKED';
export type Spotlight = { id: string; guildId: string; kind: SpotlightKind; sourceSlug: string; requesterDiscordUserId: string; approvedByDiscordUserId: string | null; status: SpotlightStatus; editorialTitle: string | null; editorialCopy: string | null; targetChannelId: string | null; embedDraftId: string | null; sourceSnapshot: EmbedPayload; publishedAt: Date | null; blockedReason: string | null; revision: number; createdAt: Date };

export class PrismaSpotlightRepository {
  constructor(private readonly prisma: PrismaClient, private readonly now: () => Date = () => new Date()) {}
  async create(input: Omit<Spotlight, 'id' | 'approvedByDiscordUserId' | 'status' | 'targetChannelId' | 'embedDraftId' | 'publishedAt' | 'blockedReason' | 'revision' | 'createdAt'>): Promise<Spotlight> { const row = await this.prisma.discordSpotlight.create({ data: { ...input, sourceSnapshot: input.sourceSnapshot as Prisma.InputJsonValue, auditEvents: { create: { actorDiscordUserId: input.requesterDiscordUserId, action: 'REQUESTED' } } } }); return map(row); }
  async get(id: string, guildId: string): Promise<Spotlight | null> { const row = await this.prisma.discordSpotlight.findFirst({ where: { id, guildId } }); return row ? map(row) : null; }
  async list(guildId: string): Promise<Spotlight[]> { return (await this.prisma.discordSpotlight.findMany({ where: { guildId }, orderBy: { createdAt: 'desc' }, take: 50 })).map(map); }
  async approve(id: string, guildId: string, actor: string, revision: number): Promise<Spotlight | null> { return this.transition(id, guildId, actor, revision, 'PENDING_APPROVAL', { status: 'APPROVED', approvedByDiscordUserId: actor }, 'APPROVED'); }
  async cancel(id: string, guildId: string, actor: string, revision: number): Promise<Spotlight | null> { const result = await this.prisma.discordSpotlight.updateMany({ where: { id, guildId, revision, status: { in: ['PENDING_APPROVAL', 'APPROVED', 'BLOCKED'] } }, data: { status: 'CANCELLED', revision: { increment: 1 } } }); if (!result.count) return null; await this.audit(id, actor, 'CANCELLED'); return this.get(id, guildId); }
  async edit(id: string, guildId: string, actor: string, revision: number, input: { title?: string | null; copy?: string | null }): Promise<Spotlight | null> { const result = await this.prisma.discordSpotlight.updateMany({ where: { id, guildId, revision, status: { in: ['PENDING_APPROVAL', 'APPROVED', 'BLOCKED'] } }, data: { ...(input.title !== undefined ? { editorialTitle: input.title } : {}), ...(input.copy !== undefined ? { editorialCopy: input.copy } : {}), revision: { increment: 1 } } }); if (!result.count) return null; await this.audit(id, actor, 'EDITORIAL_UPDATED'); return this.get(id, guildId); }
  async refresh(id: string, guildId: string, actor: string, revision: number, snapshot: EmbedPayload): Promise<Spotlight | null> { const result = await this.prisma.discordSpotlight.updateMany({ where: { id, guildId, revision, status: { in: ['APPROVED', 'BLOCKED'] } }, data: { sourceSnapshot: snapshot as Prisma.InputJsonValue, status: 'APPROVED', blockedReason: null, revision: { increment: 1 } } }); if (!result.count) return null; await this.audit(id, actor, 'SOURCE_REFRESHED'); return this.get(id, guildId); }
  async block(id: string, guildId: string, actor: string, revision: number, reason: string): Promise<Spotlight | null> { const result = await this.prisma.discordSpotlight.updateMany({ where: { id, guildId, revision, status: { in: ['APPROVED', 'BLOCKED'] } }, data: { status: 'BLOCKED', blockedReason: reason.slice(0, 300), revision: { increment: 1 } } }); if (!result.count) return null; await this.audit(id, actor, 'BLOCKED', { reason }); return this.get(id, guildId); }
  async attachDraft(id: string, guildId: string, actor: string, revision: number, draftId: string): Promise<Spotlight | null> { const result = await this.prisma.discordSpotlight.updateMany({ where: { id, guildId, revision, status: 'APPROVED' }, data: { embedDraftId: draftId, revision: { increment: 1 } } }); if (!result.count) return null; await this.audit(id, actor, 'DRAFT_READY', { draftId }); return this.get(id, guildId); }
  async published(id: string, guildId: string, actor: string, revision: number, draftId: string, channelId: string): Promise<Spotlight | null> { const result = await this.prisma.discordSpotlight.updateMany({ where: { id, guildId, revision, status: 'APPROVED' }, data: { status: 'PUBLISHED', embedDraftId: draftId, targetChannelId: channelId, publishedAt: this.now(), revision: { increment: 1 } } }); if (!result.count) return null; await this.audit(id, actor, 'PUBLISHED', { draftId, channelId }); return this.get(id, guildId); }
  async cooldown(guildId: string, kind: SpotlightKind, sourceSlug: string, days = 14): Promise<boolean> { return Boolean(await this.prisma.discordSpotlight.findFirst({ where: { guildId, kind, sourceSlug, status: 'PUBLISHED', publishedAt: { gte: new Date(this.now().getTime() - days * 86_400_000) } }, select: { id: true } })); }
  private async transition(id: string, guildId: string, actor: string, revision: number, from: SpotlightStatus, data: Prisma.DiscordSpotlightUpdateManyMutationInput, action: string) { const result = await this.prisma.discordSpotlight.updateMany({ where: { id, guildId, revision, status: from }, data: { ...data, revision: { increment: 1 } } }); if (!result.count) return null; await this.audit(id, actor, action); return this.get(id, guildId); }
  private async audit(spotlightId: string, actorDiscordUserId: string, action: string, details?: Record<string, string>) { await this.prisma.discordSpotlightAuditEvent.create({ data: { spotlightId, actorDiscordUserId, action, details: details as Prisma.InputJsonValue | undefined } }); }
}
function map(row: { id: string; guildId: string; kind: string; sourceSlug: string; requesterDiscordUserId: string; approvedByDiscordUserId: string | null; status: string; editorialTitle: string | null; editorialCopy: string | null; targetChannelId: string | null; embedDraftId: string | null; sourceSnapshot: unknown; publishedAt: Date | null; blockedReason: string | null; revision: number; createdAt: Date }): Spotlight { return { ...row, kind: row.kind as SpotlightKind, status: row.status as SpotlightStatus, sourceSnapshot: row.sourceSnapshot as EmbedPayload }; }
