import { PrismaClient } from '../../generated/prisma/index.js';
import type { CreatedTicket, TicketRepository } from '../ticket-creation.js';
import type { LifecycleRepository, LifecycleTicket } from '../ticket-lifecycle.js';
import type { InactivityRepository } from '../ticket-inactivity.js';
import type { TranscriptRecord, TranscriptRepository, TranscriptSource } from '../ticket-transcripts.js';

export type PrismaTicketRepositoryOptions = {
  beforeLifecycleEventInsert?: () => void | Promise<void>;
};

export class PrismaTicketRepository implements TicketRepository, LifecycleRepository, InactivityRepository, TranscriptRepository {
  constructor(
    private readonly prisma: PrismaClient,
    private readonly options: PrismaTicketRepositoryOptions = {},
  ) {}
  async findActive(guildId: string, creatorDiscordId: string): Promise<CreatedTicket[]> { const rows = await this.prisma.discordTicket.findMany({ where: { guildId, creatorDiscordId, status: { not: 'CLOSED' } } }); return rows.map((row) => ({ id: row.id, guildId: row.guildId, channelId: row.channelId ?? '', channelName: '', category: row.category, subject: row.subject, safeSummary: row.safeSummary, priority: row.priority, createdAt: row.createdAt })); }
  async create(ticket: CreatedTicket & { creatorDiscordId: string; referenceId?: string }): Promise<void> { await this.prisma.$transaction(async (db) => { await db.discordGuildConfig.upsert({ where: { guildId: ticket.guildId }, create: { guildId: ticket.guildId, setupVersion: 0, setupStatus: 'NOT_CONFIGURED' }, update: {} }); await db.discordTicket.create({ data: { id: ticket.id, guildId: ticket.guildId, creatorDiscordId: ticket.creatorDiscordId, category: ticket.category, channelId: ticket.channelId, subject: ticket.subject, safeSummary: ticket.safeSummary, safeReferenceId: ticket.referenceId, status: 'OPEN', priority: ticket.priority, lastActivityAt: ticket.createdAt, createdAt: ticket.createdAt } }); await db.discordTicketEvent.create({ data: { ticketId: ticket.id, type: 'CREATED', actorDiscordId: ticket.creatorDiscordId, metadata: { channelId: ticket.channelId, category: ticket.category } } }); }); }
  async delete(ticketId: string): Promise<void> { await this.prisma.discordTicket.delete({ where: { id: ticketId } }); }
  async get(id: string, guildId: string): Promise<LifecycleTicket | null> { const row = await this.prisma.discordTicket.findFirst({ where: { id, guildId } }); return row ? lifecycleTicket(row) : null; }
  async findByChannel(guildId: string, channelId: string): Promise<LifecycleTicket | null> { const row = await this.prisma.discordTicket.findFirst({ where: { guildId, channelId } }); return row ? lifecycleTicket(row) : null; }
  async recordActivity(guildId: string, channelId: string): Promise<boolean> { const result = await this.prisma.discordTicket.updateMany({ where: { guildId, channelId, status: { in: ['OPEN', 'CLAIMED', 'WAITING_USER', 'WAITING_STAFF', 'ESCALATED'] } }, data: { lastActivityAt: new Date(), inactivityWarnedAt: null } }); return result.count === 1; }
  async listWarningCandidates(before: Date, limit: number): Promise<LifecycleTicket[]> { return (await this.prisma.discordTicket.findMany({ where: { status: 'WAITING_USER', lastActivityAt: { lte: before }, inactivityWarnedAt: null }, orderBy: [{ lastActivityAt: 'asc' }, { id: 'asc' }], take: limit })).map(lifecycleTicket); }
  async listCloseCandidates(before: Date, limit: number): Promise<LifecycleTicket[]> { return (await this.prisma.discordTicket.findMany({ where: { status: 'WAITING_USER', inactivityWarnedAt: { lte: before } }, orderBy: [{ inactivityWarnedAt: 'asc' }, { id: 'asc' }], take: limit })).map(lifecycleTicket); }
  async markWarning(ticket: LifecycleTicket, at: Date): Promise<boolean> { const result = await this.prisma.discordTicket.updateMany({ where: { id: ticket.id, guildId: ticket.guildId, status: 'WAITING_USER', updatedAt: ticket.updatedAt, inactivityWarnedAt: null }, data: { inactivityWarnedAt: at } }); return result.count === 1; }
  async getTranscriptSource(ticketId: string, guildId: string): Promise<TranscriptSource | null> { const row = await this.prisma.discordTicket.findFirst({ where: { id: ticketId, guildId }, include: { events: { orderBy: { createdAt: 'asc' } } } }); return row ? { ...lifecycleTicket(row), safeSummary: row.safeSummary, events: row.events.map((event) => ({ type: event.type, actorDiscordId: event.actorDiscordId ?? undefined, metadata: event.metadata as Record<string, unknown> | null, createdAt: event.createdAt })) } : null; }
  async getTranscript(ticketId: string): Promise<TranscriptRecord | null> { const row = await this.prisma.discordTicketTranscript.findUnique({ where: { ticketId } }); return row ? { ticketId: row.ticketId, status: row.status, content: row.content, messageCount: row.messageCount, failureReason: row.failureReason ?? undefined, deliveryChannelId: row.deliveryChannelId ?? undefined, deliveredAt: row.deliveredAt ?? undefined } : null; }
  async saveTranscript(record: TranscriptRecord, retryFailed: boolean): Promise<TranscriptRecord> { const row = await this.prisma.discordTicketTranscript.upsert({ where: { ticketId: record.ticketId }, create: { ticketId: record.ticketId, status: record.status, content: record.content, messageCount: record.messageCount, failureReason: record.failureReason }, update: retryFailed ? { status: record.status, content: record.content, messageCount: record.messageCount, failureReason: record.failureReason } : {} }); return { ticketId: row.ticketId, status: row.status, content: row.content, messageCount: row.messageCount, failureReason: row.failureReason ?? undefined, deliveryChannelId: row.deliveryChannelId ?? undefined, deliveredAt: row.deliveredAt ?? undefined }; }
  async markTranscriptDelivered(ticketId: string, channelId: string): Promise<void> { await this.prisma.discordTicketTranscript.update({ where: { ticketId }, data: { deliveryChannelId: channelId, deliveredAt: new Date() } }); }
  async compareAndSet(ticket: LifecycleTicket, event: string, actor: string, metadata?: Record<string, string>): Promise<boolean> { return this.prisma.$transaction(async (db) => { const result = await db.discordTicket.updateMany({ where: { id: ticket.id, guildId: ticket.guildId, updatedAt: ticket.updatedAt }, data: { status: ticket.status, priority: ticket.priority, assignedStaffId: ticket.assignedStaffId ?? null, resolvedAt: ticket.resolvedAt ?? null, closedAt: ticket.closedAt ?? null, lastActivityAt: new Date() } }); if (result.count !== 1) return false; await this.options.beforeLifecycleEventInsert?.(); await db.discordTicketEvent.create({ data: { ticketId: ticket.id, type: event, actorDiscordId: actor, metadata } }); return true; }); }
}
function lifecycleTicket(row: { id: string; guildId: string; channelId: string | null; creatorDiscordId: string; category: string; subject: string; createdAt: Date; lastActivityAt: Date; inactivityWarnedAt: Date | null; status: LifecycleTicket['status']; priority: LifecycleTicket['priority']; assignedStaffId: string | null; resolvedAt: Date | null; closedAt: Date | null; updatedAt: Date }): LifecycleTicket { return { id: row.id, guildId: row.guildId, channelId: row.channelId ?? '', creatorId: row.creatorDiscordId, category: row.category, subject: row.subject, createdAt: row.createdAt, lastActivityAt: row.lastActivityAt, inactivityWarnedAt: row.inactivityWarnedAt ?? undefined, status: row.status, priority: row.priority, assignedStaffId: row.assignedStaffId ?? undefined, resolvedAt: row.resolvedAt ?? undefined, closedAt: row.closedAt ?? undefined, updatedAt: row.updatedAt }; }
