import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { PrismaClient } from '../../generated/prisma/index.js';
import { PrismaAnnouncementScheduleRepository } from '../../src/persistence/announcement-schedule-repository.js';
import { testDatabaseUrl } from '../test-database-url.js';

const prisma = new PrismaClient({ datasources: { db: { url: testDatabaseUrl() } } });
const now = new Date('2026-08-18T14:00:00.000Z'); const prefix = `announcement-schedule-${Date.now()}`;
const repository = new PrismaAnnouncementScheduleRepository(prisma, () => now); const ids: string[] = []; let draftId = '';
async function create(type: 'ONE_TIME' | 'DAILY' = 'DAILY') { const row = await repository.create({ guildId: `${prefix}-guild`, draftId, actorId: 'admin', name: `Schedule ${ids.length}`, timing: type === 'ONE_TIME' ? { type, timezone: 'America/New_York', localTime: '09:00', date: '2026-08-19' } : { type, timezone: 'America/New_York', localTime: '09:00' }, payloadMode: 'SNAPSHOT', payloadSnapshot: { title: 'Announcement' }, linkButtonsSnapshot: [], targetChannelId: 'channel-a' }); ids.push(row.id); return row; }

beforeAll(async () => { await prisma.$connect(); const draft = await prisma.discordEmbedDraft.create({ data: { guildId: `${prefix}-guild`, creatorDiscordUserId: 'admin', name: 'Source', payload: { title: 'Announcement' }, linkButtons: [] } }); draftId = draft.id; });
afterAll(async () => { if (ids.length) await prisma.discordAnnouncementSchedule.deleteMany({ where: { id: { in: ids } } }); if (draftId) await prisma.discordEmbedDraft.delete({ where: { id: draftId } }); await prisma.$disconnect(); });

describe('Prisma announcement scheduler authority', () => {
  it('persists snapshot intent, UTC due time, and schedule audit', async () => { const row = await create('ONE_TIME'); expect(row.nextRunAt?.toISOString()).toBe('2026-08-19T13:00:00.000Z'); expect(row.payloadMode).toBe('SNAPSHOT'); expect(await prisma.discordAnnouncementScheduleAuditEvent.count({ where: { scheduleId: row.id, action: 'SCHEDULE_CREATED' } })).toBe(1); });
  it('claims a due occurrence exactly once across concurrent worker attempts', async () => { const row = await create(); await prisma.discordAnnouncementSchedule.update({ where: { id: row.id }, data: { nextRunAt: new Date(now.getTime() - 1_000) } }); const [first, second] = await Promise.all([repository.claimDue('worker-one', 60), repository.claimDue('worker-two', 60)]); expect(first.length + second.length).toBe(1); expect(await prisma.discordScheduledPublicationRun.count({ where: { scheduleId: row.id } })).toBe(1); });
  it('uses revision control for pause and resumes at the next future local occurrence', async () => { const row = await create(); const paused = await repository.pause(row.id, row.guildId, 'admin', row.version); expect(paused?.status).toBe('PAUSED'); expect(await repository.pause(row.id, row.guildId, 'admin', row.version)).toBeNull(); const resumed = await repository.resume(row.id, row.guildId, 'admin', paused!.version); expect(resumed?.status).toBe('SCHEDULED'); expect(resumed?.nextRunAt?.getTime()).toBeGreaterThan(now.getTime()); });
  it('soft-cancels while preserving durable history and audit records', async () => { const row = await create(); expect(await repository.cancel(row.id, row.guildId, 'admin', row.version)).toBe(true); expect((await repository.get(row.id, row.guildId))?.status).toBe('CANCELLED'); expect(await prisma.discordAnnouncementScheduleAuditEvent.count({ where: { scheduleId: row.id, action: 'SCHEDULE_CANCELLED' } })).toBe(1); });
  it('marks an expired lease unknown instead of publishing it again', async () => { const row = await create(); await prisma.discordAnnouncementSchedule.update({ where: { id: row.id }, data: { status: 'PROCESSING', leaseExpiresAt: new Date(now.getTime() - 1) } }); await prisma.discordScheduledPublicationRun.create({ data: { scheduleId: row.id, scheduledFor: new Date(now.getTime() - 2_000), status: 'PROCESSING' } }); expect(await repository.recoverExpiredLeases()).toBeGreaterThan(0); expect((await repository.get(row.id, row.guildId))?.status).toBe('BLOCKED'); expect(await prisma.discordScheduledPublicationRun.count({ where: { scheduleId: row.id, status: 'UNKNOWN_DELIVERY_STATE' } })).toBe(1); });
});
