import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { PrismaClient } from '../../generated/prisma/index.js';
import { PrismaTicketRepository } from '../../src/persistence/ticket-repository.js';

const databaseUrl = process.env.TEST_DATABASE_URL ?? process.env.DATABASE_URL;
const prisma = new PrismaClient({ datasources: databaseUrl ? { db: { url: databaseUrl } } : undefined });
const repository = new PrismaTicketRepository(prisma); const prefix = `discord-test-${Date.now()}`;
let guildA = ''; let guildB = ''; let ticketId = ''; let guildFixturesCreated = false;
beforeAll(async () => { await prisma.$connect(); guildA = `${prefix}-a`; guildB = `${prefix}-b`; await prisma.discordGuildConfig.createMany({ data: [{ guildId: guildA, setupVersion: 0, setupStatus: 'NOT_CONFIGURED' }, { guildId: guildB, setupVersion: 0, setupStatus: 'NOT_CONFIGURED' }] }); guildFixturesCreated = true; const ticket = await prisma.discordTicket.create({ data: { guildId: guildA, creatorDiscordId: 'creator', category: 'general-support', channelId: `${prefix}-channel`, subject: 'Integration ticket', safeSummary: 'Safe test fixture', status: 'OPEN', priority: 'NORMAL' } }); ticketId = ticket.id; });
afterAll(async () => { if (guildFixturesCreated) await prisma.discordGuildConfig.deleteMany({ where: { guildId: { in: [guildA, guildB] } } }); await prisma.$disconnect(); });
describe('PrismaTicketRepository lifecycle authority', () => {
  it('loads only within the trusted guild scope', async () => { expect(await repository.get(ticketId, guildA)).toMatchObject({ id: ticketId, guildId: guildA }); expect(await repository.get(ticketId, guildB)).toBeNull(); });
  it('commits state and exactly one event atomically', async () => { const current = await repository.get(ticketId, guildA); if (!current) throw new Error('fixture missing'); expect(await repository.compareAndSet({ ...current, status: 'WAITING_USER' }, 'STATUS_CHANGED', 'staff', { status: 'WAITING_USER' })).toBe(true); expect(await prisma.discordTicket.findUnique({ where: { id: ticketId } })).toMatchObject({ status: 'WAITING_USER' }); expect(await prisma.discordTicketEvent.count({ where: { ticketId, type: 'STATUS_CHANGED' } })).toBe(1); });
  it('rejects stale compare-and-set without a stale event', async () => { const stale = await repository.get(ticketId, guildA); if (!stale) throw new Error('fixture missing'); expect(await repository.compareAndSet({ ...stale, priority: 'HIGH' }, 'PRIORITY_CHANGED', 'staff', { priority: 'HIGH' })).toBe(true); expect(await repository.compareAndSet({ ...stale, priority: 'URGENT' }, 'PRIORITY_CHANGED', 'staff', { priority: 'URGENT' })).toBe(false); expect(await prisma.discordTicket.findUnique({ where: { id: ticketId } })).toMatchObject({ priority: 'HIGH' }); expect(await prisma.discordTicketEvent.count({ where: { ticketId, type: 'PRIORITY_CHANGED' } })).toBe(1); });
  it('rolls back the state mutation when lifecycle event persistence fails', async () => { const current = await repository.get(ticketId, guildA); if (!current) throw new Error('fixture missing'); const failingRepository = new PrismaTicketRepository(prisma, { beforeLifecycleEventInsert: () => { throw new Error('test event write failure'); } }); await expect(failingRepository.compareAndSet({ ...current, priority: 'URGENT' }, 'PRIORITY_CHANGED', 'staff', { priority: 'URGENT' })).rejects.toThrow('test event write failure'); expect(await prisma.discordTicket.findUnique({ where: { id: ticketId } })).toMatchObject({ priority: 'HIGH' }); expect(await prisma.discordTicketEvent.count({ where: { ticketId, type: 'PRIORITY_CHANGED' } })).toBe(1); });
  it('permits exactly one concurrent transfer from the same ticket version', async () => { const first = await repository.get(ticketId, guildA); const second = await repository.get(ticketId, guildA); if (!first || !second) throw new Error('fixture missing'); const results = await Promise.all([repository.compareAndSet({ ...first, assignedStaffId: 'staff-alpha', status: 'CLAIMED' }, 'TRANSFERRED', 'staff', { newAssigneeDiscordId: 'staff-alpha' }), repository.compareAndSet({ ...second, assignedStaffId: 'staff-beta', status: 'CLAIMED' }, 'TRANSFERRED', 'staff', { newAssigneeDiscordId: 'staff-beta' })]); expect(results.filter(Boolean)).toHaveLength(1); expect(await prisma.discordTicket.findUnique({ where: { id: ticketId } })).toMatchObject({ status: 'CLAIMED', assignedStaffId: expect.stringMatching(/^staff-(alpha|beta)$/) }); expect(await prisma.discordTicketEvent.count({ where: { ticketId, type: 'TRANSFERRED' } })).toBe(1); });
});
