import { SlashCommandBuilder } from 'discord.js';

export const ticketsCommand = new SlashCommandBuilder()
  .setName('tickets').setDescription('Staff ticket operations')
  .addSubcommand((sub) => sub.setName('queue').setDescription('View the current support queue').addStringOption((option) => option.setName('filter').setDescription('Queue filter').setRequired(true).addChoices({ name: 'Open', value: 'OPEN' }, { name: 'Unassigned', value: 'UNASSIGNED' }, { name: 'Mine', value: 'MINE' }, { name: 'High priority', value: 'HIGH_PRIORITY' }, { name: 'SLA at risk', value: 'SLA_RISK' }, { name: 'SLA breached', value: 'SLA_BREACHED' }, { name: 'Category', value: 'CATEGORY' }, { name: 'All active', value: 'ALL' })).addStringOption((option) => option.setName('category').setDescription('Routing category for the category filter')).addStringOption((option) => option.setName('status').setDescription('Optional ticket status')).addUserOption((option) => option.setName('assignee').setDescription('Optional assigned staff member')))
  .addSubcommand((sub) => sub.setName('search').setDescription('Search tickets in this server').addStringOption((option) => option.setName('reference').setDescription('Ticket reference prefix')).addUserOption((option) => option.setName('member').setDescription('Requester')).addStringOption((option) => option.setName('category').setDescription('Category')).addStringOption((option) => option.setName('tag').setDescription('Tag key')).addStringOption((option) => option.setName('status').setDescription('Ticket status')).addUserOption((option) => option.setName('assignee').setDescription('Assigned staff')).addIntegerOption((option) => option.setName('created-within-days').setDescription('Bounded window: 1–90 days').setMinValue(1).setMaxValue(90)))
  .addSubcommand((sub) => sub.setName('view').setDescription('View a staff ticket record').addStringOption((option) => option.setName('reference').setDescription('Ticket reference').setRequired(true)))
  .addSubcommand((sub) => sub.setName('stats').setDescription('View support operations statistics').addStringOption((option) => option.setName('period').setDescription('Reporting period').setRequired(true).addChoices({ name: '7 days', value: '7d' }, { name: '30 days', value: '30d' })));

export const ticketConfigCommand = new SlashCommandBuilder()
  .setName('ticket-config').setDescription('Configure support forms and policies')
  .addSubcommand((sub) => sub.setName('categories').setDescription('Review current configured category policies'))
  .addSubcommand((sub) => sub.setName('form').setDescription('Review the active versioned intake form').addStringOption((option) => option.setName('category').setDescription('Category').setRequired(true)))
  .addSubcommand((sub) => sub.setName('form-edit').setDescription('Edit one active intake question').addStringOption((option) => option.setName('category').setDescription('Category').setRequired(true)).addStringOption((option) => option.setName('key').setDescription('Stable question key').setRequired(true)).addStringOption((option) => option.setName('label').setDescription('New question label').setRequired(true).setMaxLength(45)).addBooleanOption((option) => option.setName('required').setDescription('Whether a response is required')))
  .addSubcommand((sub) => sub.setName('form-reorder').setDescription('Move one active intake question').addStringOption((option) => option.setName('category').setDescription('Category').setRequired(true)).addStringOption((option) => option.setName('key').setDescription('Stable question key').setRequired(true)).addIntegerOption((option) => option.setName('position').setDescription('Position, starting at 1').setRequired(true).setMinValue(1).setMaxValue(20)))
  .addSubcommand((sub) => sub.setName('routing').setDescription('Set category routing to a managed role key').addStringOption((option) => option.setName('category').setDescription('Category').setRequired(true)).addStringOption((option) => option.setName('team').setDescription('Managed role key, or clear').setRequired(true)))
  .addSubcommand((sub) => sub.setName('sla').setDescription('Set category SLA targets in minutes').addStringOption((option) => option.setName('category').setDescription('Category').setRequired(true)).addIntegerOption((option) => option.setName('first-response-minutes').setDescription('First human staff response target').setRequired(true).setMinValue(1).setMaxValue(43200)).addIntegerOption((option) => option.setName('resolution-minutes').setDescription('Resolution target').setRequired(true).setMinValue(1).setMaxValue(129600)))
  .addSubcommand((sub) => sub.setName('tags').setDescription('Create or disable a ticket tag').addStringOption((option) => option.setName('action').setDescription('Tag action').setRequired(true).addChoices({ name: 'Create or update', value: 'UPSERT' }, { name: 'Disable', value: 'DISABLE' })).addStringOption((option) => option.setName('key').setDescription('Stable tag key').setRequired(true)).addStringOption((option) => option.setName('label').setDescription('Display label')))
  .addSubcommand((sub) => sub.setName('inactivity').setDescription('Set category inactivity policy').addStringOption((option) => option.setName('category').setDescription('Category').setRequired(true)).addIntegerOption((option) => option.setName('warning-hours').setDescription('Hours before one warning').setRequired(true).setMinValue(1).setMaxValue(720)).addIntegerOption((option) => option.setName('close-hours').setDescription('Hours after warning before automatic close').setRequired(true).setMinValue(1).setMaxValue(720)).addBooleanOption((option) => option.setName('protected').setDescription('Prevent automatic close for new tickets')));
