import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ChatInputCommandInteraction, PermissionFlagsBits, SlashCommandBuilder, StringSelectMenuBuilder } from 'discord.js';
import { SliceEmbed } from '../embeds/slice-embed.js';
import { sanitizeTicketText } from '../tickets.js';
import { type Poll, PrismaCommunityRepository, type Suggestion } from '../persistence/community-repository.js';
import type { BotConfig } from '../config.js';

export const notificationsCommand = new SlashCommandBuilder().setName('notifications').setDescription('View or update notification role preferences');
export const suggestCommand = new SlashCommandBuilder().setName('suggest').setDescription('Submit a community suggestion').addStringOption((o) => o.setName('idea').setDescription('Your suggestion').setRequired(true).setMaxLength(700));
export const suggestionCommand = new SlashCommandBuilder().setName('suggestion').setDescription('Manage a community suggestion').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addIntegerOption((o) => o.setName('reference').setDescription('Suggestion number').setRequired(true).setMinValue(1)).addStringOption((o) => o.setName('status').setDescription('New status').setRequired(true).addChoices({ name: 'Under review', value: 'UNDER_REVIEW' }, { name: 'Accepted', value: 'ACCEPTED' }, { name: 'Declined', value: 'DECLINED' }, { name: 'Implemented', value: 'IMPLEMENTED' }));
export const pollCommand = new SlashCommandBuilder().setName('poll').setDescription('Create a community poll').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption((o) => o.setName('question').setDescription('Question').setRequired(true).setMaxLength(300)).addStringOption((o) => o.setName('option1').setDescription('First option').setRequired(true).setMaxLength(120)).addStringOption((o) => o.setName('option2').setDescription('Second option').setRequired(true).setMaxLength(120)).addStringOption((o) => o.setName('option3').setDescription('Optional third option').setMaxLength(120)).addStringOption((o) => o.setName('option4').setDescription('Optional fourth option').setMaxLength(120)).addStringOption((o) => o.setName('option5').setDescription('Optional fifth option').setMaxLength(120)).addIntegerOption((o) => o.setName('hours').setDescription('Optional duration in hours').setMinValue(1).setMaxValue(168));
export const birthdayCommand = new SlashCommandBuilder().setName('birthday').setDescription('Manage your birthday').addSubcommand((s) => s.setName('set').setDescription('Store month and day only').addIntegerOption((o) => o.setName('month').setDescription('Month').setRequired(true).setMinValue(1).setMaxValue(12)).addIntegerOption((o) => o.setName('day').setDescription('Day').setRequired(true).setMinValue(1).setMaxValue(31))).addSubcommand((s) => s.setName('remove').setDescription('Remove your birthday')).addSubcommand((s) => s.setName('view').setDescription('View your saved month and day'));

export function suggestionPayload(suggestion: Suggestion, counts: { up: number; down: number }) { return { embeds: [SliceEmbed.info(`Suggestion #${suggestion.referenceNumber} · ${suggestion.status.replace(/_/g, ' ')}`, `${suggestion.content}\n\n👍 **${counts.up}** · 👎 **${counts.down}**\nSubmitted by <@${suggestion.creatorDiscordUserId}>`)], components: [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`slice:community:suggestion:${suggestion.id}:up`).setEmoji('👍').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`slice:community:suggestion:${suggestion.id}:down`).setEmoji('👎').setStyle(ButtonStyle.Secondary))] }; }
export function pollPayload(poll: Poll, counts: number[]) { const closed = poll.status !== 'OPEN' || Boolean(poll.closesAt && poll.closesAt <= new Date()); const body = poll.options.map((option, index) => `**${index + 1}.** ${option} — **${counts[index] ?? 0}** vote${counts[index] === 1 ? '' : 's'}`).join('\n'); return { embeds: [SliceEmbed.info(closed ? 'Community poll · CLOSED' : 'Community poll', `${poll.question}\n\n${body}${poll.closesAt ? `\n\nCloses: <t:${Math.floor(poll.closesAt.getTime() / 1000)}:R>` : ''}`)], components: closed ? [] : [new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId(`slice:community:poll:${poll.id}`).setPlaceholder('Cast or replace your vote').addOptions(poll.options.map((label, value) => ({ label, value: String(value) }))))] }; }

export async function handleCommunityCommand(interaction: ChatInputCommandInteraction, repository: PrismaCommunityRepository, config: Pick<BotConfig, 'SUGGESTIONS_ENABLED' | 'SUGGESTIONS_CHANNEL_LOGICAL_KEY' | 'POLLS_ENABLED' | 'POLL_MAX_OPTIONS' | 'BIRTHDAYS_ENABLED'>, channelFor: (key: string) => Promise<{ id: string; send(payload: object): Promise<{ id: string }> } | null>, notification: () => Promise<void>, refreshSuggestion: (suggestion: Suggestion) => Promise<void>): Promise<void> {
  if (!interaction.guildId) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Guild only', 'Community features are available in a Slice server.')] });
  if ((interaction.commandName === 'suggestion' || interaction.commandName === 'poll') && !interaction.memberPermissions?.has(PermissionFlagsBits.ManageGuild)) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Staff only', 'You need Manage Server permission to use that community management command.')] });
  if (interaction.commandName === 'notifications') return void await notification();
  if (interaction.commandName === 'birthday') { if (!config.BIRTHDAYS_ENABLED) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Birthdays unavailable', 'Birthdays are currently disabled.')] }); const sub = interaction.options.getSubcommand(); if (sub === 'remove') { await repository.removeBirthday(interaction.guildId, interaction.user.id); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.success('Birthday removed', 'Your month and day have been removed.')] }); } if (sub === 'view') { const birthday = await repository.birthday(interaction.guildId, interaction.user.id); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.info('Your birthday', birthday ? `Saved as **${birthday.month}/${birthday.day}**. No birth year is stored.` : 'No birthday is saved.')] }); } const month = interaction.options.getInteger('month', true); const day = interaction.options.getInteger('day', true); if (day > new Date(2024, month, 0).getDate()) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Invalid birthday', 'That month and day combination is not valid.')] }); await repository.setBirthday(interaction.guildId, interaction.user.id, month, day); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.success('Birthday saved', `Saved **${month}/${day}**. No birth year is collected.`)] }); }
  if (interaction.commandName === 'suggest') { if (!config.SUGGESTIONS_ENABLED) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Suggestions unavailable', 'Suggestions are currently disabled.')] }); const content = safeCommunityText(interaction.options.getString('idea', true), 700); if (content.length < 8) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Suggestion too short', 'Please provide a concise, useful suggestion.')] }); const suggestion = await repository.createSuggestion(interaction.guildId, interaction.user.id, content); const channel = await channelFor(config.SUGGESTIONS_CHANNEL_LOGICAL_KEY); if (!channel) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Suggestions unavailable', 'The configured suggestions channel needs `/setup repair`.')] }); const message = await channel.send(suggestionPayload(suggestion, { up: 0, down: 0 })); await repository.attachSuggestion(suggestion.id, channel.id, message.id); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.success('Suggestion submitted', `Suggestion #${suggestion.referenceNumber} was posted for community feedback.`)] }); }
  if (interaction.commandName === 'suggestion') { const suggestion = await repository.suggestionByReference(interaction.guildId, interaction.options.getInteger('reference', true)); if (!suggestion) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Suggestion unavailable', 'That community suggestion was not found.')] }); const updated = await repository.setSuggestionStatus(suggestion.id, interaction.options.getString('status', true)); await refreshSuggestion(updated); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.success('Suggestion updated', `Suggestion #${updated.referenceNumber} is now **${updated.status.replace(/_/g, ' ')}**.`)] }); }
  if (!config.POLLS_ENABLED) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Polls unavailable', 'Polls are currently disabled.')] }); const values = ['option1', 'option2', 'option3', 'option4', 'option5'].map((key) => interaction.options.getString(key)).filter((value): value is string => Boolean(value)).slice(0, config.POLL_MAX_OPTIONS).map((value) => safeCommunityText(value, 120)); if (values.length < 2 || new Set(values.map((value) => value.toLowerCase())).size !== values.length) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Invalid poll options', 'Use 2–5 distinct, non-empty options.')] }); const hours = interaction.options.getInteger('hours'); const poll = await repository.createPoll(interaction.guildId, interaction.user.id, safeCommunityText(interaction.options.getString('question', true), 300), values, hours ? new Date(Date.now() + hours * 3_600_000) : null); const channel = interaction.channel; const message = channel?.isSendable() ? await channel.send(pollPayload(poll, values.map(() => 0))) : null; if (!message) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Poll unavailable', 'This channel cannot host a community poll.')] }); await repository.attachPoll(poll.id, interaction.channelId!, message.id); await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.success('Poll created', 'The persistent community poll is now open.')] }); }
function safeCommunityText(value: string, maxLength: number): string { return sanitizeTicketText(value).replace(/@(everyone|here)/gi, '@\u200b$1').replace(/<@!?&?\d+>/g, '[mention removed]').slice(0, maxLength).trim(); }
