import { ChatInputCommandInteraction, PermissionFlagsBits, SlashCommandBuilder } from 'discord.js';
import { SliceEmbed } from '../embeds/slice-embed.js';
import { sanitizeTicketText } from '../tickets.js';
import type { SetupRepository } from '../persistence/setup-repository.js';

export const inviteCommand = new SlashCommandBuilder().setName('invite').setDescription('Get the official Slice Discord invite');
export const roadmapCommand = new SlashCommandBuilder().setName('roadmap').setDescription('View the public Slice roadmap');
export const announceCommand = new SlashCommandBuilder().setName('announce').setDescription('Publish an official Slice update').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption((o) => o.setName('kind').setDescription('Destination').setRequired(true).addChoices({ name: 'News', value: 'news' }, { name: 'Platform update', value: 'platform-updates' })).addStringOption((o) => o.setName('title').setDescription('Title').setRequired(true).setMaxLength(120)).addStringOption((o) => o.setName('message').setDescription('Official update').setRequired(true).setMaxLength(1500)).addBooleanOption((o) => o.setName('notify').setDescription('Mention the matching opt-in notification role'));
export const requestCommand = new SlashCommandBuilder().setName('request').setDescription('Post a community-only collecting request').addStringOption((o) => o.setName('asset').setDescription('Asset or collectible').setRequired(true).setMaxLength(120)).addStringOption((o) => o.setName('message').setDescription('Community interest details').setRequired(true).setMaxLength(500));
export const offerCommand = new SlashCommandBuilder().setName('offer').setDescription('Post a community-only collecting offer').addStringOption((o) => o.setName('asset').setDescription('Asset or collectible').setRequired(true).setMaxLength(120)).addStringOption((o) => o.setName('message').setDescription('Community interest details').setRequired(true).setMaxLength(500));
export async function handleGapSweep(interaction: ChatInputCommandInteraction, repository: SetupRepository, inviteUrl?: string): Promise<void> { if (interaction.commandName === 'invite') return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.info('Official Slice invite', inviteUrl ? `[Join the official Slice Discord](${inviteUrl})` : 'The official invite has not been configured yet. Ask a server administrator.')] }); if (interaction.commandName === 'roadmap') return void await interaction.reply({ embeds: [SliceEmbed.info('Slice roadmap', '**Community foundation** — Discord setup, support, moderation, and progression.\n**Market information** — Public market reads and factual analytics.\n**Notifications** — Backend-authoritative delivery integration when its consumer seam is published.\n\nRoadmap timing is maintained by Slice and may change.')] }); if (!interaction.guild) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Guild only', 'This community feature is available only in a Slice server.')] }); if (interaction.commandName === 'announce') { const kind = interaction.options.getString('kind', true); const resource = await repository.getResource(interaction.guild.id, 'CHANNEL', kind); const channel = resource ? await interaction.guild.channels.fetch(resource.discordId).catch(() => null) : null; if (!channel?.isTextBased() || !('send' in channel)) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Announcement unavailable', 'Run `/setup repair` to restore the managed announcement channel.')] }); const title = safe(interaction.options.getString('title', true), 120); const body = safe(interaction.options.getString('message', true), 1500); const notify = interaction.options.getBoolean('notify') === true; const role = notify ? await repository.getResource(interaction.guild.id, 'ROLE', kind) : null; await channel.send({ content: role ? `<@&${role.discordId}>` : undefined, embeds: [SliceEmbed.info(title, body)], allowedMentions: { parse: [], roles: role ? [role.discordId] : [], users: [], repliedUser: false } }); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.success('Official update published', `Posted to #${kind}.`)] }); } const asset = safe(interaction.options.getString('asset', true), 120); const body = safe(interaction.options.getString('message', true), 500); const title = interaction.commandName === 'request' ? 'Looking for · community request' : 'Community offer / interest'; await interaction.reply({ embeds: [SliceEmbed.info(title, `**${asset}**\n${body}\n\nPosted by <@${interaction.user.id}>. This is community discussion only—not an order, trade, reservation, or settlement.`)] }); }
function safe(value: string, max: number): string { return sanitizeTicketText(value).replace(/@(everyone|here)/gi, '@\u200b$1').replace(/<@!?&?\d+>/g, '[mention removed]').slice(0, max).trim(); }
