import { ChatInputCommandInteraction, SlashCommandBuilder, SlashCommandSubcommandBuilder } from 'discord.js';
import { SliceEmbed } from '../embeds/slice-embed.js';
import { PrismaInvestorProfileRepository, type ProfileVisibility } from '../persistence/investor-profile-repository.js';
import { ACHIEVEMENTS, MemberProgressionService } from '../progression.js';
import { MarketFeedRenderer } from '../market-renderer.js';
import { SliceWebsiteHandoffClient } from '../onboarding.js';
import { presentationConfig } from '../presentation-config.js';
import { DiscordPaginator } from '../paginator.js';
import { SliceBackendClient, type BackendResult, type MarketAsset, type PublicCollector } from '../slice-backend-client.js';

const copy = presentationConfig()['commands.yml'];
const assetOption = <T extends SlashCommandBuilder | SlashCommandSubcommandBuilder>(command: T): T => {
  command.addStringOption((option) => option.setName('asset').setDescription(copy.options.asset).setRequired(true).setMaxLength(120));
  return command;
};
const kind = (option: import('discord.js').SlashCommandStringOption) => option.setName('kind').setDescription('Market ranking').addChoices({ name: 'Gainers', value: 'gainers' }, { name: 'Losers', value: 'losers' }, { name: 'Most active', value: 'active' });

export const cardCommand = assetOption(new SlashCommandBuilder().setName('card').setDescription(copy.descriptions.card));
export const searchCommand = new SlashCommandBuilder().setName('search').setDescription(copy.descriptions.search).addStringOption((option) => option.setName('query').setDescription(copy.options.query).setRequired(true).setMaxLength(80));
export const valueCommand = assetOption(new SlashCommandBuilder().setName('value').setDescription(copy.descriptions.value));
export const priceCommand = assetOption(new SlashCommandBuilder().setName('price').setDescription(copy.descriptions.price));
export const historyCommand = assetOption(new SlashCommandBuilder().setName('history').setDescription(copy.descriptions.history));
export const topCommand = new SlashCommandBuilder().setName('top').setDescription(copy.descriptions.top).addStringOption((option) => option.setName('category').setDescription(copy.options.category).setRequired(true).addChoices({ name: 'Trending gainers', value: 'gainers' }, { name: 'Largest decliners', value: 'losers' }, { name: 'Most watched', value: 'active' }));
export const assetCommand = new SlashCommandBuilder().setName('asset').setDescription('Search or view public Slice collectibles')
  .addSubcommand((sub) => sub.setName('search').setDescription('Search public Slice collectibles').addStringOption((option) => option.setName('query').setDescription('Title or keyword').setMaxLength(80)).addStringOption((option) => option.setName('category').setDescription('Current Slice category slug').setMaxLength(96)).addStringOption((option) => option.setName('set').setDescription('Current Slice set slug').setMaxLength(96)).addStringOption((option) => option.setName('grading-company').setDescription('Grading company code').setMaxLength(16)).addNumberOption((option) => option.setName('grade-min').setDescription('Minimum grade').setMinValue(0).setMaxValue(100)).addNumberOption((option) => option.setName('grade-max').setDescription('Maximum grade').setMinValue(0).setMaxValue(100)))
  .addSubcommand((sub) => assetOption(sub.setName('view').setDescription('View a public Slice collectible')));
export const marketCommand = new SlashCommandBuilder().setName('market').setDescription('Read public Slice market data').addSubcommand((sub) => sub.setName('movers').setDescription('View authoritative market movers').addStringOption(kind));
export const collectorCommand = new SlashCommandBuilder().setName('collector').setDescription('Search or view public Slice Collector profiles').addSubcommand((sub) => sub.setName('search').setDescription('Search public Collector profiles').addStringOption((option) => option.setName('query').setDescription('Name, headline, or specialism').setRequired(true).setMaxLength(80))).addSubcommand((sub) => sub.setName('view').setDescription('View a public Collector profile').addStringOption((option) => option.setName('collector').setDescription('Public Collector slug').setRequired(true).setMaxLength(120)));
export const vaultCommand = new SlashCommandBuilder().setName('vault').setDescription('Read public custody updates').addSubcommand((sub) => sub.setName('latest').setDescription('View current public custody events')).addSubcommand((sub) => sub.setName('summary').setDescription('View current public custody availability'));
export const portfolioCommand = new SlashCommandBuilder().setName('portfolio').setDescription(copy.descriptions.portfolio);
export const balanceCommand = new SlashCommandBuilder().setName('balance').setDescription(copy.descriptions.balance);
export const transactionsCommand = new SlashCommandBuilder().setName('transactions').setDescription(copy.descriptions.transactions);
export const watchlistCommand = new SlashCommandBuilder().setName('watchlist').setDescription(copy.descriptions.watchlist);
export const profileCommand = new SlashCommandBuilder().setName('profile').setDescription(copy.descriptions.profile).addSubcommand((sub) => sub.setName('view').setDescription('View your private Slice summary or a community profile').addUserOption((option) => option.setName('member').setDescription(copy.options.profile_member))).addSubcommand((sub) => sub.setName('privacy').setDescription('Set profile visibility').addStringOption((option) => option.setName('visibility').setDescription('Visibility').setRequired(true).addChoices({ name: 'Public', value: 'PUBLIC' }, { name: 'Members only', value: 'MEMBERS_ONLY' }, { name: 'Private', value: 'PRIVATE' })));

export async function handleMarketCommand(interaction: ChatInputCommandInteraction, backend: SliceBackendClient, website: SliceWebsiteHandoffClient, progression: MemberProgressionService, profiles: PrismaInvestorProfileRepository, paginator: DiscordPaginator): Promise<void> {
  if (!interaction.guildId) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.configured('market.yml', 'guild_only')] });
  if (interaction.commandName === 'profile') return void await profile(interaction, backend, progression, profiles);
  if (['portfolio', 'balance', 'transactions', 'watchlist'].includes(interaction.commandName)) return void await privateCommand(interaction, website);
  if (interaction.commandName === 'asset') return void await asset(interaction, backend, paginator);
  if (interaction.commandName === 'market') return void await movers(interaction, backend, paginator, (interaction.options.getString('kind') ?? 'gainers') as 'gainers' | 'losers' | 'active');
  if (interaction.commandName === 'collector') return void await collector(interaction, backend, paginator);
  if (interaction.commandName === 'vault') return void await vault(interaction, backend, paginator);
  const legacyAsset = interaction.options.getString('asset');
  if (interaction.commandName === 'search') { const result = await backend.searchAssets(interaction.options.getString('query', true)); return void await marketResult(interaction, result, (items) => MarketFeedRenderer.list('Slice asset search', items)); }
  if (interaction.commandName === 'top') return void await movers(interaction, backend, paginator, interaction.options.getString('category', true) as 'gainers' | 'losers' | 'active');
  if (!legacyAsset) return;
  if (interaction.commandName === 'history') { const result = await backend.history(legacyAsset); return void await marketResult(interaction, result, (value) => MarketFeedRenderer.history(value.assetSlug, value.points)); }
  const result = await backend.asset(legacyAsset); return void await marketResult(interaction, result, (value) => MarketFeedRenderer.asset(value));
}

async function asset(interaction: ChatInputCommandInteraction, backend: SliceBackendClient, paginator: DiscordPaginator): Promise<void> {
  if (interaction.options.getSubcommand() === 'view') { const result = await backend.asset(interaction.options.getString('asset', true)); return void await marketResult(interaction, result, assetDetail); }
  const result = await backend.searchAssetPage({ query: interaction.options.getString('query') ?? undefined, category: interaction.options.getString('category') ?? undefined, set: interaction.options.getString('set') ?? undefined, gradingCompany: interaction.options.getString('grading-company') ?? undefined, gradeMin: interaction.options.getNumber('grade-min') ?? undefined, gradeMax: interaction.options.getNumber('grade-max') ?? undefined, limit: 48 });
  if (!result.ok) return void await marketFailure(interaction, result);
  await publicPages(interaction, paginator, assetPages('Slice asset search', result.value.items));
}
async function movers(interaction: ChatInputCommandInteraction, backend: SliceBackendClient, paginator: DiscordPaginator, requested: 'gainers' | 'losers' | 'active'): Promise<void> { const result = await backend.movers(requested); if (!result.ok) return void await marketFailure(interaction, result); await publicPages(interaction, paginator, assetPages(`Market movers · ${requested}`, result.value)); }
async function collector(interaction: ChatInputCommandInteraction, backend: SliceBackendClient, paginator: DiscordPaginator): Promise<void> { if (interaction.options.getSubcommand() === 'view') { const result = await backend.collector(interaction.options.getString('collector', true)); return void await marketResult(interaction, result, collectorDetail); } const query = interaction.options.getString('query', true).toLowerCase(); const result = await backend.collectorDirectory(); if (!result.ok) return void await marketFailure(interaction, result); const matches = result.value.items.filter((item) => [item.slug, item.displayName, item.headline, item.specialism].filter((value): value is string => Boolean(value)).join(' ').toLowerCase().includes(query)); await publicPages(interaction, paginator, collectorPages(matches)); }
async function vault(interaction: ChatInputCommandInteraction, backend: SliceBackendClient, paginator: DiscordPaginator): Promise<void> { if (interaction.options.getSubcommand() === 'summary') { const result = await backend.vaultSummary(); return void await marketResult(interaction, result, (value) => SliceEmbed.info('Public custody summary', `Authority: **${value.authority}**\nPublished public events: **${value.eventCount}**\n\nThis is a read-only public custody projection, not a private intake or ownership record.`)); } const result = await backend.vaultEvents(); if (!result.ok) return void await marketFailure(interaction, result); const pages = chunk(result.value.items, 6).map((items, index) => SliceEmbed.info('Public custody updates', items.length ? items.map((item) => `**${item.type.replace(/_/g, ' ')}** · ${item.assetSlug}\n${item.publicSummary}\n<t:${Math.floor(new Date(item.occurredAt).getTime() / 1000)}:R>`).join('\n\n') : 'No public custody events are available.').setFooter({ text: `Slice public custody · ${index + 1}` })); await publicPages(interaction, paginator, pages); }
async function marketResult<T>(interaction: ChatInputCommandInteraction, result: BackendResult<T>, render: (value: T) => ReturnType<typeof SliceEmbed.info>): Promise<void> { await interaction.reply({ ephemeral: false, embeds: [result.ok ? render(result.value) : SliceEmbed.configured('market.yml', 'data_unavailable', { reason: result.message })] }); }
async function marketFailure(interaction: ChatInputCommandInteraction, result: Exclude<BackendResult<unknown>, { ok: true }>): Promise<void> { await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.configured('market.yml', 'data_unavailable', { reason: result.message })] }); }
async function publicPages(interaction: ChatInputCommandInteraction, paginator: DiscordPaginator, pages: ReturnType<typeof SliceEmbed.info>[]): Promise<void> { await interaction.reply({ ephemeral: false, ...paginator.create(interaction.user.id, pages.length ? pages : [SliceEmbed.info('No public results', 'No authoritative public results are available.')]) }); }
async function privateCommand(interaction: ChatInputCommandInteraction, website: SliceWebsiteHandoffClient): Promise<void> { const destination = interaction.commandName === 'portfolio' ? 'portfolio' : interaction.commandName === 'transactions' ? 'transactions' : interaction.commandName === 'watchlist' ? 'marketplace' : 'account'; const handoff = website.handoff(destination); if (!handoff.available) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.configured('market.yml', 'private_unavailable', { reason: handoff.message })] }); await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.configured('market.yml', 'private_available')], components: [{ type: 1, components: [{ type: 2, style: 5, label: 'Open Slice', url: handoff.url }] }] }); }
async function profile(interaction: ChatInputCommandInteraction, backend: SliceBackendClient, progression: MemberProgressionService, profiles: PrismaInvestorProfileRepository): Promise<void> { const subcommand = interaction.options.getSubcommand(); if (subcommand === 'privacy') { const value = interaction.options.getString('visibility', true) as ProfileVisibility; await profiles.setVisibility(interaction.guildId!, interaction.user.id, value); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.configured('market.yml', 'profile_updated', { status: value.replace(/_/g, ' ') })] }); } const target = interaction.options.getUser('member'); if (!target || target.id === interaction.user.id) { const result = await backend.getMySliceSummary(interaction.user.id); if (!result.ok || !result.value.linked) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.warning('Connect your Slice account', 'Connect your account to view your private Slice profile summary.')] }); const value = result.value; return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.info('Your Slice profile', `Account: **${value.identity.displayName ?? value.identity.username ?? 'Slice member'}**\nCollector status: **${value.identity.capabilities.collector ? 'Enabled' : 'Not enabled'}**\nInvestor access: **${value.identity.capabilities.investor ? 'Enabled' : 'Not enabled'}**\n\nThis summary is visible only to you.`)] }); } const visibility = await profiles.visibility(interaction.guildId!, target.id); if (visibility === 'PRIVATE') return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.configured('market.yml', 'profile_private')] }); const data = await progression.get(interaction.guildId!, target.id); const achievements = await progression.achievementsFor(interaction.guildId!, target.id); await interaction.reply({ embeds: [SliceEmbed.configured('market.yml', 'profile', { username: target.username, level: data.level, xp: data.xp, reputation: data.reputation, count: `${achievements.length}/${ACHIEVEMENTS.length}`, status: visibility.replace(/_/g, ' '), reason: '' })] }); }
function amount(minor: string, currency: string) { return `${currency} ${(Number(minor) / 100).toFixed(2)}`; }
function assetDetail(asset: MarketAsset) { const valuation = asset.sliceValuation?.amount ?? asset.estimatedMarketValue; const marketType = asset.initialOffering ? 'Initial Offering' : asset.trading?.enabled ? 'Secondary Market' : 'Public asset'; const lines = [`**${marketType}**`, asset.year ? `Year: **${asset.year}**` : null, asset.collectibleSet?.name ? `Set: **${asset.collectibleSet.name}**` : null, asset.cardNumber ? `Card: **${asset.cardNumber}**` : null, asset.grading ? `Grade: **${asset.grading.companyCode} ${asset.grading.label}**` : asset.conditionLabel ? `Condition: **${asset.conditionLabel}**` : null, `Slice valuation: **${valuation ? amount(valuation.minor, valuation.currency) : 'Unavailable'}**`, asset.marketReference?.amount ? `External reference${asset.marketReference.provider ? ` · ${asset.marketReference.provider}` : ''}: **${amount(asset.marketReference.amount.minor, asset.marketReference.amount.currency)}**` : null, asset.initialOffering ? `Price per Slice: **${amount(asset.initialOffering.pricePerUnitMinor, asset.initialOffering.currency)}**\nAvailable ownership: **${asset.initialOffering.inventory?.availableUnits ?? 'Unavailable'} / ${asset.initialOffering.offeredUnits}**` : null, asset.trading ? `Market status: **${asset.trading.status}**` : null, `Data status: **${asset.dataStatus ?? 'UNAVAILABLE'}**`].filter((line): line is string => Boolean(line)); return SliceEmbed.info(asset.title, lines.join('\n')); }
function assetPages(title: string, assets: MarketAsset[]) { return chunk(assets, 6).map((items, index) => SliceEmbed.info(title, items.map((asset, offset) => `**${index * 6 + offset + 1}. ${asset.title}**\n${asset.year ? `${asset.year} · ` : ''}${asset.collectibleSet?.name ?? asset.category?.name ?? 'Collectible'}${asset.grading ? ` · ${asset.grading.companyCode} ${asset.grading.label}` : ''}\nSlice valuation: **${asset.sliceValuation?.amount ? amount(asset.sliceValuation.amount.minor, asset.sliceValuation.amount.currency) : asset.estimatedMarketValue ? amount(asset.estimatedMarketValue.minor, asset.estimatedMarketValue.currency) : 'Unavailable'}** · ${asset.dataStatus ?? 'UNAVAILABLE'}\n\`${asset.slug}\``).join('\n\n'))); }
function collectorDetail(item: PublicCollector) { return SliceEmbed.info(item.displayName ?? item.slug, [`Public Collector profile`, item.headline, item.specialism ? `Specialism: **${item.specialism}**` : null, `Published collectibles: **${item.publishedListingCount}**`, item.publishedListings.length ? `Recent public listings:\n${item.publishedListings.map((listing) => `• **${listing.title}** · ${listing.category}`).join('\n')}` : null].filter((line): line is string => Boolean(line)).join('\n\n')); }
function collectorPages(items: PublicCollector[]) { return chunk(items, 6).map((page) => SliceEmbed.info('Public Collector search', page.map((item) => `**${item.displayName ?? item.slug}**\n${item.specialism ?? item.headline ?? 'Public Slice Collector'}\nPublished collectibles: **${item.publishedListingCount}** · \`${item.slug}\``).join('\n\n'))); }
function chunk<T>(items: T[], size: number): T[][] { return Array.from({ length: Math.ceil(items.length / size) }, (_, index) => items.slice(index * size, index * size + size)); }
