import { ChatInputCommandInteraction, SlashCommandBuilder } from 'discord.js';
import { parseModerationDuration } from '../discord-moderation.js';
import type { ManualModerationService, ModerationActor, ModerationTarget } from '../moderation.js';
import { SliceEmbed } from '../embeds/slice-embed.js';
export const warnCommand = new SlashCommandBuilder().setName('warn').setDescription('Create a moderation warning').addUserOption((option) => option.setName('target').setDescription('Member').setRequired(true)).addStringOption((option) => option.setName('reason').setDescription('Reason').setRequired(true).setMaxLength(500));
export const noteCommand = new SlashCommandBuilder().setName('note').setDescription('Add a staff moderation note').addUserOption((option) => option.setName('target').setDescription('Member').setRequired(true)).addStringOption((option) => option.setName('reason').setDescription('Reason').setRequired(true).setMaxLength(500));
export const timeoutCommand = new SlashCommandBuilder().setName('timeout').setDescription('Timeout a member').addUserOption((option) => option.setName('target').setDescription('Member').setRequired(true)).addStringOption((option) => option.setName('duration').setDescription('Duration: 30m, 2h, or 1d (max 28d)').setRequired(true).setMaxLength(8)).addStringOption((option) => option.setName('reason').setDescription('Reason').setRequired(true).setMaxLength(500));
export const untimeoutCommand = new SlashCommandBuilder().setName('untimeout').setDescription('Remove a member timeout').addUserOption((option) => option.setName('target').setDescription('Member').setRequired(true)).addStringOption((option) => option.setName('reason').setDescription('Reason').setRequired(true).setMaxLength(500));
export const banCommand = new SlashCommandBuilder().setName('ban').setDescription('Ban a member').addUserOption((option) => option.setName('target').setDescription('Member').setRequired(true)).addStringOption((option) => option.setName('reason').setDescription('Reason').setRequired(true).setMaxLength(500));
export const unbanCommand = new SlashCommandBuilder().setName('unban').setDescription('Unban a Discord user').addUserOption((option) => option.setName('target').setDescription('User').setRequired(true)).addStringOption((option) => option.setName('reason').setDescription('Reason').setRequired(true).setMaxLength(500));
export const modcaseCommand = new SlashCommandBuilder().setName('modcase').setDescription('View a moderation case').addIntegerOption((option) => option.setName('number').setDescription('Case number').setRequired(true).setMinValue(1));
export const modhistoryCommand = new SlashCommandBuilder().setName('modhistory').setDescription('View recent moderation history').addUserOption((option) => option.setName('target').setDescription('Member').setRequired(true));
export async function handleModerationCommand(interaction: ChatInputCommandInteraction, service: ManualModerationService, actor: ModerationActor, target: (id: string, action: string) => Promise<ModerationTarget>): Promise<void> { if (!interaction.guildId) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Guild only', 'Moderation commands are available only in a server.')] }); try { const action = interaction.commandName; if (['warn', 'note', 'timeout', 'untimeout', 'ban', 'unban'].includes(action)) { const member = await target(interaction.options.getUser('target', true).id, action); const reason = interaction.options.getString('reason', true); const result = action === 'warn' ? await service.warn(interaction.guildId, actor, member, reason) : action === 'note' ? await service.note(interaction.guildId, actor, member, reason) : action === 'timeout' ? await service.timeout(interaction.guildId, actor, member, reason, parseModerationDuration(interaction.options.getString('duration', true))) : action === 'untimeout' ? await service.untimeout(interaction.guildId, actor, member, reason) : action === 'ban' ? await service.ban(interaction.guildId, actor, member, reason) : await service.unban(interaction.guildId, actor, member, reason); const label = result.status === 'ENFORCED' ? `${action.replace(/^./, (letter) => letter.toUpperCase())} enforced` : `${action.replace(/^./, (letter) => letter.toUpperCase())} failed`; return void await interaction.reply({ ephemeral: true, embeds: [result.status === 'ENFORCED' ? SliceEmbed.success(`Case #${result.caseNumber} · ${label}`, `Action applied to <@${member.id}>.`) : SliceEmbed.error(`Case #${result.caseNumber} · ${label}`, 'Discord enforcement failed; the case is recorded as failed.')] }); } if (action === 'modcase') { const result = await service.getCase(interaction.guildId, interaction.options.getInteger('number', true)); return void await interaction.reply({ ephemeral: true, embeds: [result ? SliceEmbed.info(`Case #${result.caseNumber}`, `Action: **${result.action}**\nStatus: **${result.status}**\nReason: ${result.reason}`) : SliceEmbed.error('Case unavailable', 'That moderation case is unavailable.')] }); } const rows = await service.getHistory(interaction.guildId, interaction.options.getUser('target', true).id); await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.info('Moderation history', rows.length ? rows.map((row) => `#${row.caseNumber} **${row.action}** — ${row.status} — ${row.reason}`).join('\n') : 'No recent moderation history.')] }); } catch { await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Moderation unavailable', 'You do not have permission to perform this moderation action, or Discord could not enforce it.')] }); } }
