import { ChatInputCommandInteraction, SlashCommandBuilder } from 'discord.js';
import { SliceEmbed } from '../embeds/slice-embed.js';
import { PrismaDiscordDeliveryRepository } from '../persistence/discord-delivery-repository.js';
import { authoritativePrice } from '../price-alert-worker.js';
import { money } from '../market-digest.js';
import { SliceBackendClient } from '../slice-backend-client.js';

export const priceAlertCommand = new SlashCommandBuilder().setName('pricealert').setDescription('Manage Discord price-alert preferences').addSubcommand((sub) => sub.setName('add').setDescription('Add a price alert').addStringOption((o) => o.setName('asset').setDescription('Authoritative Slice asset slug').setRequired(true).setMaxLength(120)).addStringOption((o) => o.setName('condition').setDescription('Alert condition').setRequired(true).addChoices({ name: 'Price above', value: 'PRICE_ABOVE' }, { name: 'Price below', value: 'PRICE_BELOW' })).addIntegerOption((o) => o.setName('minor').setDescription('Threshold in the asset currency minor units').setRequired(true).setMinValue(1))).addSubcommand((sub) => sub.setName('list').setDescription('List your alerts')).addSubcommand((sub) => sub.setName('remove').setDescription('Disable an alert').addStringOption((o) => o.setName('id').setDescription('Alert ID').setRequired(true)));
export async function handlePriceAlert(interaction: ChatInputCommandInteraction, repository: PrismaDiscordDeliveryRepository, backend: SliceBackendClient): Promise<void> { if (!interaction.guildId) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Guild only', 'Price alerts are Discord community preferences.')] }); const sub = interaction.options.getSubcommand(); if (sub === 'list') { const rows = await repository.listAlerts(interaction.guildId, interaction.user.id); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.info('Your price alerts', rows.length ? rows.map((row) => `${row.id.slice(0, 8)} · **${row.condition.replace(/_/g, ' ')}** [${row.assetId}] at **${row.currency ? money(row.thresholdMinor, row.currency) : `${row.thresholdMinor.toString()} minor units`}**`).join('\n') : 'No enabled alerts.')] }); } if (sub === 'remove') { const removed = await repository.removeAlert(interaction.guildId, interaction.user.id, interaction.options.getString('id', true)); return void await interaction.reply({ ephemeral: true, embeds: [removed ? SliceEmbed.success('Price alert disabled', 'This private alert will not trigger again.') : SliceEmbed.error('Alert unavailable', 'That alert is unavailable.')] }); }
  const assetId = interaction.options.getString('asset', true); const condition = interaction.options.getString('condition', true) as 'PRICE_ABOVE' | 'PRICE_BELOW'; const thresholdMinor = BigInt(interaction.options.getInteger('minor', true)); const result = await backend.asset(assetId); if (!result.ok) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Price alert unavailable', 'That Slice asset is unavailable for an authoritative alert.')] }); const current = authoritativePrice(result.value); if (!current || current.dataStatus !== 'LIVE') return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.warning('Price alert unavailable', 'Price alerts require current LIVE Slice market data.')] }); const conditionMet = condition === 'PRICE_ABOVE' ? current.minor >= thresholdMinor : current.minor <= thresholdMinor; await repository.createAlert({ guildId: interaction.guildId, discordUserId: interaction.user.id, assetId, condition, thresholdMinor, currency: current.currency, lastEvaluatedMinor: current.minor, lastConditionMet: conditionMet, lastObservedAt: current.asOf, lastSource: current.source, lastDataStatus: current.dataStatus }); await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.success('Price alert saved', `${result.value.title} will notify you privately on a future LIVE crossing of **${money(thresholdMinor, current.currency)}**. Current data was used as the baseline and will not trigger immediately.`)] }); }
