import { ChatInputCommandInteraction, SlashCommandBuilder } from 'discord.js';
import { SliceEmbed } from '../embeds/slice-embed.js';
import { presentationConfig } from '../presentation-config.js';
import { ACHIEVEMENTS, levelForXp, MemberProgressionService, xpForLevel } from '../progression.js';
const copy = presentationConfig()['commands.yml'];
export const levelCommand = new SlashCommandBuilder().setName('level').setDescription(copy.descriptions.level).addUserOption((option) => option.setName('member').setDescription(copy.options.progression_member));
export const leaderboardCommand = new SlashCommandBuilder().setName('leaderboard').setDescription(copy.descriptions.leaderboard).addStringOption((option) => option.setName('metric').setDescription(copy.options.leaderboard_metric).addChoices({ name: 'XP', value: 'xp' }, { name: 'Reputation', value: 'reputation' }));
export const repCommand = new SlashCommandBuilder().setName('rep').setDescription(copy.descriptions.rep).addUserOption((option) => option.setName('member').setDescription(copy.options.reputation_member).setRequired(true)).addStringOption((option) => option.setName('reason').setDescription(copy.options.reputation_reason).setMaxLength(160));
export const reputationCommand = new SlashCommandBuilder().setName('reputation').setDescription(copy.descriptions.reputation).addUserOption((option) => option.setName('member').setDescription(copy.options.progression_member));
export const achievementsCommand = new SlashCommandBuilder().setName('achievements').setDescription(copy.descriptions.achievements).addUserOption((option) => option.setName('member').setDescription(copy.options.progression_member));
export const dailyCommand = new SlashCommandBuilder().setName('daily').setDescription(copy.descriptions.daily);
export async function handleProgressionCommand(interaction: ChatInputCommandInteraction, service: MemberProgressionService): Promise<void> {
  if (!interaction.guildId) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.configured('progression.yml', 'guild_only')] }); const target = interaction.options.getUser('member') ?? interaction.user;
  if (interaction.commandName === 'rep') { const recipient = interaction.options.getUser('member', true); if (recipient.bot || recipient.id === interaction.user.id) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.configured('progression.yml', 'reputation_invalid')] }); const result = await service.giveReputation({ guildId: interaction.guildId, giverDiscordUserId: interaction.user.id, receiverDiscordUserId: recipient.id, reason: interaction.options.getString('reason') ?? undefined }); return void await interaction.reply({ ephemeral: true, embeds: [result ? SliceEmbed.configured('progression.yml', 'reputation_sent', { user: recipient.id, reputation: result.progression.reputation }) : SliceEmbed.configured('progression.yml', 'reputation_unavailable')] }); }
  if (interaction.commandName === 'daily') { const result = await service.claimDaily(interaction.guildId, interaction.user.id); return void await interaction.reply({ ephemeral: true, embeds: [result ? SliceEmbed.configured('progression.yml', 'daily_claimed', { amount: result.amount, streak: result.progression.currentStreak }) : SliceEmbed.configured('progression.yml', 'daily_unavailable')] }); }
  if (interaction.commandName === 'leaderboard') { const metric = (interaction.options.getString('metric') ?? 'xp') as 'xp' | 'reputation'; const rows = await service.leaderboard(interaction.guildId, metric); const body = rows.length ? rows.map((row, index) => `**${index + 1}.** <@${row.discordUserId}> — **${metric === 'xp' ? `${row.xp} XP · Level ${row.level}` : `${row.reputation} reputation`}**`).join('\n') : 'No public community progression yet.'; return void await interaction.reply({ embeds: [SliceEmbed.configured('progression.yml', 'leaderboard', { reason: metric === 'xp' ? 'XP' : 'Reputation', status: body })] }); }
  if (interaction.commandName === 'achievements') { const unlocked = await service.achievementsFor(interaction.guildId, target.id); const definitions = new Map(ACHIEVEMENTS.map((definition) => [definition.key, definition])); const body = unlocked.length ? unlocked.slice(0, 20).map((entry) => { const definition = definitions.get(entry.key); return `${definition?.icon ?? '✦'} **${definition?.name ?? entry.key}** — ${definition?.description ?? 'Community achievement'}`; }).join('\n') : 'No achievements unlocked yet. Participate in the community to begin.'; return void await interaction.reply({ embeds: [SliceEmbed.configured('progression.yml', 'achievements', { username: target.username, reason: body, count: `${unlocked.length}/${ACHIEVEMENTS.length}` })] }); }
  const progression = await service.get(interaction.guildId, target.id); const rank = await service.rank(interaction.guildId, target.id, interaction.commandName === 'reputation' ? 'reputation' : 'xp'); if (interaction.commandName === 'reputation') return void await interaction.reply({ embeds: [SliceEmbed.configured('progression.yml', 'reputation', { username: target.username, reputation: progression.reputation, rank })] }); const next = xpForLevel(levelForXp(progression.xp)); const previous = progression.level <= 1 ? 0 : xpForLevel(progression.level - 1); const unlocked = await service.achievementsFor(interaction.guildId, target.id); return void await interaction.reply({ embeds: [SliceEmbed.configured('progression.yml', 'level', { username: target.username, level: progression.level, xp: progression.xp, reason: `${progression.xp - previous}/${next - previous} XP to level ${progression.level + 1}`, reputation: progression.reputation, rank, count: `${unlocked.length}/${ACHIEVEMENTS.length}` })] });
}
