import { PermissionFlagsBits, SlashCommandBuilder } from 'discord.js';

const types = [['One time', 'ONE_TIME'], ['Daily', 'DAILY'], ['Weekly', 'WEEKLY'], ['Monthly', 'MONTHLY'], ['Custom weekdays', 'CUSTOM_WEEKDAYS']] as const;
const modes = [['Snapshot (default)', 'SNAPSHOT'], ['Live draft', 'LIVE_DRAFT']] as const;
export const scheduleCommand = new SlashCommandBuilder().setName('schedule').setDescription('Schedule a validated Slice embed').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
  .addSubcommand((s) => s.setName('create').setDescription('Schedule an embed draft').addStringOption((o) => o.setName('draft').setDescription('Embed draft ID').setRequired(true)).addStringOption((o) => o.setName('name').setDescription('Schedule name').setRequired(true).setMaxLength(100)).addStringOption((o) => o.setName('type').setDescription('Schedule type').setRequired(true).addChoices(...types.map(([name, value]) => ({ name, value })))).addStringOption((o) => o.setName('time').setDescription('24-hour local time: HH:mm').setRequired(true)).addStringOption((o) => o.setName('timezone').setDescription('IANA timezone, e.g. America/New_York').setRequired(true)).addStringOption((o) => o.setName('date').setDescription('One-time date: YYYY-MM-DD')).addStringOption((o) => o.setName('weekdays').setDescription('MON,WED,FRI (weekly accepts one)')).addIntegerOption((o) => o.setName('day').setDescription('Monthly day 1-31')).addStringOption((o) => o.setName('mode').setDescription('Content behavior').addChoices(...modes.map(([name, value]) => ({ name, value })))).addChannelOption((o) => o.setName('channel').setDescription('Target text channel')))
  .addSubcommand((s) => s.setName('list').setDescription('List guild schedules').addStringOption((o) => o.setName('status').setDescription('Lifecycle filter').addChoices(...['ACTIVE', 'PAUSED', 'FAILED', 'COMPLETED', 'CANCELLED', 'ALL'].map((value) => ({ name: value, value })))))
  .addSubcommand((s) => s.setName('view').setDescription('View a schedule').addStringOption((o) => o.setName('schedule').setDescription('Schedule ID').setRequired(true)))
  .addSubcommand((s) => s.setName('edit').setDescription('Edit a schedule').addStringOption((o) => o.setName('schedule').setDescription('Schedule ID').setRequired(true)).addStringOption((o) => o.setName('name').setDescription('New schedule name').setMaxLength(100)).addChannelOption((o) => o.setName('channel').setDescription('New target text channel')).addStringOption((o) => o.setName('type').setDescription('New schedule type').addChoices(...types.map(([name, value]) => ({ name, value })))).addStringOption((o) => o.setName('time').setDescription('New 24-hour local time HH:mm')).addStringOption((o) => o.setName('timezone').setDescription('New IANA timezone')).addStringOption((o) => o.setName('date').setDescription('New one-time date YYYY-MM-DD')).addStringOption((o) => o.setName('weekdays').setDescription('New weekday(s), e.g. MON,WED,FRI')).addIntegerOption((o) => o.setName('day').setDescription('New monthly day 1-31')).addStringOption((o) => o.setName('mode').setDescription('Content behavior').addChoices(...modes.map(([name, value]) => ({ name, value })))))
  .addSubcommand((s) => s.setName('pause').setDescription('Pause a schedule').addStringOption((o) => o.setName('schedule').setDescription('Schedule ID').setRequired(true)))
  .addSubcommand((s) => s.setName('resume').setDescription('Resume a schedule').addStringOption((o) => o.setName('schedule').setDescription('Schedule ID').setRequired(true)))
  .addSubcommand((s) => s.setName('cancel').setDescription('Cancel a schedule').addStringOption((o) => o.setName('schedule').setDescription('Schedule ID').setRequired(true)))
  .addSubcommand((s) => s.setName('history').setDescription('Inspect announcement run history').addStringOption((o) => o.setName('schedule').setDescription('Schedule ID').setRequired(true)))
  .addSubcommand((s) => s.setName('retry').setDescription('Retry a safe failed schedule').addStringOption((o) => o.setName('schedule').setDescription('Schedule ID').setRequired(true)))
  .addSubcommand((s) => s.setName('run-now').setDescription('Run one immediate announcement').addStringOption((o) => o.setName('schedule').setDescription('Schedule ID').setRequired(true)))
  .addSubcommand((s) => s.setName('timezone').setDescription('Set this guild scheduler timezone').addStringOption((o) => o.setName('timezone').setDescription('IANA timezone').setRequired(true)));
