import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ChatInputCommandInteraction, MessageFlags, PermissionFlagsBits, SlashCommandBuilder } from 'discord.js';
import { SetupProvisioner } from '../setup/provisioner.js';
import { SliceEmbed } from '../embeds/slice-embed.js';
import type { SetupRepository } from '../persistence/setup-repository.js';
const nonces = new Map<string, { guildId: string; actorId: string; expires: number }>();
export const setupCommand = new SlashCommandBuilder().setName('setup').setDescription('Configure Slice AI server resources').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addSubcommand((s) => s.setName('preview').setDescription('Preview safe setup changes')).addSubcommand((s) => s.setName('server').setDescription('Preview full Slice server setup')).addSubcommand((s) => s.setName('status').setDescription('Show configuration status')).addSubcommand((s) => s.setName('repair').setDescription('Preview a safe repair')).addSubcommand((s) => s.setName('artwork').setDescription('Generate Slice artwork'));
export async function handleSetup(interaction: ChatInputCommandInteraction, repository: SetupRepository, provisioner: SetupProvisioner): Promise<void> {
  if (!interaction.guild) { await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Guild only', 'Server setup can only run inside a Discord server.')] }); return; }
  if (!interaction.memberPermissions?.has(PermissionFlagsBits.Administrator)) { await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Administrator required', 'Only a Discord server administrator can configure Slice AI.')] }); return; }
  const sub = interaction.options.getSubcommand();
  if (sub === 'status') { await interaction.deferReply({ flags: MessageFlags.Ephemeral }); const status = await provisioner.status(interaction.guild); const p = status.plan; const state = p.ambiguous.length ? 'AMBIGUOUS' : p.updateAvailable ? 'UPDATE AVAILABLE' : p.missingRoles + p.missingCategories + p.missingChannels + p.missingPanels ? 'PARTIAL' : p.renamed + p.moved + p.permissionDrift + p.staleReferences ? 'DRIFTED' : status.configured ? 'READY' : 'MISSING'; await interaction.editReply({ embeds: [SliceEmbed.info('Slice Discord status', `Foundation: **READY**\nDatabase: **CONNECTED**\nRoles: **${p.missingRoles ? 'MISSING' : 'READY'}**\nChannels: **${p.missingCategories + p.missingChannels ? 'PARTIAL' : 'READY'}**\nPermissions: **${p.permissionDrift ? 'DRIFTED' : 'READY'}**\nPanels: **${p.missingPanels ? 'MISSING' : 'READY'}**\nArtwork: **READY**\nSetup version: **${status.version}**\nOverall: **${state}**${p.ambiguous.length ? `\nAmbiguous: ${p.ambiguous.join(', ')}` : ''}`)] }); return; }
  if (sub === 'artwork') { await interaction.deferReply({ flags: MessageFlags.Ephemeral }); await provisioner.generateArtwork(); await interaction.editReply({ embeds: [SliceEmbed.success('Artwork generated', 'Branded PNG banners have been rendered locally. Server icon/banner application remains a manual admin step.')] }); return; }
  await interaction.deferReply({ flags: MessageFlags.Ephemeral }); void repository; const nonce = crypto.randomUUID(); nonces.set(nonce, { guildId: interaction.guild.id, actorId: interaction.user.id, expires: Date.now() + 10 * 60_000 }); const preview = await provisioner.inspect(interaction.guild);
  const repair = sub === 'repair'; await interaction.editReply({ embeds: [SliceEmbed.info(repair ? 'Slice repair preview' : 'Slice server setup preview', `Missing roles: **${preview.missingRoles}**\nMissing categories: **${preview.missingCategories}**\nMissing channels: **${preview.missingChannels}**\nPanels missing: **${preview.missingPanels}**\nStale references: **${preview.staleReferences}**\nRenamed/moved: **${preview.renamed + preview.moved}**\nPermission drift: **${preview.permissionDrift}**\nAmbiguous: **${preview.ambiguous.length}**\n\nNo unrelated Discord resources will be deleted.`)], components: [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`slice:setup:apply:${nonce}`).setLabel(repair ? 'Apply repair' : 'Apply setup').setStyle(ButtonStyle.Success).setDisabled(preview.ambiguous.length > 0), new ButtonBuilder().setCustomId(`slice:setup:cancel:${nonce}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary))] });
}
export async function handleSetupButton(customId: string, userId: string, guildId: string, apply: () => Promise<{ created: number; updated: number }>): Promise<{ title: string; body: string }> {
  const [, , action, nonce] = customId.split(':'); const request = nonces.get(nonce); if (!request || request.expires < Date.now()) return { title: 'Setup expired', body: 'Run `/setup preview` again.' }; if (request.actorId !== userId || request.guildId !== guildId) return { title: 'Not authorized', body: 'Only the administrator who opened this preview can apply it.' }; nonces.delete(nonce); if (action === 'cancel') return { title: 'Setup cancelled', body: 'No server changes were made.' }; const result = await apply(); return { title: 'Slice setup complete', body: `Created **${result.created}** resources and repaired **${result.updated}** managed resources.` };
}
