import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ButtonInteraction, ChatInputCommandInteraction, MessageFlags, PermissionFlagsBits, SlashCommandBuilder } from 'discord.js';
import { SetupProvisioner, type ReconciliationPlan } from '../setup/provisioner.js';
import { SliceEmbed } from '../embeds/slice-embed.js';
import type { SetupRepository } from '../persistence/setup-repository.js';
const nonces = new Map<string, { guildId: string; actorId: string; expires: number }>();
export const setupCommand = new SlashCommandBuilder().setName('setup').setDescription('Configure Slice AI server resources').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addSubcommand((s) => s.setName('preview').setDescription('Preview safe setup changes')).addSubcommand((s) => s.setName('server').setDescription('Preview full Slice server setup')).addSubcommand((s) => s.setName('status').setDescription('Show detailed configuration status')).addSubcommand((s) => s.setName('refresh').setDescription('Refresh detailed configuration status')).addSubcommand((s) => s.setName('repair').setDescription('Preview a safe repair')).addSubcommand((s) => s.setName('artwork').setDescription('Generate Slice artwork')).addSubcommand((s) => s.setName('reset').setDescription('Preview removal of Slice-managed Discord setup'));
export function setupStatusPayload(status: { plan: ReconciliationPlan; version: number; configured: boolean }, refreshed = false) {
  const p = status.plan;
  const state = p.ambiguous.length ? 'AMBIGUOUS' : (p.hierarchyDrift ?? 0) ? 'HIERARCHY BLOCKED' : p.updateAvailable ? 'UPDATE AVAILABLE' : p.missingRoles + p.missingCategories + p.missingChannels + p.missingPanels ? 'PARTIAL' : p.renamed + p.moved + p.permissionDrift + p.roleDrift + p.separatorDrift + p.staleReferences ? 'DRIFTED' : status.configured ? 'READY' : 'MISSING';
  const value = (label: string, missing: number) => missing ? `${label}: **${missing} missing**` : `${label}: **Ready**`;
  const embed = SliceEmbed.staff('Setup status', refreshed ? '✓ Status refreshed just now. Select Review updates to see a safe, itemized repair preview.' : 'Current managed-resource reconciliation. Select Review updates to see a safe, itemized repair preview.').addFields(
    { name: 'SERVER STRUCTURE', value: [value('Roles', p.missingRoles), value('Categories', p.missingCategories), value('Channels', p.missingChannels)].join('\n'), inline: false },
    { name: 'PERSISTENCE', value: [value('Panels', p.missingPanels), `Setup version: **${status.version}**`, `Configuration: **${status.configured ? 'Stored' : 'Not stored'}**`].join('\n'), inline: false },
    { name: 'ROLE AUDIT', value: [`Role presentation/permission drift: **${p.roleDrift}**`, `Assigned separator roles: **${p.separatorDrift}**`, `Bot hierarchy blockers: **${p.hierarchyDrift ?? 0}**`].join('\n'), inline: false },
    { name: 'DRIFT', value: [`Renamed: **${p.renamed}** · Moved: **${p.moved}**`, `Channel permission drift: **${p.permissionDrift}** · Stale references: **${p.staleReferences}**`, `Ambiguous: **${p.ambiguous.length}**`].join('\n'), inline: false },
    { name: 'OVERALL', value: `**${state}**${p.ambiguous.length ? `\n${p.ambiguous.join(', ')}` : ''}`, inline: false },
  );
  return { embeds: [embed], components: [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('slice:setup:refresh').setLabel('Review updates').setStyle(ButtonStyle.Secondary))] };
}
export function setupUpdatePreviewPayload(preview: ReconciliationPlan, guildId: string, actorId: string) {
  const nonce = createNonce(guildId, actorId);
  return {
    embeds: [SliceEmbed.info('Slice setup update preview', `No Discord changes have been made.\n\n**Roles**\nMissing: **${preview.missingRoles}** · Presentation/permission drift: **${preview.roleDrift}** · Assigned separators: **${preview.separatorDrift}** · Bot hierarchy blockers: **${preview.hierarchyDrift ?? 0}**\n\n**Categories and channels**\nMissing categories: **${preview.missingCategories}** · Missing channels: **${preview.missingChannels}** · Renamed/moved: **${preview.renamed + preview.moved}** · Permission drift: **${preview.permissionDrift}**\n\n**Panels and configuration**\nPanels missing: **${preview.missingPanels}** · Stale references: **${preview.staleReferences}** · Manifest update available: **${preview.updateAvailable ? 'Yes' : 'No'}**\n\nAmbiguous resources: **${preview.ambiguous.length}**${(preview.hierarchyDrift ?? 0) ? '\n\nMove the SliceAI application role above all Slice-managed roles in Discord Server Settings before applying this update.' : ''}\n\nApplying updates only reconciles Slice-managed resources. Unmanaged Discord resources and history are not deleted.`)],
    components: [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`slice:setup:apply:${nonce}`).setLabel('Apply update').setStyle(ButtonStyle.Success).setDisabled(preview.ambiguous.length > 0 || (preview.hierarchyDrift ?? 0) > 0), new ButtonBuilder().setCustomId(`slice:setup:cancel:${nonce}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary))],
  };
}
export async function handleSetupRefresh(interaction: ButtonInteraction, provisioner: SetupProvisioner): Promise<void> {
  if (!interaction.guild || !interaction.guildId) return;
  await interaction.deferReply({ flags: MessageFlags.Ephemeral });
  await interaction.editReply(setupUpdatePreviewPayload(await provisioner.inspect(interaction.guild), interaction.guildId, interaction.user.id));
}
export async function handleSetup(interaction: ChatInputCommandInteraction, repository: SetupRepository, provisioner: SetupProvisioner): Promise<void> {
  if (!interaction.guild) { await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Guild only', 'Server setup can only run inside a Discord server.')] }); return; }
  if (!interaction.memberPermissions?.has(PermissionFlagsBits.Administrator)) { await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Administrator required', 'Only a Discord server administrator can configure Slice AI.')] }); return; }
  const sub = interaction.options.getSubcommand();
  if (sub === 'status' || sub === 'refresh') { await interaction.deferReply({ flags: MessageFlags.Ephemeral }); await interaction.editReply(setupStatusPayload(await provisioner.status(interaction.guild))); return; }
  if (sub === 'artwork') { await interaction.deferReply({ flags: MessageFlags.Ephemeral }); await provisioner.generateArtwork(); await interaction.editReply({ embeds: [SliceEmbed.success('Artwork generated', 'Branded PNG banners have been rendered locally. Server icon/banner application remains a manual admin step.')] }); return; }
  if (sub === 'reset') { await interaction.deferReply({ flags: MessageFlags.Ephemeral }); const nonce = createNonce(interaction.guild.id, interaction.user.id); const plan = await provisioner.inspectReset(interaction.guild); await interaction.editReply({ embeds: [SliceEmbed.warning('Slice setup reset preview', `This will remove **only** Slice-managed Discord resources and setup metadata for this server.\n\nManaged roles: **${plan.managedRoles}**\nManaged categories: **${plan.managedCategories}**\nManaged channels: **${plan.managedChannels}**\nPanel messages: **${plan.panels}**\nSlice support ticket channels: **${plan.ticketChannels}**\n\nIt will not touch Slice accounts, Discord account links, portfolios, ownership, orders, trades, balances, or financial records. This action is destructive and cannot be undone automatically.`)], components: [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`slice:setup:reset:${nonce}`).setLabel('Confirm reset').setStyle(ButtonStyle.Danger), new ButtonBuilder().setCustomId(`slice:setup:cancel:${nonce}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary))] }); return; }
  await interaction.deferReply({ flags: MessageFlags.Ephemeral }); void repository; const preview = await provisioner.inspect(interaction.guild);
  await interaction.editReply(setupUpdatePreviewPayload(preview, interaction.guild.id, interaction.user.id));
}
function createNonce(guildId: string, actorId: string): string { const nonce = crypto.randomUUID(); nonces.set(nonce, { guildId, actorId, expires: Date.now() + 10 * 60_000 }); return nonce; }
export async function handleSetupButton(customId: string, userId: string, guildId: string, callbacks: { apply: () => Promise<{ created: number; updated: number }>; reset: () => Promise<{ deletedRoles: number; deletedCategories: number; deletedChannels: number; deletedPanels: number; deletedTicketChannels: number }> }): Promise<{ title: string; body: string }> {
  const [, , action, nonce] = customId.split(':'); const request = nonces.get(nonce); if (!request || request.expires < Date.now()) return { title: 'Setup expired', body: 'Run `/setup preview` again.' }; if (request.actorId !== userId || request.guildId !== guildId) return { title: 'Not authorized', body: 'Only the administrator who opened this preview can apply it.' }; nonces.delete(nonce); if (action === 'cancel') return { title: 'Setup cancelled', body: 'No server changes were made.' }; if (action === 'reset') { const result = await callbacks.reset(); return { title: 'Slice setup reset complete', body: `Removed **${result.deletedRoles}** roles, **${result.deletedCategories}** categories, **${result.deletedChannels}** channels, **${result.deletedPanels}** panel messages, and **${result.deletedTicketChannels}** support ticket channels. Slice account and financial data were not changed.` }; } if (action !== 'apply') return { title: 'Setup action unavailable', body: 'Run `/setup preview` again.' }; const result = await callbacks.apply(); return { title: 'Slice setup complete', body: `Created **${result.created}** resources and repaired **${result.updated}** managed resources.` };
}
