import { ChannelType, SlashCommandBuilder } from 'discord.js';
export const spotlightCommand = new SlashCommandBuilder().setName('spotlight').setDescription('Create public, approved Slice spotlights')
  .addSubcommand((s) => s.setName('collector').setDescription('Request your public Collector Spotlight').addStringOption((o) => o.setName('collector').setDescription('Your public Collector slug').setRequired(true)).addStringOption((o) => o.setName('title').setDescription('Optional editorial title').setMaxLength(160)).addStringOption((o) => o.setName('copy').setDescription('Optional editorial copy').setMaxLength(1_500)))
  .addSubcommand((s) => s.setName('collectible').setDescription('Create a Featured Collectible request').addStringOption((o) => o.setName('asset').setDescription('Public asset slug').setRequired(true)).addStringOption((o) => o.setName('title').setDescription('Optional editorial title').setMaxLength(160)).addStringOption((o) => o.setName('copy').setDescription('Optional editorial copy').setMaxLength(1_500)))
  .addSubcommand((s) => s.setName('list').setDescription('List Spotlight requests'))
  .addSubcommand((s) => s.setName('view').setDescription('View a Spotlight request').addStringOption((o) => o.setName('id').setDescription('Spotlight ID').setRequired(true)))
  .addSubcommand((s) => s.setName('edit').setDescription('Edit Spotlight editorial fields').addStringOption((o) => o.setName('id').setDescription('Spotlight ID').setRequired(true)).addStringOption((o) => o.setName('title').setDescription('Editorial title').setMaxLength(160)).addStringOption((o) => o.setName('copy').setDescription('Editorial copy').setMaxLength(1_500)))
  .addSubcommand((s) => s.setName('approve').setDescription('Approve a requested Spotlight').addStringOption((o) => o.setName('id').setDescription('Spotlight ID').setRequired(true)))
  .addSubcommand((s) => s.setName('publish').setDescription('Refresh and publish an approved Spotlight').addStringOption((o) => o.setName('id').setDescription('Spotlight ID').setRequired(true)).addChannelOption((o) => o.setName('channel').setDescription('Public target channel').setRequired(true).addChannelTypes(ChannelType.GuildText)))
  .addSubcommand((s) => s.setName('schedule').setDescription('Prepare an approved Spotlight for /schedule').addStringOption((o) => o.setName('id').setDescription('Spotlight ID').setRequired(true)))
  .addSubcommand((s) => s.setName('cancel').setDescription('Cancel a Spotlight request').addStringOption((o) => o.setName('id').setDescription('Spotlight ID').setRequired(true)));
