import { describe, expect, it } from 'vitest';
import { evaluateAutomod, ModerationService, type ModerationCase, type ModerationRepository, type ModerationTransport } from '../../src/moderation.js';

class Cases implements ModerationRepository {
  rows: ModerationCase[] = [];
  async create(input: Omit<ModerationCase, 'caseNumber' | 'status'>): Promise<ModerationCase> { const row: ModerationCase = { ...input, caseNumber: this.rows.length + 1, status: 'PENDING' }; this.rows.push(row); return row; }
  async mark(id: Pick<ModerationCase, 'guildId' | 'caseNumber'>, status: ModerationCase['status']): Promise<void> { const row = this.rows.find((candidate) => candidate.guildId === id.guildId && candidate.caseNumber === id.caseNumber); if (row) row.status = status; }
}
function transport(overrides: Partial<ModerationTransport> = {}): ModerationTransport { return { enforce: async () => {}, log: async () => {}, ...overrides }; }

describe('moderation service', () => {
  it('persists one enforced sanitized manual warning and logs it', async () => { const cases = new Cases(); const logged: ModerationCase[] = []; const service = new ModerationService(cases, transport({ log: async (row) => { logged.push(row); } })); const result = await service.enforce({ guildId: 'g', targetDiscordUserId: 'target', moderatorDiscordUserId: 'mod', action: 'WARN', source: 'MANUAL', reason: 'password secret-value' }); expect(result).toMatchObject({ guildId: 'g', targetDiscordUserId: 'target', moderatorDiscordUserId: 'mod', action: 'WARN', source: 'MANUAL', status: 'ENFORCED' }); expect(cases.rows).toHaveLength(1); expect(cases.rows[0].reason).toContain('[redacted]'); expect(logged).toHaveLength(1); });
  it('records failed enforcement honestly and does not report it enforced', async () => { const cases = new Cases(); const result = await new ModerationService(cases, transport({ enforce: async () => { throw new Error('discord failed'); } })).enforce({ guildId: 'g', targetDiscordUserId: 'target', action: 'TIMEOUT', source: 'MANUAL', reason: 'Repeated spam' }); expect(result.status).toBe('FAILED'); expect(cases.rows[0].status).toBe('FAILED'); });
  it('keeps an enforced case authoritative when mod-log delivery fails', async () => { const cases = new Cases(); const result = await new ModerationService(cases, transport({ log: async () => { throw new Error('log unavailable'); } })).enforce({ guildId: 'g', targetDiscordUserId: 'target', action: 'BAN', source: 'MANUAL', reason: 'Serious violation' }); expect(result.status).toBe('ENFORCED'); expect(cases.rows[0].status).toBe('ENFORCED'); });
});
describe('automod and anti-scam evaluator', () => {
  it('allows normal traffic below flood, duplicate, and mention thresholds', () => { expect(evaluateAutomod({ content: 'Please check the support login guide.', mentions: 2, recent: 2, duplicates: 1, staff: false })).toEqual({ severity: 'LOW' }); });
  it('detects flood, duplicate spam, mentions, and invites as medium automod blocks', () => { expect(evaluateAutomod({ content: 'hello', mentions: 0, recent: 7, duplicates: 1, staff: false })).toMatchObject({ action: 'AUTOMOD_BLOCK', severity: 'MEDIUM', reason: 'Spam policy' }); expect(evaluateAutomod({ content: 'hello', mentions: 0, recent: 1, duplicates: 3, staff: false })).toMatchObject({ action: 'AUTOMOD_BLOCK' }); expect(evaluateAutomod({ content: 'hello', mentions: 9, recent: 1, duplicates: 1, staff: false })).toMatchObject({ action: 'AUTOMOD_BLOCK' }); expect(evaluateAutomod({ content: 'join discord.gg/example', mentions: 0, recent: 1, duplicates: 1, staff: false })).toMatchObject({ action: 'AUTOMOD_BLOCK', reason: 'Unapproved invite link' }); });
  it('exempts staff from the current invite rule but not high-confidence scam patterns', () => { expect(evaluateAutomod({ content: 'discord.gg/example', mentions: 0, recent: 1, duplicates: 1, staff: true })).toEqual({ severity: 'LOW' }); expect(evaluateAutomod({ content: 'Free Nitro: share your seed phrase', mentions: 0, recent: 1, duplicates: 1, staff: true })).toMatchObject({ action: 'SCAM_BLOCK', severity: 'CRITICAL' }); });
  it('classifies synthetic credential, seed, impersonation, and giveaway scams without retaining raw tokens', () => { for (const content of ['Verify login with your discord token', 'Send your seed phrase for wallet support', 'Official support: free nitro giveaway']) { const result = evaluateAutomod({ content, mentions: 0, recent: 1, duplicates: 1, staff: false }); expect(result).toMatchObject({ action: 'SCAM_BLOCK', severity: 'CRITICAL' }); } const token = 'abcdefghijklmnopqrst.abcdefghij.abcdefghij'; const result = evaluateAutomod({ content: `discord token ${token}`, mentions: 0, recent: 1, duplicates: 1, staff: false }); expect(result.excerpt).not.toContain(token); });
});
