import { describe, expect, it } from 'vitest';
import { banCommand, handleModerationCommand, modcaseCommand, modhistoryCommand, noteCommand, timeoutCommand, unbanCommand, untimeoutCommand, warnCommand } from '../../src/commands/moderation.js';
import type { ManualModerationService, ModerationActor, ModerationTarget } from '../../src/moderation.js';
const actor: ModerationActor={id:'actor',staff:true,admin:false,position:5}; const target: ModerationTarget={id:'target',position:1,protected:false,bot:false};
function interaction(commandName:string,guildId='guild'){const replies:unknown[]=[];return {commandName,guildId,guild:guildId?{}:null,user:{id:'actor'},options:{getUser:()=>({id:'target'}),getString:(key?:string)=> key==='duration'?'1h':'Reason text',getInteger:()=>7},reply:async(p:unknown)=>{replies.push(p)},replies};}
function service(){const calls:string[]=[];const value={caseNumber:7,guildId:'guild',targetDiscordUserId:'target',moderatorDiscordUserId:'actor',action:'WARN',source:'MANUAL',status:'ENFORCED',reason:'Reason text'};return {calls,api:{warn:async()=>{calls.push('warn');return value},note:async()=>{calls.push('note');return {...value,action:'NOTE'}},getCase:async()=>{calls.push('case');return value},getHistory:async()=>{calls.push('history');return [value]}} as unknown as ManualModerationService};}
describe('production moderation command routing',()=>{
  it('registers each moderation command exactly once',()=>{const names=[warnCommand,noteCommand,timeoutCommand,untimeoutCommand,banCommand,unbanCommand,modcaseCommand,modhistoryCommand].map(c=>c.name);expect(names).toEqual(['warn','note','timeout','untimeout','ban','unban','modcase','modhistory']);expect(new Set(names).size).toBe(8);});
  it('routes trusted guild actor target and reason to warn exactly once',async()=>{const i=interaction('warn');const s=service();await handleModerationCommand(i as never,s.api,actor,async()=>target);expect(s.calls).toEqual(['warn']);expect(i.replies).toHaveLength(1);});
  it('routes note without a Discord punishment boundary',async()=>{const i=interaction('note');const s=service();await handleModerationCommand(i as never,s.api,actor,async()=>target);expect(s.calls).toEqual(['note']);expect(i.replies).toHaveLength(1);});
  it('routes guild-scoped case and bounded target history lookups',async()=>{const caseInteraction=interaction('modcase');const historyInteraction=interaction('modhistory');const s=service();await handleModerationCommand(caseInteraction as never,s.api,actor,async()=>target);await handleModerationCommand(historyInteraction as never,s.api,actor,async()=>target);expect(s.calls).toEqual(['case','history']);});
  it('rejects guildless commands before service mutation and renders service failures safely',async()=>{const dm=interaction('warn','');const s=service();await handleModerationCommand(dm as never,s.api,actor,async()=>target);expect(s.calls).toEqual([]);const denied=interaction('warn');await handleModerationCommand(denied as never,{...s.api,warn:async()=>{throw new Error('FORBIDDEN')}} as ManualModerationService,actor,async()=>target);expect(denied.replies).toHaveLength(1);});
});
