import { describe, expect, it } from 'vitest';
import { FAQ, SliceWebsiteHandoffClient, isNotificationRoleKey } from '../../src/onboarding.js';
import { accountStatusPayload } from '../../src/commands/onboarding.js';
import { notificationMenu } from '../../src/notification-roles.js';
import { canTransition, sanitizeTicketText, staffRolesForCategory } from '../../src/tickets.js';
describe('onboarding safety', () => { it('accepts only allowlisted notification roles', () => { expect(isNotificationRoleKey('news')).toBe(true); expect(isNotificationRoleKey('administrator')).toBe(false); expect(isNotificationRoleKey('verified')).toBe(false); }); it('uses configured Slice website handoffs without accepting Discord credentials', () => { const client = new SliceWebsiteHandoffClient('https://slice.example/'); expect(client.handoff('account')).toMatchObject({ available: true, url: 'https://slice.example/account' }); expect(client.handoff('your-actions')).toMatchObject({ available: true, url: 'https://slice.example/collector-workspace' }); expect(new SliceWebsiteHandoffClient().handoff('account')).toMatchObject({ available: false }); }); it('keeps FAQ policy-safe', () => { expect(FAQ.fees).not.toMatch(/\d+[.%]/); expect(FAQ.security).toMatch(/Never share/); }); });
describe('account link response safety', () => { it('keeps unlinked and linked account controls ephemeral-ready and free of Discord credential collection', () => { const website = new SliceWebsiteHandoffClient('https://slice.example'); expect(accountStatusPayload({ ok: true, value: { linked: false } }, website).components).toHaveLength(1); const linked = accountStatusPayload({ ok: true, value: { linked: true, user: { username: 'slice', displayName: 'Slice Member', roles: ['COLLECTOR'], preferredCurrency: 'GBP', collector: { enabled: true, membership: null, openActionCount: 0 }, portfolio: { available: false }, orders: { available: false } } } }, website); expect(JSON.stringify(linked)).toContain('@slice'); expect(JSON.stringify(linked)).not.toMatch(/password|api key|verification code/i); }); });
describe('notification preference discovery', () => { it('uses the stable managed selector route', () => { expect(notificationMenu()[0]?.components[0]?.data.custom_id).toBe('slice:roles:notifications'); }); });
describe('ticket domain safety', () => { it('enforces lifecycle transitions', () => { expect(canTransition('OPEN', 'CLAIMED')).toBe(true); expect(canTransition('CLOSED', 'OPEN')).toBe(false); }); it('redacts secret-like ticket text', () => { expect(sanitizeTicketText('my password is hello and api key abc')).toContain('[redacted]'); }); it('narrows sensitive ticket routing', () => { expect(staffRolesForCategory('security-concern')).not.toContain('moderator'); expect(staffRolesForCategory('verification-help')).toContain('support'); expect(staffRolesForCategory('verification-help')).not.toContain('compliance'); }); });
