import { describe, expect, it } from 'vitest';
import { InMemorySetupRepository } from '../../src/persistence/setup-repository.js';

describe('guild-scoped setup persistence', () => {
  it('upserts and reads a guild configuration', async () => { const repository = new InMemorySetupRepository(); await repository.upsertGuildConfig({ guildId: 'A', setupVersion: 2, setupStatus: 'APPLIED' }); expect((await repository.getGuildConfig('A'))?.setupVersion).toBe(2); });
  it('enforces one logical resource per guild and type', async () => { const repository = new InMemorySetupRepository(); const resource = { guildId: 'A', resourceType: 'CHANNEL' as const, logicalKey: 'general', discordId: 'one', expectedName: 'general', parentLogicalKey: 'community', setupVersion: 2, metadata: null }; await repository.upsertResource(resource); await repository.upsertResource({ ...resource, discordId: 'two' }); expect((await repository.listResources('A'))).toEqual([{ ...resource, discordId: 'two' }]); });
  it('keeps resources and panels isolated between guilds', async () => { const repository = new InMemorySetupRepository(); await repository.upsertResource({ guildId: 'A', resourceType: 'ROLE', logicalKey: 'support', discordId: 'role-a', expectedName: 'Support', parentLogicalKey: null, setupVersion: 2, metadata: null }); await repository.upsertPanel({ guildId: 'A', logicalKey: 'faq', channelId: 'channel-a', messageId: 'message-a', templateKey: 'faq', artworkKey: null, version: 2 }); expect(await repository.getResource('B', 'ROLE', 'support')).toBeNull(); expect(await repository.getPanel('B', 'faq')).toBeNull(); });
  it('updates a canonical panel rather than creating another reference', async () => { const repository = new InMemorySetupRepository(); const panel = { guildId: 'A', logicalKey: 'faq', channelId: 'channel', messageId: 'one', templateKey: 'faq', artworkKey: null, version: 2 }; await repository.upsertPanel(panel); await repository.upsertPanel({ ...panel, messageId: 'two' }); expect(await repository.listPanels('A')).toEqual([{ ...panel, messageId: 'two' }]); });
  it('replaces a stale Discord resource ID without changing the logical key', async () => { const repository = new InMemorySetupRepository(); const resource = { guildId: 'A', resourceType: 'CHANNEL' as const, logicalKey: 'staff', discordId: 'deleted-id', expectedName: 'staff', parentLogicalKey: 'staff', setupVersion: 1, metadata: null }; await repository.upsertResource(resource); await repository.upsertResource({ ...resource, discordId: 'replacement-id', setupVersion: 2 }); expect((await repository.getResource('A', 'CHANNEL', 'staff'))).toMatchObject({ discordId: 'replacement-id', setupVersion: 2 }); });
  it('updates manifest version independently for each guild', async () => { const repository = new InMemorySetupRepository(); await repository.upsertGuildConfig({ guildId: 'A', setupVersion: 1, setupStatus: 'APPLIED' }); await repository.upsertGuildConfig({ guildId: 'B', setupVersion: 2, setupStatus: 'APPLIED' }); await repository.upsertGuildConfig({ guildId: 'A', setupVersion: 2, setupStatus: 'APPLIED' }); expect((await repository.getGuildConfig('A'))?.setupVersion).toBe(2); expect((await repository.getGuildConfig('B'))?.setupVersion).toBe(2); });
  it('resets only the selected guild setup data', async () => { const repository = new InMemorySetupRepository(); await repository.upsertGuildConfig({ guildId: 'A', setupVersion: 2, setupStatus: 'APPLIED' }); await repository.upsertGuildConfig({ guildId: 'B', setupVersion: 2, setupStatus: 'APPLIED' }); await repository.upsertResource({ guildId: 'A', resourceType: 'CHANNEL', logicalKey: 'general', discordId: 'channel-a', expectedName: 'general', parentLogicalKey: null, setupVersion: 2, metadata: null }); await repository.upsertPanel({ guildId: 'A', logicalKey: 'faq', channelId: 'channel-a', messageId: 'message-a', templateKey: 'faq', artworkKey: null, version: 2 }); await repository.resetGuildData('A'); expect(await repository.getGuildConfig('A')).toBeNull(); expect(await repository.listResources('A')).toEqual([]); expect(await repository.listPanels('A')).toEqual([]); expect((await repository.getGuildConfig('B'))?.setupVersion).toBe(2); });
});
