import { describe, expect, it } from 'vitest';
import { TicketInactivityService, type InactivityRepository } from '../../src/ticket-inactivity.js';
import { TicketLifecycleService, type LifecycleRepository, type LifecycleTicket } from '../../src/ticket-lifecycle.js';
import { TicketTranscriptService, type TranscriptRecord, type TranscriptRepository, type TranscriptSource } from '../../src/ticket-transcripts.js';

const now = new Date('2026-08-08T12:00:00.000Z');
function ticket(overrides: Partial<LifecycleTicket> = {}): LifecycleTicket { return { id: 'ticket-1', guildId: 'guild-1', channelId: 'channel-1', creatorId: 'creator-1', category: 'general-support', subject: 'Need help', createdAt: new Date('2026-08-01T00:00:00.000Z'), lastActivityAt: new Date('2026-08-01T00:00:00.000Z'), status: 'WAITING_USER', priority: 'NORMAL', updatedAt: new Date('2026-08-01T00:00:00.000Z'), ...overrides }; }
class Store implements LifecycleRepository, InactivityRepository, TranscriptRepository {
  current = ticket(); events: string[] = []; transcript?: TranscriptRecord;
  async get(id: string, guildId: string) { return id === this.current.id && guildId === this.current.guildId ? { ...this.current } : null; }
  async compareAndSet(next: LifecycleTicket, event: string) { if (next.updatedAt.getTime() !== this.current.updatedAt.getTime()) return false; this.current = { ...next, updatedAt: new Date(next.updatedAt.getTime() + 1), lastActivityAt: now }; this.events.push(event); return true; }
  async listWarningCandidates(before: Date) { return this.current.status === 'WAITING_USER' && !this.current.inactivityWarnedAt && this.current.lastActivityAt <= before ? [{ ...this.current }] : []; }
  async listCloseCandidates(before: Date) { return this.current.status === 'WAITING_USER' && !!this.current.inactivityWarnedAt && this.current.inactivityWarnedAt <= before ? [{ ...this.current }] : []; }
  async markWarning(row: LifecycleTicket, at: Date) { if (row.updatedAt.getTime() !== this.current.updatedAt.getTime() || this.current.inactivityWarnedAt) return false; this.current = { ...this.current, inactivityWarnedAt: at, updatedAt: new Date(row.updatedAt.getTime() + 1) }; return true; }
  async getTranscriptSource(id: string, guildId: string): Promise<TranscriptSource | null> { const row = await this.get(id, guildId); return row?.status === 'CLOSED' ? { ...row, safeSummary: 'safe', events: this.events.map((type) => ({ type, createdAt: now })) } : null; }
  async getTranscript(id: string) { return id === this.transcript?.ticketId ? this.transcript : null; }
  async saveTranscript(record: TranscriptRecord) { this.transcript = record; return record; }
  async markTranscriptDelivered() {}
}
describe('ticket transcripts', () => {
  it('creates ordered redacted lifecycle transcripts and reuses them', async () => { const store = new Store(); store.current.status = 'CLOSED'; store.current.closedAt = now; store.events = ['CLOSED']; const service = new TicketTranscriptService(store); const first = await service.generate('ticket-1', 'guild-1', { read: async () => ({ partial: false, messages: [{ id: '2', createdAt: new Date('2026-08-08T11:00:00Z'), authorId: 'u2', authorLabel: 'U2', content: 'authorization: Bearer secret', bot: false, attachments: [] }, { id: '1', createdAt: new Date('2026-08-08T10:00:00Z'), authorId: 'u1', authorLabel: 'U1', content: 'first', bot: false, attachments: [] }] }) }); expect(first.transcript.content.indexOf('first')).toBeLessThan(first.transcript.content.indexOf('U2')); expect(first.transcript.content).toContain('[redacted]'); expect((await service.generate('ticket-1', 'guild-1', { read: async () => { throw new Error('should not run'); } })).reused).toBe(true); });
  it('persists partial and failed history states without reopening a closed ticket', async () => { const store = new Store(); store.current.status = 'CLOSED'; const service = new TicketTranscriptService(store); expect((await service.generate('ticket-1', 'guild-1', { read: async () => ({ partial: true, messages: [] }) })).transcript.status).toBe('PARTIAL'); store.transcript = undefined; expect((await service.generate('ticket-1', 'guild-1', { read: async () => { throw new Error('unavailable'); } })).transcript.status).toBe('FAILED'); expect(store.current.status).toBe('CLOSED'); });
});
describe('ticket inactivity', () => {
  const policy = { enabled: true, warningHours: 48, closeHours: 72, batchSize: 10 };
  it('warns once only after the waiting-user threshold', async () => { const store = new Store(); store.current.lastActivityAt = new Date(now.getTime() - 49 * 3_600_000); const notices: string[] = []; const service = new TicketInactivityService(store, new TicketLifecycleService(store), { warn: async () => { notices.push('warn'); }, closed: async () => { notices.push('closed'); } }, policy); expect(await service.scan(now)).toEqual({ warned: 1, closed: 0 }); expect(await service.scan(now)).toEqual({ warned: 0, closed: 0 }); expect(notices).toEqual(['warn']); });
  it('does not warn under threshold or for waiting staff and terminal states', async () => { for (const status of ['WAITING_USER', 'WAITING_STAFF', 'RESOLVED', 'CLOSED'] as const) { const store = new Store(); store.current.status = status; store.current.lastActivityAt = status === 'WAITING_USER' ? new Date(now.getTime() - 47 * 3_600_000) : new Date(now.getTime() - 100 * 3_600_000); const service = new TicketInactivityService(store, new TicketLifecycleService(store), { warn: async () => { throw new Error('unexpected'); }, closed: async () => { throw new Error('unexpected'); } }, policy); expect(await service.scan(now)).toEqual({ warned: 0, closed: 0 }); } });
  it('resets warning authority after activity and skips stale auto-close', async () => { const store = new Store(); store.current.lastActivityAt = new Date(now.getTime() - 100 * 3_600_000); store.current.inactivityWarnedAt = new Date(now.getTime() - 73 * 3_600_000); store.current.lastActivityAt = new Date(now.getTime() - 1_000); store.current.inactivityWarnedAt = undefined; const service = new TicketInactivityService(store, new TicketLifecycleService(store), { warn: async () => {}, closed: async () => { throw new Error('unexpected'); } }, policy); expect(await service.scan(now)).toEqual({ warned: 0, closed: 0 }); expect(store.current.status).toBe('WAITING_USER'); });
  it('auto-closes only reloaded waiting-user tickets through lifecycle events', async () => { const store = new Store(); store.current.lastActivityAt = new Date(now.getTime() - 200 * 3_600_000); store.current.inactivityWarnedAt = new Date(now.getTime() - 73 * 3_600_000); const closed: string[] = []; const service = new TicketInactivityService(store, new TicketLifecycleService(store), { warn: async () => {}, closed: async (row) => { closed.push(row.id); } }, policy); expect(await service.scan(now)).toEqual({ warned: 0, closed: 1 }); expect(store.current.status).toBe('CLOSED'); expect(store.events).toEqual(['CLOSED']); expect(closed).toEqual(['ticket-1']); });
});
