import { describe, expect, it } from 'vitest';
import { refreshTicketMessage, ticketLifecycleComponents } from '../../src/ticket-discord.js';
import { TicketLifecycleService, type LifecycleActor, type LifecycleRepository, type LifecycleTicket } from '../../src/ticket-lifecycle.js';
import { parseTicketControlId, TicketInteractionRouter, type TicketAuthorization, type TicketLookup } from '../../src/ticket-routing.js';

class TicketStore implements LifecycleRepository, TicketLookup {
  ticket: LifecycleTicket;
  events: string[] = [];
  constructor(overrides: Partial<LifecycleTicket> = {}) { this.ticket = { id: 'ticket-1', guildId: 'guild-1', channelId: 'channel-1', creatorId: 'creator-1', category: 'general-support', subject: 'Need help', createdAt: new Date('2026-08-01T00:00:00.000Z'), lastActivityAt: new Date('2026-08-01T00:00:00.000Z'), status: 'OPEN', priority: 'NORMAL', updatedAt: new Date('2026-08-01T00:00:00.000Z'), ...overrides }; }
  async get(id: string, guildId: string): Promise<LifecycleTicket | null> { return id === this.ticket.id && guildId === this.ticket.guildId ? { ...this.ticket } : null; }
  async findByChannel(guildId: string, channelId: string): Promise<LifecycleTicket | null> { return guildId === this.ticket.guildId && channelId === this.ticket.channelId ? { ...this.ticket } : null; }
  async compareAndSet(ticket: LifecycleTicket, event: string): Promise<boolean> { if (ticket.updatedAt.getTime() !== this.ticket.updatedAt.getTime()) return false; this.ticket = { ...ticket, updatedAt: new Date(this.ticket.updatedAt.getTime() + 1) }; this.events.push(event); return true; }
}

const actor = (id: string, staff = true, eligible = true, owner = false): LifecycleActor => ({ id, staff, eligible, admin: id === 'admin', owner });
const authorization: TicketAuthorization = { actor: async (ticket, id) => actor(id, id.startsWith('staff') || id === 'admin', true, id === ticket.creatorId), target: async (_ticket, id) => actor(id, id === 'staff-target', id === 'staff-target') };
const context = { guildId: 'guild-1', channelId: 'channel-1', actorId: 'staff-1', ticketId: 'ticket-1' };
function router(store = new TicketStore()) { return { store, router: new TicketInteractionRouter(new TicketLifecycleService(store), store, authorization) }; }

describe('persistent ticket lifecycle interaction routing', () => {
  it('routes CLAIM using trusted guild, channel, and actor context', async () => { const { store, router: subject } = router(); const result = await subject.execute('claim', context); expect(result).toMatchObject({ ok: true, changed: true, ticket: { assignedStaffId: 'staff-1', status: 'CLAIMED' } }); expect(store.events).toEqual(['CLAIMED']); });
  it('allows only the ticket owner to use the customer close control', async () => { const { store, router: subject } = router(); await expect(subject.execute('close-confirm', { ...context, actorId: 'member' })).resolves.toMatchObject({ ok: false }); await expect(subject.execute('close-confirm', { ...context, actorId: 'creator-1' })).resolves.toMatchObject({ ok: true, changed: true, ticket: { status: 'CLOSED' } }); expect(store.events).toEqual(['CLOSED']); });
  it('persists an authorized unclaim without allowing unrelated staff to clear assignment', async () => { const { store, router: subject } = router(); await subject.execute('claim', context); await expect(subject.execute('unclaim', { ...context, actorId: 'staff-2' })).resolves.toMatchObject({ ok: false }); await expect(subject.execute('unclaim', context)).resolves.toMatchObject({ ok: true, changed: true, ticket: { status: 'OPEN', assignedStaffId: undefined } }); expect(store.events).toEqual(['CLAIMED', 'UNCLAIMED']); });
  it('returns safe claim replays without duplicate events', async () => { const { store, router: subject } = router(); await subject.execute('claim', context); const replay = await subject.execute('claim', context); const later = await subject.execute('claim', { ...context, actorId: 'staff-2' }); expect(replay).toMatchObject({ ok: true, changed: false }); expect(later).toMatchObject({ ok: false, message: 'This ticket action is no longer available. Refresh and try again.' }); expect(store.events).toEqual(['CLAIMED']); });
  it('routes waiting-user and waiting-staff through lifecycle transitions', async () => { const { store, router: subject } = router(); expect((await subject.execute('waiting-user', context)).ticket?.status).toBe('WAITING_USER'); expect((await subject.execute('waiting-staff', context)).ticket?.status).toBe('WAITING_STAFF'); expect(store.events).toEqual(['STATUS_CHANGED', 'STATUS_CHANGED']); });
  it('allowlists priority values before invoking lifecycle authority', async () => { const { store, router: subject } = router(); await expect(subject.execute('priority-submit', context, { priority: 'crafted' })).resolves.toMatchObject({ ok: false }); expect(store.events).toEqual([]); await expect(subject.execute('priority-submit', context, { priority: 'URGENT' })).resolves.toMatchObject({ ok: true, changed: true, ticket: { priority: 'URGENT' } }); });
  it('validates transfer candidates as eligible staff', async () => { const { store, router: subject } = router(); await expect(subject.execute('transfer-submit', context, { targetId: 'member' })).resolves.toMatchObject({ ok: false }); expect(store.events).toEqual([]); await expect(subject.execute('transfer-submit', context, { targetId: 'staff-target' })).resolves.toMatchObject({ ok: true, changed: true, ticket: { assignedStaffId: 'staff-target' } }); });
  it('routes escalation and returns the configured logical target', async () => { const { store, router: subject } = router(); const result = await subject.execute('escalate', context); expect(result).toMatchObject({ ok: true, changed: true, escalationTarget: 'owner' }); expect(store.events).toEqual(['ESCALATED']); });
  it('requires persistent confirmation controls for resolve and close', async () => { expect(parseTicketControlId('slice:ticket:resolve-confirm:ticket-1')).toEqual({ action: 'resolve-confirm', ticketId: 'ticket-1' }); expect(parseTicketControlId('slice:ticket:close-confirm:ticket-1')).toEqual({ action: 'close-confirm', ticketId: 'ticket-1' }); const { store, router: subject } = router(); await subject.execute('resolve-confirm', context); await subject.execute('close-confirm', context); expect(store.events).toEqual(['RESOLVED', 'CLOSED']); expect(ticketLifecycleComponents(store.ticket).flatMap((row) => row.components).every((component) => component.data.disabled)).toBe(true); });
  it('rejects stale controls after a ticket is closed without appending an event', async () => { const { store, router: subject } = router(new TicketStore({ status: 'CLOSED' })); const result = await subject.execute('claim', context); expect(result).toMatchObject({ ok: false, message: 'This ticket action is no longer available. Refresh and try again.' }); expect(store.events).toEqual([]); });
  it('rejects wrong guild or channel context without disclosing ticket state', async () => { const { store, router: subject } = router(); await expect(subject.execute('claim', { ...context, guildId: 'other-guild' })).resolves.toMatchObject({ ok: false, message: 'This ticket control is unavailable.' }); await expect(subject.execute('claim', { ...context, channelId: 'other-channel' })).resolves.toMatchObject({ ok: false, message: 'This ticket control is unavailable.' }); expect(store.events).toEqual([]); });
  it('keeps the database mutation authoritative when a Discord refresh fails', async () => { const { store, router: subject } = router(); const result = await subject.execute('claim', context); await expect(refreshTicketMessage({ edit: async () => { throw new Error('Discord edit failed'); } }, result.ticket!)).rejects.toThrow('Discord edit failed'); expect(store.ticket.assignedStaffId).toBe('staff-1'); expect(store.events).toEqual(['CLAIMED']); });
  it('resolves slash-command actions by trusted channel without user ticket identifiers', async () => { const { store, router: subject } = router(); const result = await subject.executeForChannel('claim', { guildId: 'guild-1', channelId: 'channel-1', actorId: 'staff-1' }); expect(result).toMatchObject({ ok: true, changed: true }); expect(store.events).toEqual(['CLAIMED']); });
});
