import { PrismaClient } from '@prisma/client';
import { NotificationDeliveryWorkerRepository } from '../src/modules/outbox/application/notification-delivery-worker.repository';
import { InAppNotificationTransport } from '../src/modules/outbox/application/in-app-notification.transport';
import { NotificationTransportRegistry } from '../src/modules/outbox/application/notification-transport-registry';
import { NotificationDeliveryWorkerService } from '../src/modules/outbox/application/notification-delivery-worker.service';
import { setNotificationDeliveryWorkerTestFailureHook } from '../src/modules/outbox/application/notification-delivery-worker-test-failure';

const url=process.env.TEST_DATABASE_URL;if(!url)throw new Error('TEST_DATABASE_URL required');
const db=new PrismaClient({datasources:{db:{url}}});const run=`delivery-worker-${Date.now()}`;const repo=new NotificationDeliveryWorkerRepository(db as never);let now=new Date('2000-01-01T00:00:00.000Z');
describe('Document 017 delivery worker PostgreSQL reliability',()=>{
 beforeAll(()=>db.$connect());beforeEach(async()=>{now=new Date('2000-01-01T00:00:00.000Z');setNotificationDeliveryWorkerTestFailureHook(undefined);await db.notificationDelivery.deleteMany({where:{deliveryId:{startsWith:run}}});await db.outboxEvent.deleteMany({where:{eventId:{startsWith:run}}});await db.notification.deleteMany({where:{deliveryId:{startsWith:`delivery:${run}`}}});await db.user.deleteMany({where:{normalizedEmail:{startsWith:run}}});});afterAll(async()=>{setNotificationDeliveryWorkerTestFailureHook(undefined);await db.notificationDelivery.deleteMany({where:{deliveryId:{startsWith:run}}});await db.outboxEvent.deleteMany({where:{eventId:{startsWith:run}}});await db.notification.deleteMany({where:{deliveryId:{startsWith:`delivery:${run}`}}});await db.user.deleteMany({where:{normalizedEmail:{startsWith:run}}});await db.$disconnect();});
 async function rows(n=1){const event=await db.outboxEvent.create({data:{eventId:`${run}-event`,eventType:'test.event',aggregateType:'test',aggregateId:run,schemaVersion:1,occurredAt:new Date('1999-01-01'),payload:{ok:true},availableAt:new Date('1999-01-01')}});return Promise.all([...Array(n)].map((_,i)=>db.notificationDelivery.create({data:{deliveryId:`${run}-${i}`,outboxEventId:event.id,channel:i===0?'IN_APP':'DISCORD',destinationKey:`user:${run}-${i}`,classification:'PRIVATE',topic:'ORDER_UPDATES',payloadVersion:1,payload:{ok:true},idempotencyKey:`${run}-${i}`,availableAt:new Date('1999-01-01')}})));}
 it('keeps Discord claims out of the in-process worker',async()=>{await rows(4);const[a,b]=await Promise.all([repo.claimBatch('a',2,1000,now),repo.claimBatch('b',2,1000,now)]);const claimed=[...a,...b];expect(claimed).toHaveLength(1);expect(claimed[0]?.channel).toBe('IN_APP');expect(claimed[0]?.claimToken).toBeTruthy();});
 it('reclaims expired lease without incrementing attempts and fences stale finalization',async()=>{const [row]=await rows();const[a]=await repo.claimBatch('a',1,1000,now);now=new Date(now.getTime()+1001);const[b]=await repo.claimBatch('b',1,1000,now);expect(b.id).toBe(row.id);expect(b.claimToken).not.toBe(a.claimToken);expect((await db.notificationDelivery.findUniqueOrThrow({where:{id:row.id}})).attempts).toBe(0);expect(await repo.success(row.id,a.claimToken,now)).toBe(false);expect(await repo.success(row.id,b.claimToken,now)).toBe(true);});
 it('leaves Discord delivery claims pending for the authenticated bot consumer',async()=>{const [row]=await rows(2);const discord=(await db.notificationDelivery.findFirstOrThrow({where:{channel:'DISCORD',deliveryId:{startsWith:run}}}));const claims=await repo.claimBatch('a',2,1000,now);expect(claims.map((claim)=>claim.id)).not.toContain(discord.id);expect((await db.notificationDelivery.findUniqueOrThrow({where:{id:discord.id}})).status).toBe('PENDING');void row;});
 it('reuses one in-app Notification after finalization failure and lease recovery',async()=>{const user=await db.user.create({data:{email:`${run}@test.local`,normalizedEmail:`${run}@test.local`,passwordHash:'test',accountStatus:'ACTIVE'}});const [row]=await rows();await db.notificationDelivery.update({where:{id:row.id},data:{destinationKey:`user:${user.id}`}});const transport=new InAppNotificationTransport(db as never);const registry=new NotificationTransportRegistry(transport);const worker=new NotificationDeliveryWorkerService(repo,registry,{outboxBatchSize:1,outboxLeaseMs:1000,outboxMaxAttempts:3,outboxRetryBaseMs:100,outboxRetryMaxMs:1000} as never);setNotificationDeliveryWorkerTestFailureHook(()=>{throw new Error('INJECTED_FINALIZE')});await expect(worker.runOnce(now,'a')).rejects.toThrow('INJECTED_FINALIZE');expect(await db.notification.count({where:{deliveryId:row.deliveryId}})).toBe(1);let state=await db.notificationDelivery.findUniqueOrThrow({where:{id:row.id}});expect(state.status).toBe('PROCESSING');setNotificationDeliveryWorkerTestFailureHook(undefined);now=new Date(state.leaseExpiresAt!.getTime()+1);await worker.runOnce(now,'b');state=await db.notificationDelivery.findUniqueOrThrow({where:{id:row.id}});expect(state.status).toBe('DELIVERED');expect(await db.notification.count({where:{deliveryId:row.deliveryId}})).toBe(1);});
 it('backs off retryable delivery failures then dead-letters at the bounded attempt limit',async()=>{const [row]=await rows();const registry={get:()=>({channel:'IN_APP' as const,deliver:async()=>({status:'RETRYABLE_FAILURE' as const,code:'TEST_RETRY'})})} as unknown as NotificationTransportRegistry;const worker=new NotificationDeliveryWorkerService(repo,registry,{outboxBatchSize:1,outboxLeaseMs:1000,outboxMaxAttempts:3,outboxRetryBaseMs:100,outboxRetryMaxMs:1000} as never);await worker.runOnce(now,'a');let state=await db.notificationDelivery.findUniqueOrThrow({where:{id:row.id}});expect(state).toMatchObject({status:'PENDING',attempts:1,lastErrorSafe:'TEST_RETRY',claimToken:null});expect(state.availableAt.getTime()-now.getTime()).toBe(100);expect(await repo.claimBatch('early',1,1000,new Date(now.getTime()+99))).toHaveLength(0);now=state.availableAt;await worker.runOnce(now,'b');state=await db.notificationDelivery.findUniqueOrThrow({where:{id:row.id}});expect(state).toMatchObject({status:'PENDING',attempts:2,lastErrorSafe:'TEST_RETRY',claimToken:null});expect(state.availableAt.getTime()-now.getTime()).toBe(200);now=state.availableAt;await worker.runOnce(now,'c');state=await db.notificationDelivery.findUniqueOrThrow({where:{id:row.id}});expect(state).toMatchObject({status:'DEAD_LETTER',attempts:3,lastErrorSafe:'TEST_RETRY',claimToken:null});expect(state.deadLetteredAt).toEqual(now);});
});
