import { Client, type Guild } from 'discord.js';
import { MarketFeedRenderer } from './market-renderer.js';
import type { SetupRepository } from './persistence/setup-repository.js';
import { PrismaDiscordDeliveryRepository } from './persistence/discord-delivery-repository.js';
import { SliceDiscordDeliveryClient, type DiscordDelivery } from './slice-discord-delivery-client.js';

const destinationResources: Record<DiscordDelivery['destinationKey'], string> = { 'discord.market_feed': 'market-feed', 'discord.recent_sales': 'recent-sales', 'discord.new_listings': 'new-listings', 'discord.price_alerts': 'price-alerts', 'discord.platform_updates': 'platform-updates' };
/** Delivery worker consumes only an authenticated backend seam and retains no event authority. */
export class DiscordDeliveryWorker {
  constructor(private readonly client: SliceDiscordDeliveryClient, private readonly receipts: PrismaDiscordDeliveryRepository, private readonly setup: SetupRepository, private readonly discord: Client, private readonly report: (event: string, fields: Record<string, unknown>) => void) {}
  async scan(): Promise<void> { const response = await this.client.pull(); if (response.status !== 'READY') { if (response.status !== 'BACKEND_SEAM_REQUIRED') this.report('discord_delivery.unavailable', { status: response.status }); return; } for (const delivery of response.deliveries) await this.process(delivery); }
  private async process(delivery: DiscordDelivery & { guildId?: string }): Promise<void> { if (!delivery.guildId || !valid(delivery)) { this.report('discord_delivery.invalid', { deliveryId: delivery.deliveryId }); return; } const receipt = await this.receipts.receipt({ guildId: delivery.guildId, deliveryId: delivery.deliveryId, eventId: delivery.eventId, destination: delivery.destinationKey }); if (receipt.status === 'DELIVERED') return; const guild = await this.discord.guilds.fetch(delivery.guildId).catch(() => null); if (!guild) return void await this.fail(delivery, 'DESTINATION_UNAVAILABLE'); const channel = await this.destination(guild, delivery.destinationKey); if (!channel) return void await this.fail(delivery, 'DESTINATION_UNAVAILABLE'); try { const message = await channel.send({ embeds: [MarketFeedRenderer.recentSale({ assetTitle: delivery.payload.assetTitle, price: { minor: delivery.payload.priceMinor, currency: delivery.payload.currency }, units: delivery.payload.units, occurredAt: delivery.payload.occurredAt })], allowedMentions: { parse: [], roles: [], users: [], repliedUser: false } }); await this.receipts.complete(delivery.deliveryId, 'DELIVERED', channel.id, message.id); await this.client.acknowledge(delivery.deliveryId, 'DELIVERED'); } catch (error) { this.report('discord_delivery.send_failed', { deliveryId: delivery.deliveryId, name: error instanceof Error ? error.name : 'unknown' }); await this.fail(delivery, 'RETRYABLE_FAILURE'); }
  }
  private async destination(guild: Guild, key: DiscordDelivery['destinationKey']) { const resource = await this.setup.getResource(guild.id, 'CHANNEL', destinationResources[key]); const channel = resource ? await guild.channels.fetch(resource.discordId).catch(() => null) : null; return channel?.isTextBased() && 'send' in channel ? channel : null; }
  private async fail(delivery: DiscordDelivery, outcome: 'RETRYABLE_FAILURE' | 'DESTINATION_UNAVAILABLE'): Promise<void> { await this.receipts.complete(delivery.deliveryId, outcome, undefined, undefined, outcome); await this.client.acknowledge(delivery.deliveryId, outcome); }
}
function valid(value: DiscordDelivery): boolean { return value.eventType === 'trade.completed' && value.schemaVersion === 1 && /^\S.{0,255}$/.test(value.payload.assetTitle) && /^\d+$/.test(value.payload.priceMinor) && /^[A-Z]{3}$/.test(value.payload.currency) && !Number.isNaN(Date.parse(value.payload.occurredAt)); }
