import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, PermissionFlagsBits, type ChatInputCommandInteraction } from 'discord.js';
import { colorNumber, presentationConfig } from './presentation-config.js';

export type EmbedField = { name: string; value: string; inline?: boolean };
export type LinkButton = { label: string; url: string; emoji?: string };
export type EmbedPayload = { title?: string; url?: string; description?: string; color?: number; author?: { name: string; iconUrl?: string; url?: string }; thumbnail?: string; image?: string; fields?: EmbedField[]; footer?: { text: string; iconUrl?: string } | null; timestamp?: boolean };
export type EmbedTemplate = 'ANNOUNCEMENT' | 'UPDATE' | 'EVENT' | 'WARNING' | 'RELEASE_NOTES';

export const EMBED_TEMPLATES: Record<EmbedTemplate, { label: string; payload: EmbedPayload }> = {
  ANNOUNCEMENT: { label: 'Announcement', payload: { title: 'Slice announcement', description: 'Share an important update with the Slice community.', timestamp: true } },
  UPDATE: { label: 'Product update', payload: { title: 'Slice update', description: 'Here is what is new.', color: 0x5865f2, timestamp: true } },
  EVENT: { label: 'Community event', payload: { title: 'Slice community event', description: 'Join the conversation.', color: 0x57f287, fields: [{ name: 'When', value: 'Add the event date and time', inline: true }, { name: 'Where', value: 'Add the channel or location', inline: true }], timestamp: true } },
  WARNING: { label: 'Important notice', payload: { title: 'Important Slice notice', description: 'Please review this update carefully.', color: 0xfee75c, timestamp: true } },
  RELEASE_NOTES: { label: 'Release notes', payload: { title: 'Slice release notes', description: 'Highlights from this release.', color: 0xeb459e, fields: [{ name: 'New', value: 'Add the first highlight' }, { name: 'Improved', value: 'Add an improvement' }], timestamp: true } },
};

export function canManageEmbeds(interaction: Pick<ChatInputCommandInteraction, 'guildId' | 'memberPermissions'>): boolean { return Boolean(interaction.guildId && interaction.memberPermissions?.has(PermissionFlagsBits.ManageGuild)); }
export function safeUrl(value: string | undefined): string | undefined { if (!value) return undefined; try { const url = new URL(value); return url.protocol === 'https:' && !/^(localhost|127\.|10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(url.hostname) ? url.toString() : undefined; } catch { return undefined; } }
export function validateEmbed(payload: EmbedPayload, buttons: LinkButton[] = []): string[] { const errors: string[] = []; const fields = payload.fields ?? []; const size = (payload.title?.length ?? 0) + (payload.description?.length ?? 0) + (payload.author?.name.length ?? 0) + (payload.footer?.text.length ?? 0) + fields.reduce((n, field) => n + field.name.length + field.value.length, 0); if (!payload.title && !payload.description && !fields.length) errors.push('Add a title, description, or field.'); if ((payload.title?.length ?? 0) > 256) errors.push('Title exceeds 256 characters.'); if ((payload.description?.length ?? 0) > 4096) errors.push('Description exceeds 4096 characters.'); if (fields.length > 25) errors.push('Discord allows at most 25 fields.'); if (fields.some((field) => !field.name.trim() || !field.value.trim() || field.name.length > 256 || field.value.length > 1024)) errors.push('Each field needs a name and value within Discord limits.'); if ((payload.footer?.text.length ?? 0) > 2048 || (payload.author?.name.length ?? 0) > 256 || size > 6000) errors.push('Embed total or metadata exceeds Discord limits.'); for (const value of [payload.url, payload.thumbnail, payload.image, payload.author?.iconUrl, payload.author?.url, payload.footer?.iconUrl]) if (value && !safeUrl(value)) errors.push('URLs must be public HTTPS URLs.'); if (buttons.length > 5 || buttons.some((button) => !button.label.trim() || button.label.length > 80 || !safeUrl(button.url) || (button.emoji?.length ?? 0) > 32)) errors.push('Link buttons need labels, public HTTPS URLs, and optional short emoji (maximum 5).'); return errors; }
export function renderEmbed(payload: EmbedPayload): EmbedBuilder { const branding = presentationConfig()['branding.yml']; const embed = new EmbedBuilder().setColor(payload.color ?? colorNumber(branding.colors.info)); if (payload.title) embed.setTitle(payload.title); if (payload.url) embed.setURL(payload.url); if (payload.description) embed.setDescription(payload.description); if (payload.author) embed.setAuthor({ name: payload.author.name, ...(payload.author.iconUrl ? { iconURL: payload.author.iconUrl } : {}), ...(payload.author.url ? { url: payload.author.url } : {}) }); if (payload.thumbnail) embed.setThumbnail(payload.thumbnail); if (payload.image) embed.setImage(payload.image); if (payload.fields?.length) embed.addFields(payload.fields); if (payload.footer === null) embed.setFooter(null); else embed.setFooter(payload.footer ?? { text: branding.footer.text }); if (payload.timestamp) embed.setTimestamp(); return embed; }
export function builderControls(id: string) { return [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`slice:embed:${id}:title`).setLabel('Title').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`slice:embed:${id}:description`).setLabel('Description').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`slice:embed:${id}:color`).setLabel('Color').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`slice:embed:${id}:author`).setLabel('Author').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`slice:embed:${id}:footer`).setLabel('Footer').setStyle(ButtonStyle.Secondary)), new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`slice:embed:${id}:media`).setLabel('Media').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`slice:embed:${id}:fields`).setLabel('Fields').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`slice:embed:${id}:buttons`).setLabel('Links').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`slice:embed:${id}:target`).setLabel('Target').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`slice:embed:${id}:template`).setLabel('Template').setStyle(ButtonStyle.Primary)), new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`slice:embed:${id}:preview`).setLabel('Preview').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId(`slice:embed:${id}:publish`).setLabel('Publish').setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId(`slice:embed:${id}:schedule`).setLabel('Schedule').setStyle(ButtonStyle.Primary))]; }
export function parseFields(value: string): EmbedField[] | null { if (!value.trim()) return []; const fields = value.split('\n').map((line) => line.split('|').map((part) => part.trim())).map(([name, fieldValue, inline]) => ({ name, value: fieldValue, ...(inline?.toLowerCase() === 'inline' ? { inline: true } : {}) })); return fields.every((field) => Boolean(field.name && field.value)) ? fields : null; }
export function parseLinkButtons(value: string): LinkButton[] | null { if (!value.trim()) return []; const buttons = value.split('\n').map((line) => line.split('|').map((part) => part.trim())).map(([label, url, emoji]) => ({ label, url, ...(emoji ? { emoji } : {}) })); return buttons.every((button) => Boolean(button.label && button.url)) ? buttons : null; }
export function applyTemplate(template: EmbedTemplate): EmbedPayload { return structuredClone(EMBED_TEMPLATES[template].payload); }
