import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, PermissionFlagsBits, type ChatInputCommandInteraction } from 'discord.js';
import { colorNumber, presentationConfig } from './presentation-config.js';
export type EmbedField = { name: string; value: string; inline?: boolean }; export type LinkButton = { label: string; url: string; emoji?: string };
export type EmbedPayload = { title?: string; url?: string; description?: string; color?: number; author?: { name: string; iconUrl?: string; url?: string }; thumbnail?: string; image?: string; fields?: EmbedField[]; footer?: { text: string; iconUrl?: string } | null; timestamp?: boolean };
export function canManageEmbeds(interaction: Pick<ChatInputCommandInteraction, 'guildId' | 'memberPermissions'>): boolean { return Boolean(interaction.guildId && interaction.memberPermissions?.has(PermissionFlagsBits.ManageGuild)); }
export function safeUrl(value: string | undefined): string | undefined { if (!value) return undefined; try { const url = new URL(value); return url.protocol === 'https:' && !/^(localhost|127\.|10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(url.hostname) ? url.toString() : undefined; } catch { return undefined; } }
export function validateEmbed(payload: EmbedPayload, buttons: LinkButton[] = []): string[] { const errors: string[] = []; const size = (payload.title?.length ?? 0) + (payload.description?.length ?? 0) + (payload.author?.name.length ?? 0) + (payload.footer?.text.length ?? 0) + (payload.fields ?? []).reduce((n, field) => n + field.name.length + field.value.length, 0); if (!payload.title && !payload.description && !(payload.fields?.length)) errors.push('Add a title, description, or field.'); if ((payload.title?.length ?? 0) > 256) errors.push('Title exceeds 256 characters.'); if ((payload.description?.length ?? 0) > 4096) errors.push('Description exceeds 4096 characters.'); if ((payload.fields?.length ?? 0) > 25) errors.push('Discord allows at most 25 fields.'); if ((payload.fields ?? []).some((field) => field.name.length > 256 || field.value.length > 1024)) errors.push('A field exceeds Discord limits.'); if ((payload.footer?.text.length ?? 0) > 2048 || (payload.author?.name.length ?? 0) > 256 || size > 6000) errors.push('Embed total or metadata exceeds Discord limits.'); for (const value of [payload.url, payload.thumbnail, payload.image, payload.author?.iconUrl, payload.author?.url, payload.footer?.iconUrl]) if (value && !safeUrl(value)) errors.push('URLs must be public HTTPS URLs.'); if (buttons.length > 5 || buttons.some((button) => !button.label || button.label.length > 80 || !safeUrl(button.url))) errors.push('Link buttons must have labels and public HTTPS URLs (maximum 5).'); return errors; }
export function renderEmbed(payload: EmbedPayload): EmbedBuilder { const branding = presentationConfig()['branding.yml']; const embed = new EmbedBuilder().setColor(payload.color ?? colorNumber(branding.colors.info)); if (payload.title) embed.setTitle(payload.title); if (payload.url) embed.setURL(payload.url); if (payload.description) embed.setDescription(payload.description); if (payload.author) embed.setAuthor({ name: payload.author.name, ...(payload.author.iconUrl ? { iconURL: payload.author.iconUrl } : {}), ...(payload.author.url ? { url: payload.author.url } : {}) }); if (payload.thumbnail) embed.setThumbnail(payload.thumbnail); if (payload.image) embed.setImage(payload.image); if (payload.fields?.length) embed.addFields(payload.fields); if (payload.footer === null) embed.setFooter(null); else embed.setFooter(payload.footer ?? { text: branding.footer.text }); if (payload.timestamp) embed.setTimestamp(); return embed; }
export function builderControls(id: string) { return [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`slice:embed:${id}:title`).setLabel('Title').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`slice:embed:${id}:description`).setLabel('Description').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`slice:embed:${id}:color`).setLabel('Color').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`slice:embed:${id}:preview`).setLabel('Preview').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId(`slice:embed:${id}:publish`).setLabel('Publish').setStyle(ButtonStyle.Success)), new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`slice:embed:${id}:schedule`).setLabel('Schedule').setStyle(ButtonStyle.Primary))]; }
