import { SliceEmbed } from './embeds/slice-embed.js';
import type { MarketAsset, Money } from './slice-backend-client.js';
const money = (value?: Money | null) => value ? `${value.currency} ${(Number(value.minor) / 100).toFixed(2)}` : 'Unavailable';
export class MarketFeedRenderer {
  static asset(asset: MarketAsset) { const fields = [`**${asset.category?.name ?? 'Collectible'}**${asset.collectibleSet ? ` · ${asset.collectibleSet.name}` : ''}`, asset.grading ? `${asset.grading.companyCode} ${asset.grading.label}` : null, `Reference value: **${money(asset.estimatedMarketValue)}**`, asset.change24hBps === null || asset.change24hBps === undefined ? null : `Reported 24h movement: **${(asset.change24hBps / 100).toFixed(2)}%**`, `Asset reference: [${asset.publicId}]`].filter(Boolean).join('\n'); return SliceEmbed.configured('market.yml', 'asset', { asset: asset.title, reason: fields }); }
  static recentSale(input: { assetTitle: string; price: Money; units?: string; occurredAt: string }) { return SliceEmbed.configured('market.yml', 'recent_sale', { asset: input.assetTitle, price: money(input.price) }); }
  static list(title: string, assets: MarketAsset[]) { return SliceEmbed.configured('market.yml', 'list', { reason: title, status: assets.length ? assets.map((asset, index) => `**${index + 1}.** ${asset.title} — ${money(asset.estimatedMarketValue)}\n[${asset.slug}]`).join('\n') : 'No authoritative market results are available.' }); }
  static history(asset: string, points: Array<{ observedAt: string; estimatedMarketValue: Money }>) { return SliceEmbed.configured('market.yml', 'history', { asset, status: points.length ? points.slice(-10).reverse().map((point) => `<t:${Math.floor(new Date(point.observedAt).getTime() / 1000)}:d> — **${money(point.estimatedMarketValue)}**`).join('\n') : 'No authoritative valuation history is available.' }); }
  static platformUpdate(input: { title: string; body: string }) { return SliceEmbed.configured('market.yml', 'list', { reason: input.title.slice(0, 120), status: input.body.slice(0, 1500) }); }
  static marketSummary(input: { gainers: MarketAsset[]; losers: MarketAsset[]; active: MarketAsset[] }) { const names = (items: MarketAsset[]) => items.slice(0, 3).map((asset) => asset.title).join(', ') || 'Unavailable'; return SliceEmbed.configured('market.yml', 'summary', { reason: `Reported gainers: **${names(input.gainers)}**\nReported decliners: **${names(input.losers)}**\nReported activity: **${names(input.active)}**` }); }
}
