import { sanitizeTicketText } from './tickets.js';
export type ModerationAction = 'WARN'|'NOTE'|'TIMEOUT'|'UNTIMEOUT'|'KICK'|'BAN'|'UNBAN'|'MESSAGE_DELETE'|'AUTOMOD_BLOCK'|'SCAM_BLOCK'; export type ModerationSource = 'MANUAL'|'AUTOMOD'|'ANTI_SCAM'|'SYSTEM'; export type ModerationSeverity = 'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';
export type ModerationCase = { guildId:string; caseNumber:number; targetDiscordUserId:string; moderatorDiscordUserId?:string; action:ModerationAction; source:ModerationSource; status:'PENDING'|'ENFORCED'|'FAILED'|'REVERSED'; reason:string; expiresAt?:Date; relatedMessageId?:string; relatedChannelId?:string; evidenceExcerpt?:string };
export interface ModerationRepository { create(input: Omit<ModerationCase,'caseNumber'|'status'>):Promise<ModerationCase>; mark(id: Pick<ModerationCase,'guildId'|'caseNumber'>, status: ModerationCase['status']):Promise<void>; }
export interface ModerationTransport { enforce(caseRecord: ModerationCase):Promise<void>; log(caseRecord: ModerationCase):Promise<void>; }
export class ModerationService { constructor(private readonly repo:ModerationRepository,private readonly transport:ModerationTransport){} async enforce(input:Omit<ModerationCase,'caseNumber'|'status'|'reason'|'evidenceExcerpt'> & {reason:string;evidenceExcerpt?:string}) { if(!input.guildId||!input.targetDiscordUserId||input.reason.trim().length<3) throw new Error('Moderation reason is required.'); const record=await this.repo.create({...input,reason:sanitizeTicketText(input.reason).slice(0,500),evidenceExcerpt:input.evidenceExcerpt?sanitizeTicketText(input.evidenceExcerpt).slice(0,500):undefined}); try { await this.transport.enforce(record); await this.repo.mark(record,'ENFORCED'); const enforced={...record,status:'ENFORCED' as const}; await this.transport.log(enforced).catch(()=>undefined); return enforced; } catch { await this.repo.mark(record,'FAILED'); return {...record,status:'FAILED' as const}; } } }
export type ManualAction='WARN'|'NOTE'|'TIMEOUT'|'UNTIMEOUT'|'BAN'|'UNBAN'; export type ModerationActor={id:string;staff:boolean;admin:boolean;position:number}; export type ModerationTarget={id:string;position:number;protected:boolean;bot:boolean}; export interface ModerationAuthorization { authorize(guildId:string,actor:ModerationActor,target:ModerationTarget,action:ManualAction):Promise<void> }
export class ManualModerationService { constructor(private readonly service:ModerationService,private readonly repository:ModerationRepository & {get(guildId:string,caseNumber:number):Promise<ModerationCase|null>;history(guildId:string,target:string,take?:number):Promise<ModerationCase[]>},private readonly authorization:ModerationAuthorization) {} private async action(action:ManualAction,guildId:string,actor:ModerationActor,target:ModerationTarget,reason:string,expiresAt?:Date){await this.authorization.authorize(guildId,actor,target,action);return this.service.enforce({guildId,targetDiscordUserId:target.id,moderatorDiscordUserId:actor.id,action,source:'MANUAL',reason,expiresAt});} async warn(g:string,a:ModerationActor,t:ModerationTarget,r:string){return this.action('WARN',g,a,t,r)} async note(g:string,a:ModerationActor,t:ModerationTarget,r:string){return this.action('NOTE',g,a,t,r)} async timeout(g:string,a:ModerationActor,t:ModerationTarget,r:string,expiresAt:Date){if(expiresAt<=new Date())throw new Error('Invalid timeout duration.');return this.action('TIMEOUT',g,a,t,r,expiresAt)} async untimeout(g:string,a:ModerationActor,t:ModerationTarget,r:string){return this.action('UNTIMEOUT',g,a,t,r)} async ban(g:string,a:ModerationActor,t:ModerationTarget,r:string){return this.action('BAN',g,a,t,r)} async unban(g:string,a:ModerationActor,t:ModerationTarget,r:string){return this.action('UNBAN',g,a,t,r)} async getCase(g:string,n:number){return this.repository.get(g,n)} async getHistory(g:string,t:string){return this.repository.history(g,t,10)} }
export class DiscordModerationAuthorization implements ModerationAuthorization { async authorize(guildId:string,actor:ModerationActor,target:ModerationTarget,action:ManualAction):Promise<void>{if(!guildId||!actor.staff)throw new Error('Staff authorization required.');if(action!=='NOTE'&&(actor.id===target.id||target.bot||target.protected||(!actor.admin&&target.position>=actor.position)))throw new Error('Target is protected.');} }
export function evaluateAutomod(message:{content:string;mentions:number;recent:number;duplicates:number;staff:boolean}, policy={maxMentions:8,maxMessages:6,duplicateLimit:3}):{action?:ModerationAction;severity:ModerationSeverity;reason?:string;excerpt?:string} { const text=message.content.toLowerCase(); const scam=/(seed phrase|private key|discord token|verify.*login|free nitro|crypto giveaway)/.test(text); if(scam) return {action:'SCAM_BLOCK',severity:'CRITICAL',reason:'High-confidence scam pattern',excerpt:sanitizeTicketText(message.content)}; if(/discord\.gg\//.test(text)&&!message.staff) return {action:'AUTOMOD_BLOCK',severity:'MEDIUM',reason:'Unapproved invite link',excerpt:sanitizeTicketText(message.content)}; if(message.mentions>policy.maxMentions||message.recent>policy.maxMessages||message.duplicates>=policy.duplicateLimit) return {action:'AUTOMOD_BLOCK',severity:'MEDIUM',reason:'Spam policy',excerpt:sanitizeTicketText(message.content)}; return {severity:'LOW'}; }
