import { ActionRowBuilder, ButtonBuilder, ButtonStyle, type ButtonInteraction, type ChatInputCommandInteraction } from 'discord.js';
import { parseWeekdays, scheduleLabel, validateTiming, type PayloadMode, type ScheduleTiming } from './announcement-schedule.js';
import { canManageEmbeds, validateEmbed } from './embed-builder.js';
import { publishableChannel } from './embed-publication.js';
import { SliceEmbed } from './embeds/slice-embed.js';
import { DiscordPaginator } from './paginator.js';
import type { PrismaEmbedRepository } from './persistence/embed-repository.js';
import type { AnnouncementSchedule, CreateSchedule, PrismaAnnouncementScheduleRepository } from './persistence/announcement-schedule-repository.js';

export type ScheduleCreateSession = { actorId: string; guildId: string; input: CreateSchedule; expiresAt: number };
export type ScheduleRunConfirmation = { actorId: string; guildId: string; scheduleId: string; expiresAt: number };
export type ScheduleSessions = Map<string, ScheduleCreateSession | ScheduleRunConfirmation>;

export async function handleScheduleCommand(interaction: ChatInputCommandInteraction, schedules: PrismaAnnouncementScheduleRepository, embeds: PrismaEmbedRepository, sessions: ScheduleSessions, paginator: DiscordPaginator): Promise<void> {
  if (!canManageEmbeds(interaction) || !interaction.guildId || !interaction.guild) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Schedule management required', 'Only staff with Manage Server can manage announcements.')] });
  const sub = interaction.options.getSubcommand();
  if (sub === 'timezone') { const timezone = interaction.options.getString('timezone'); if (!timezone) { const current = await schedules.guildTimezone(interaction.guildId); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.info('Scheduler timezone', current ? `Guild default: **${current}**.` : 'No guild default is configured; provide an IANA timezone to set one.')] }); } if (!validateTiming({ type: 'DAILY', timezone, localTime: '09:00' }).length) { await schedules.setGuildTimezone(interaction.guildId, timezone); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.success('Scheduler timezone saved', `Future schedule forms can use **${timezone}**.`)] }); } return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Invalid timezone', 'Use an IANA timezone such as America/New_York.')] }); }
  if (sub === 'create') {
    const draft = await embeds.get(interaction.options.getString('draft', true), interaction.guildId); if (!draft) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Draft unavailable', 'Choose a current Embed Builder draft from this guild.')] });
    const mode = (interaction.options.getString('mode') ?? 'SNAPSHOT') as PayloadMode; const type = interaction.options.getString('type', true) as ScheduleTiming['type']; const timezone = interaction.options.getString('timezone') ?? await schedules.guildTimezone(interaction.guildId);
    if (!timezone) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Timezone required', 'Provide an IANA timezone or set the guild default with `/schedule timezone`.')] });
    const timing: ScheduleTiming = { type, timezone, localTime: interaction.options.getString('time', true), date: interaction.options.getString('date') ?? undefined, weekdays: parseWeekdays(interaction.options.getString('weekdays')), dayOfMonth: interaction.options.getInteger('day') ?? undefined };
    const timingErrors = validateTiming(timing); const payloadErrors = validateEmbed(draft.payload, draft.buttons); if (timingErrors.length || payloadErrors.length) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Schedule needs attention', timingErrors[0] ?? payloadErrors[0]!)] });
    const targetId = interaction.options.getChannel('channel')?.id ?? draft.targetChannelId ?? interaction.channelId; const channel = await publishableChannel(interaction.guild, targetId); if (!channel) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Target unavailable', 'Choose a text channel where the bot can view, send messages, and embed links.')] });
    const input: CreateSchedule = { guildId: interaction.guildId, draftId: draft.id, actorId: interaction.user.id, name: interaction.options.getString('name', true), timing, payloadMode: mode, ...(mode === 'SNAPSHOT' ? { payloadSnapshot: draft.payload, linkButtonsSnapshot: draft.buttons } : {}), targetChannelId: channel.id };
    const key = crypto.randomUUID().slice(0, 12); sessions.set(key, { actorId: interaction.user.id, guildId: interaction.guildId, input, expiresAt: Date.now() + 10 * 60_000 });
    return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.info('Confirm scheduled announcement', `**${input.name}**\n${scheduleLabel(timing)}\nTarget: <#${channel.id}>\nContent: ${mode === 'SNAPSHOT' ? `Snapshot of draft revision ${draft.version}` : 'Latest saved draft at publish time'}`)], components: [confirmationRow(key)] });
  }
  if (sub === 'list') { const filter = interaction.options.getString('status') ?? 'ACTIVE'; const status = filter === 'ACTIVE' ? 'SCHEDULED' : filter; const rows = await schedules.list(interaction.guildId, status); const pages = chunk(rows, 6).map((page) => SliceEmbed.info(`Announcement schedules · ${filter}`, page.map((row) => `\`${row.id.slice(0, 8)}\` · **${row.name}** · ${row.status}\n${scheduleLabel(timingOf(row))}\n<#${row.targetChannelId}>`).join('\n\n'))); return void await interaction.reply({ ephemeral: true, ...(paginator.create(interaction.user.id, pages.length ? pages : [SliceEmbed.info('Announcement schedules', 'No matching schedules.')])) }); }
  const id = interaction.options.getString('schedule', true);
  const schedule = await schedules.get(id, interaction.guildId); if (!schedule) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Schedule unavailable', 'That schedule does not belong to this guild.')] });
  if (sub === 'view') return void await interaction.reply({ ephemeral: true, embeds: [scheduleEmbed(schedule)], components: [scheduleControls(schedule)] });
  if (sub === 'history') { const history = await schedules.history(schedule.id, interaction.guildId); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.info(`Run history · ${schedule.name}`, history.length ? history.map((run) => `${run.status} · <t:${Math.floor(run.scheduledFor.getTime() / 1000)}:f>${run.errorCode ? ` · ${run.errorCode}` : ''}`).join('\n') : 'No runs yet.')] }); }
  if (sub === 'edit') {
    const name = interaction.options.getString('name') ?? undefined; const target = interaction.options.getChannel('channel'); const mode = interaction.options.getString('mode') as PayloadMode | null; const requestedType = interaction.options.getString('type') as ScheduleTiming['type'] | null; const timingRequested = Boolean(requestedType || interaction.options.getString('time') || interaction.options.getString('timezone') || interaction.options.getString('date') || interaction.options.getString('weekdays') || interaction.options.getInteger('day'));
    const requestedTiming = timingRequested ? { type: requestedType ?? schedule.scheduleType, localTime: interaction.options.getString('time') ?? schedule.localTime, timezone: interaction.options.getString('timezone') ?? schedule.timezone, date: interaction.options.getString('date') ?? schedule.date ?? undefined, weekdays: interaction.options.getString('weekdays') ? parseWeekdays(interaction.options.getString('weekdays')) : schedule.weekdays, dayOfMonth: interaction.options.getInteger('day') ?? schedule.dayOfMonth ?? undefined } satisfies ScheduleTiming : undefined;
    if (!name && !target && !mode && !requestedTiming) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.warning('Nothing changed', 'Provide a name, target, mode, or complete timing change.')] });
    if (requestedTiming && validateTiming(requestedTiming).length) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Invalid timing', validateTiming(requestedTiming)[0]!)] });
    if (target && !(await publishableChannel(interaction.guild, target.id))) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Target unavailable', 'The bot needs View Channel, Send Messages, and Embed Links.')] });
    let snapshot: { payloadSnapshot?: CreateSchedule['payloadSnapshot']; linkButtonsSnapshot?: CreateSchedule['linkButtonsSnapshot'] } = {};
    if (mode === 'SNAPSHOT') { const draft = await embeds.get(schedule.draftId ?? '', interaction.guildId); if (!draft || validateEmbed(draft.payload, draft.buttons).length) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Draft unavailable', 'A valid current draft is required to capture a snapshot.')] }); snapshot = { payloadSnapshot: draft.payload, linkButtonsSnapshot: draft.buttons }; }
    if (mode === 'LIVE_DRAFT' && !(await embeds.get(schedule.draftId ?? '', interaction.guildId))) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Draft unavailable', 'A current draft is required for live-draft publishing.')] });
    const updated = await schedules.update(schedule.id, interaction.guildId, interaction.user.id, schedule.version, { name, targetChannelId: target?.id, payloadMode: mode ?? undefined, timing: requestedTiming, ...snapshot });
    return void await interaction.reply({ ephemeral: true, embeds: [updated ? SliceEmbed.success('Schedule updated', scheduleSummary(updated)) : SliceEmbed.warning('Schedule changed', 'Reload it before editing.')] });
  }
  const action = sub === 'pause' ? 'pause' : sub === 'resume' ? 'resume' : sub === 'cancel' ? 'cancel' : sub === 'retry' ? 'retry' : 'run'; if (action === 'run') return void await openRunConfirmation(interaction, sessions, schedule); return void await performScheduleAction(interaction, schedules, schedule, action);
}

export async function handleScheduleButton(interaction: ButtonInteraction, schedules: PrismaAnnouncementScheduleRepository, sessions: ScheduleSessions): Promise<void> {
  const [, , key, action] = interaction.customId.split(':'); if (!key || !action) return;
  if (key === 'create') { const sessionKey = action; const decision = interaction.customId.split(':')[4]; const session = sessions.get(sessionKey); if (!session || !('input' in session) || session.actorId !== interaction.user.id || session.guildId !== interaction.guildId || session.expiresAt < Date.now() || !canManageEmbeds(interaction)) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Confirmation expired', 'Start the schedule again from the command or builder.')] }); sessions.delete(sessionKey); if (decision !== 'confirm') return void await interaction.update({ embeds: [SliceEmbed.info('Schedule cancelled', 'No announcement was scheduled.')], components: [] }); try { const created = await schedules.create(session.input); return void await interaction.update({ embeds: [SliceEmbed.success('Announcement scheduled', scheduleSummary(created))], components: [] }); } catch { return void await interaction.update({ embeds: [SliceEmbed.error('Schedule unavailable', 'The timing could not be saved. Please try again.')], components: [] }); } }
  if (key === 'run-confirm') { const sessionKey = action; const decision = interaction.customId.split(':')[4]; const session = sessions.get(sessionKey); if (!session || !('scheduleId' in session) || session.actorId !== interaction.user.id || session.guildId !== interaction.guildId || session.expiresAt < Date.now() || !canManageEmbeds(interaction)) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Confirmation expired', 'Open the schedule and request Run Now again.')] }); sessions.delete(sessionKey); if (decision !== 'confirm') return void await interaction.update({ embeds: [SliceEmbed.info('Manual run cancelled', 'No announcement was queued.')], components: [] }); const schedule = await schedules.get(session.scheduleId, session.guildId); if (!schedule) return void await interaction.update({ embeds: [SliceEmbed.error('Schedule unavailable', 'The schedule no longer belongs to this guild.')], components: [] }); const queued = await schedules.runNow(schedule.id, schedule.guildId, interaction.user.id, schedule.version); return void await interaction.update({ embeds: [queued ? SliceEmbed.success('Manual run queued', scheduleSummary(queued)) : SliceEmbed.warning('Schedule changed', 'Reload the schedule before running it.')], components: [] }); }
  if (!canManageEmbeds(interaction) || !interaction.guildId) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Schedule management required', 'Manage Server is required.')] }); const schedule = await schedules.get(key, interaction.guildId); if (!schedule) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Schedule unavailable', 'This schedule is unavailable.')] }); if (action === 'run') return void await openRunConfirmation(interaction, sessions, schedule); return void await performScheduleAction(interaction, schedules, schedule, action);
}

async function openRunConfirmation(interaction: ChatInputCommandInteraction | ButtonInteraction, sessions: ScheduleSessions, schedule: AnnouncementSchedule): Promise<void> { const key = crypto.randomUUID().slice(0, 12); sessions.set(key, { actorId: interaction.user.id, guildId: schedule.guildId, scheduleId: schedule.id, expiresAt: Date.now() + 5 * 60_000 }); const payload = { ephemeral: true, embeds: [SliceEmbed.warning('Confirm immediate announcement', `Queue **${schedule.name}** to run now in <#${schedule.targetChannelId}>? The worker will record and send the currently configured ${schedule.payloadMode === 'SNAPSHOT' ? 'snapshot' : 'live draft'} content.`)], components: [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`slice:schedule:run-confirm:${key}:confirm`).setLabel('Confirm run now').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId(`slice:schedule:run-confirm:${key}:cancel`).setLabel('Cancel').setStyle(ButtonStyle.Secondary))] }; return void await interaction.reply(payload); }

async function performScheduleAction(interaction: ChatInputCommandInteraction | ButtonInteraction, schedules: PrismaAnnouncementScheduleRepository, schedule: AnnouncementSchedule, action: string): Promise<void> {
  const actor = interaction.user.id; const guildId = schedule.guildId; const row = action === 'pause' ? await schedules.pause(schedule.id, guildId, actor, schedule.version) : action === 'resume' ? await schedules.resume(schedule.id, guildId, actor, schedule.version) : action === 'retry' ? await schedules.retry(schedule.id, guildId, actor, schedule.version) : action === 'run' ? await schedules.runNow(schedule.id, guildId, actor, schedule.version) : null;
  if (action === 'cancel') { const cancelled = await schedules.cancel(schedule.id, guildId, actor, schedule.version); return void await response(interaction, cancelled ? SliceEmbed.success('Schedule cancelled', 'The schedule and its run history were preserved.') : SliceEmbed.warning('Schedule changed', 'Reload it before cancelling.')); }
  return void await response(interaction, row ? SliceEmbed.success(action === 'run' ? 'Manual run queued' : 'Schedule updated', scheduleSummary(row)) : SliceEmbed.warning('Schedule changed', 'This action is not currently available.'));
}
async function response(interaction: ChatInputCommandInteraction | ButtonInteraction, embed: ReturnType<typeof SliceEmbed.info>) { if (interaction.isButton()) return interaction.reply({ ephemeral: true, embeds: [embed] }); return interaction.reply({ ephemeral: true, embeds: [embed] }); }
function confirmationRow(key: string) { return new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`slice:schedule:create:${key}:confirm`).setLabel('Confirm schedule').setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId(`slice:schedule:create:${key}:cancel`).setLabel('Cancel').setStyle(ButtonStyle.Secondary)); }
function scheduleControls(schedule: AnnouncementSchedule) { return new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`slice:schedule:${schedule.id}:pause`).setLabel('Pause').setStyle(ButtonStyle.Secondary).setDisabled(schedule.status !== 'SCHEDULED'), new ButtonBuilder().setCustomId(`slice:schedule:${schedule.id}:resume`).setLabel('Resume').setStyle(ButtonStyle.Success).setDisabled(schedule.status !== 'PAUSED'), new ButtonBuilder().setCustomId(`slice:schedule:${schedule.id}:run`).setLabel('Run now').setStyle(ButtonStyle.Primary).setDisabled(!['SCHEDULED', 'PAUSED'].includes(schedule.status)), new ButtonBuilder().setCustomId(`slice:schedule:${schedule.id}:cancel`).setLabel('Cancel').setStyle(ButtonStyle.Danger).setDisabled(['CANCELLED', 'COMPLETED', 'PROCESSING'].includes(schedule.status))); }
function timingOf(schedule: AnnouncementSchedule): ScheduleTiming { return { type: schedule.scheduleType, timezone: schedule.timezone, localTime: schedule.localTime, date: schedule.date ?? undefined, weekdays: schedule.weekdays, dayOfMonth: schedule.dayOfMonth ?? undefined }; }
function scheduleSummary(schedule: AnnouncementSchedule) { return `**${schedule.name}** · ${schedule.status}\n${scheduleLabel(timingOf(schedule))}\nNext: ${schedule.nextRunAt ? `<t:${Math.floor(schedule.nextRunAt.getTime() / 1000)}:f>` : 'None'}\nTarget: <#${schedule.targetChannelId}>\nContent: ${schedule.payloadMode === 'SNAPSHOT' ? 'Snapshot' : 'Live draft'}`; }
function scheduleEmbed(schedule: AnnouncementSchedule) { return SliceEmbed.info(`Schedule · ${schedule.name}`, `Reference: \`${schedule.id}\`\n${scheduleSummary(schedule)}\nCreated by: <@${schedule.createdByDiscordUserId}>`); }
function chunk<T>(items: T[], size: number): T[][] { const pages: T[][] = []; for (let index = 0; index < items.length; index += size) pages.push(items.slice(index, index + size)); return pages; }
