export type BackendFailure = 'UNAUTHORIZED' | 'ACCOUNT_NOT_LINKED' | 'NOT_FOUND' | 'BACKEND_UNAVAILABLE' | 'RATE_LIMITED' | 'INVALID_REQUEST' | 'BACKEND_SEAM_REQUIRED';
export type BackendResult<T> = { ok: true; value: T } | { ok: false; code: BackendFailure; message: string };
export type Money = { minor: string; currency: string };
export type MarketAsset = { publicId: string; slug: string; title: string; shortName?: string | null; year?: number | null; category?: { name: string }; collectibleSet?: { name: string } | null; grading?: { companyCode: string; grade: string; label: string } | null; estimatedMarketValue?: Money | null; change24hBps?: number | null; availabilityBps?: number | null; ownersCount?: number | null; confidence?: number | null; dataStatus?: string; asOf?: string | null };
export type MarketHistory = { assetSlug: string; range: string; points: Array<{ observedAt: string; estimatedMarketValue: Money; source: string; dataStatus: string }> };

/** The only HTTP boundary for Discord market reads; handlers never parse raw backend errors. */
export class SliceBackendClient {
  private readonly cache = new Map<string, { expires: number; value: unknown }>();
  private readonly recent = new Map<string, number>();
  constructor(private readonly options: { baseUrl?: string; serviceToken?: string }) {}
  async searchAssets(query: string): Promise<BackendResult<MarketAsset[]>> { return this.publicRead(`/market/assets?query=${encodeURIComponent(query)}&limit=10`, (value) => object(value).items as MarketAsset[]); }
  async asset(asset: string): Promise<BackendResult<MarketAsset>> { return this.publicRead(`/market/assets/${encodeURIComponent(asset)}`, (value) => value as MarketAsset); }
  async history(asset: string): Promise<BackendResult<MarketHistory>> { return this.publicRead(`/market/assets/${encodeURIComponent(asset)}/history?range=30D`, (value) => value as MarketHistory); }
  async top(kind: 'gainers' | 'losers' | 'active'): Promise<BackendResult<MarketAsset[]>> { return this.publicRead(`/market/movers?kind=${kind}&limit=10`, (value) => object(value).items as MarketAsset[]); }
  async recentSales(): Promise<BackendResult<never[]>> { return { ok: false, code: 'BACKEND_SEAM_REQUIRED', message: 'Recent-sale read delivery is not available to Discord yet.' }; }
  async privateRead<T>(): Promise<BackendResult<T>> { return { ok: false, code: 'BACKEND_SEAM_REQUIRED', message: 'Secure linked-account read endpoints are not available to Discord yet.' }; }
  private async publicRead<T>(path: string, parse: (value: unknown) => T): Promise<BackendResult<T>> { if (!this.options.baseUrl) return { ok: false, code: 'BACKEND_SEAM_REQUIRED', message: 'Slice market read service is not configured for Discord yet.' }; const key = path; const cached = this.cache.get(key); if (cached && cached.expires > Date.now()) return { ok: true, value: cached.value as T }; const now = Date.now(); if ((this.recent.get(key) ?? 0) + 500 > now) return { ok: false, code: 'RATE_LIMITED', message: 'Please retry this market query shortly.' }; this.recent.set(key, now); try { const response = await fetch(new URL(path, this.options.baseUrl), { headers: this.options.serviceToken ? { authorization: `Bearer ${this.options.serviceToken}` } : {} }); if (!response.ok) return failure(response.status); const value = parse(await response.json()); this.cache.set(key, { expires: Date.now() + 30_000, value }); return { ok: true, value }; } catch { return { ok: false, code: 'BACKEND_UNAVAILABLE', message: 'Slice market data is temporarily unavailable.' }; } }
}
function failure(status: number): BackendResult<never> { if (status === 401 || status === 403) return { ok: false, code: 'UNAUTHORIZED', message: 'This Slice read is not authorized.' }; if (status === 404) return { ok: false, code: 'NOT_FOUND', message: 'That Slice asset was not found.' }; if (status === 429) return { ok: false, code: 'RATE_LIMITED', message: 'Slice is rate limiting this request. Try again shortly.' }; if (status >= 400 && status < 500) return { ok: false, code: 'INVALID_REQUEST', message: 'That Slice request is invalid.' }; return { ok: false, code: 'BACKEND_UNAVAILABLE', message: 'Slice market data is temporarily unavailable.' }; }
function object(value: unknown): Record<string, unknown> { return value !== null && typeof value === 'object' ? value as Record<string, unknown> : {}; }
