import { PermissionFlagsBits, type ChatInputCommandInteraction, type Client } from 'discord.js';
import { publishEmbed } from './embed-publication.js';
import { SliceEmbed } from './embeds/slice-embed.js';
import type { EmbedPayload } from './embed-builder.js';
import type { PrismaEmbedRepository } from './persistence/embed-repository.js';
import { PrismaSpotlightRepository, type Spotlight } from './persistence/spotlight-repository.js';
import { SliceBackendClient, type MarketAsset, type PublicCollector } from './slice-backend-client.js';

const COOLDOWN_DAYS = 14;

export async function handleSpotlightCommand(interaction: ChatInputCommandInteraction, repository: PrismaSpotlightRepository, backend: SliceBackendClient, embeds: PrismaEmbedRepository, client: Client): Promise<void> {
  if (!interaction.guildId || !interaction.guild) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Spotlight unavailable', 'Spotlights are available only inside a Slice server.')] });
  const sub = interaction.options.getSubcommand(); const manager = interaction.memberPermissions?.has(PermissionFlagsBits.ManageGuild) === true;
  if ((sub === 'collectible' || !['collector', 'view'].includes(sub)) && !manager) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Spotlight management required', 'Manage Server is required for this Spotlight action.')] });
  if (sub === 'collector' || sub === 'collectible') return void await create(interaction, repository, backend, sub === 'collector' ? 'COLLECTOR' : 'COLLECTIBLE');
  if (sub === 'list') { const rows = await repository.list(interaction.guildId); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.info('Spotlight requests', rows.length ? rows.map(summary).join('\n\n') : 'No Spotlight requests yet.')] }); }
  const id = interaction.options.getString('id', true); const row = await repository.get(id, interaction.guildId); if (!row) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Spotlight unavailable', 'That request is not in this server.')] });
  if (sub === 'view') { if (!manager && row.requesterDiscordUserId !== interaction.user.id) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Spotlight unavailable', 'Only the requester or staff can view this request.')] }); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.info(`Spotlight · ${row.kind}`, `${summary(row)}\n\nLocked source fields are refreshed from Slice before publication.`)] }); }
  if (sub === 'edit') { const title = editorial(interaction.options.getString('title'), 160); const copy = editorial(interaction.options.getString('copy'), 1_500); if (title === undefined && copy === undefined) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.warning('Nothing changed', 'Provide an editorial title or copy. Source fields are locked.')] }); const updated = await repository.edit(row.id, row.guildId, interaction.user.id, row.revision, { title, copy }); return void await interaction.reply({ ephemeral: true, embeds: [updated ? SliceEmbed.success('Spotlight editorial updated', 'Only editorial fields changed; the public source remains locked.') : SliceEmbed.warning('Spotlight changed', 'Reload the request before editing.')] }); }
  if (sub === 'approve') { const updated = await repository.approve(row.id, row.guildId, interaction.user.id, row.revision); return void await interaction.reply({ ephemeral: true, embeds: [updated ? SliceEmbed.success('Spotlight approved', 'The source will be refreshed again before publication.') : SliceEmbed.warning('Spotlight unavailable', 'Only a pending request can be approved.')] }); }
  if (sub === 'cancel') { const updated = await repository.cancel(row.id, row.guildId, interaction.user.id, row.revision); return void await interaction.reply({ ephemeral: true, embeds: [updated ? SliceEmbed.success('Spotlight cancelled', 'The audit history was retained.') : SliceEmbed.warning('Spotlight unavailable', 'This request cannot be cancelled now.')] }); }
  if (row.status !== 'APPROVED') return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.warning('Spotlight approval required', 'Approve this request before preparing or publishing it.')] });
  if (await repository.cooldown(row.guildId, row.kind, row.sourceSlug, COOLDOWN_DAYS)) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.warning('Spotlight cooldown active', `This ${row.kind === 'COLLECTOR' ? 'Collector' : 'collectible'} was featured in the last ${COOLDOWN_DAYS} days.`)] });
  const refreshed = await refresh(row, backend); if (!refreshed.ok) { await repository.block(row.id, row.guildId, interaction.user.id, row.revision, refreshed.message); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Spotlight blocked', refreshed.message)] }); }
  const current = await repository.refresh(row.id, row.guildId, interaction.user.id, row.revision, refreshed.payload); if (!current) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.warning('Spotlight changed', 'Reload the request before publishing.')] });
  const draft = await embeds.create(current.guildId, interaction.user.id, `Spotlight · ${current.sourceSlug}`, refreshed.payload, refreshed.buttons);
  if (sub === 'schedule') { const attached = await repository.attachDraft(current.id, current.guildId, interaction.user.id, current.revision, draft.id); return void await interaction.reply({ ephemeral: true, embeds: [attached ? SliceEmbed.success('Spotlight ready to schedule', `Draft ID: ${draft.id}. It contains refreshed public data; use /schedule create with this draft in Snapshot mode.`) : SliceEmbed.warning('Spotlight changed', 'The generated draft is safe, but reload before scheduling.')] }); }
  const channelId = interaction.options.getChannel('channel', true).id; const saved = await embeds.save(draft.id, current.guildId, interaction.user.id, draft.version, { payload: refreshed.payload, buttons: refreshed.buttons, targetChannelId: channelId }); if (!saved) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Spotlight unavailable', 'The refreshed draft could not be prepared.')] });
  try { await publishEmbed({ client, guildId: current.guildId, draft: saved, actorId: interaction.user.id, channelId, payload: saved.payload, buttons: saved.buttons, repository: embeds }); const published = await repository.published(current.id, current.guildId, interaction.user.id, current.revision, saved.id, channelId); return void await interaction.reply({ ephemeral: true, embeds: [published ? SliceEmbed.success('Spotlight published', `Public-data checks passed and the feature was posted in <#${channelId}>.`) : SliceEmbed.warning('Publication receipt needs review', 'Discord publication was recorded, but the Spotlight state changed before its receipt was saved.')] }); } catch { await repository.block(current.id, current.guildId, interaction.user.id, current.revision, 'The public target channel is unavailable or Discord did not confirm publication.'); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Spotlight publication failed', 'No Spotlight was marked published. Check the target channel and retry after review.')] }); }
}

async function create(interaction: ChatInputCommandInteraction, repository: PrismaSpotlightRepository, backend: SliceBackendClient, kind: 'COLLECTOR' | 'COLLECTIBLE') { const sourceSlug = interaction.options.getString(kind === 'COLLECTOR' ? 'collector' : 'asset', true).trim(); const source = await sourceFor(kind, sourceSlug, backend); if (!source.ok) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Spotlight unavailable', source.message)] }); if (kind === 'COLLECTOR' && source.owner !== interaction.user.id) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.error('Collector approval required', 'Connect the Discord account that owns this public Collector profile before requesting a Spotlight.')] }); if (await repository.cooldown(interaction.guildId!, kind, sourceSlug, COOLDOWN_DAYS)) return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.warning('Spotlight cooldown active', `This source was featured in the last ${COOLDOWN_DAYS} days.`)] }); const row = await repository.create({ guildId: interaction.guildId!, kind, sourceSlug, requesterDiscordUserId: interaction.user.id, editorialTitle: editorial(interaction.options.getString('title'), 160) ?? null, editorialCopy: editorial(interaction.options.getString('copy'), 1_500) ?? null, sourceSnapshot: source.payload }); return void await interaction.reply({ ephemeral: true, embeds: [SliceEmbed.success('Spotlight request recorded', `${summary(row)}\n\n${kind === 'COLLECTOR' ? 'Your linked public profile ownership was verified. ' : ''}A staff member must approve it before publication.`)] }); }

async function refresh(row: Spotlight, backend: SliceBackendClient) { const source = await sourceFor(row.kind, row.sourceSlug, backend); if (!source.ok) return { ok: false as const, message: source.message }; return { ok: true as const, payload: withEditorial(source.payload, row), buttons: source.buttons }; }
async function sourceFor(kind: 'COLLECTOR' | 'COLLECTIBLE', slug: string, backend: SliceBackendClient): Promise<{ ok: true; payload: EmbedPayload; buttons: Array<{ label: string; url: string }>; owner?: string } | { ok: false; message: string }> { if (kind === 'COLLECTOR') { const eligibility = await backend.collectorSpotlightEligibility(slug); if (!eligibility.ok || !eligibility.value.eligible || !eligibility.value.isPublic || !eligibility.value.collector || !eligibility.value.linkedDiscordUserId) return { ok: false, message: 'This Collector is no longer public or does not have a linked Discord identity.' }; const collector = eligibility.value.collector; const publicCollector = await backend.collector(slug); const listings = publicCollector.ok ? publicCollector.value.publishedListings.slice(0, 3).map((item) => item.title).join(', ') : ''; return { ok: true, owner: eligibility.value.linkedDiscordUserId, payload: collectorPayload(collector, listings), buttons: [{ label: 'View Collector', url: `https://slice.ai/collectors/${encodeURIComponent(slug)}` }] }; } const asset = await backend.asset(slug); if (!asset.ok) return { ok: false, message: 'This collectible is not currently available as a public Slice asset.' }; return { ok: true, payload: assetPayload(asset.value), buttons: [{ label: 'View Collectible', url: `https://slice.ai/market/${encodeURIComponent(asset.value.slug)}` }] }; }
function collectorPayload(collector: Omit<PublicCollector, 'publishedListings'>, listings: string): EmbedPayload { return { title: `Collector Spotlight · ${collector.displayName ?? collector.slug}`, description: [collector.headline, collector.specialism ? `**Specialism:** ${collector.specialism}` : null, `**Public listings:** ${collector.publishedListingCount}`, listings ? `**Featured listings:** ${listings}` : null].filter(Boolean).join('\n\n'), timestamp: true }; }
function assetPayload(asset: MarketAsset): EmbedPayload { return { title: `Featured Collectible · ${asset.title}`, description: [asset.category?.name ? `**Category:** ${asset.category.name}` : null, asset.collectibleSet?.name ? `**Set:** ${asset.collectibleSet.name}` : null, asset.grading?.label ? `**Grade:** ${asset.grading.label}` : null, asset.estimatedMarketValue ? `**Estimated market value:** ${asset.estimatedMarketValue.currency} ${(Number(asset.estimatedMarketValue.minor) / 100).toLocaleString()}` : null].filter(Boolean).join('\n'), timestamp: true }; }
function withEditorial(payload: EmbedPayload, row: Spotlight): EmbedPayload { return { ...payload, ...(row.editorialTitle ? { title: row.editorialTitle } : {}), description: [row.editorialCopy, payload.description].filter(Boolean).join('\n\n') }; }
function editorial(value: string | null, limit: number): string | undefined { if (value === null) return undefined; const clean = value.replace(/@(everyone|here)/gi, '@​$1').replace(/<@!?&?\d+>/g, '[mention removed]').trim().slice(0, limit); return clean || null as never; }
function summary(row: Spotlight) { return `${row.id.slice(0, 8)} · **${row.kind}** · ${row.status}\nSource: ${row.sourceSlug}${row.blockedReason ? `\nBlocked: ${row.blockedReason}` : ''}`; }
