import { createHash, randomUUID } from 'node:crypto';
import { TICKET_CATEGORIES, sanitizeTicketText, staffRolesForCategory, type TicketPriority } from './tickets.js';
export type TicketInput = { guildId: string; creatorDiscordId: string; category: string; subject: string; description: string; referenceId?: string; requestedUrgency?: string };
export type CreatedTicket = { id: string; guildId: string; channelId: string; channelName: string; category: string; subject: string; safeSummary: string; priority: TicketPriority; createdAt: Date };
export type PermissionEntry = { id: string; allow?: readonly string[]; deny?: readonly string[] };
export interface TicketChannel { id: string; name: string; sendOpening(ticket: CreatedTicket): Promise<void>; delete(reason: string): Promise<void>; }
export interface TicketDiscordBoundary { createPrivateChannel(input: { name: string; creatorId: string; permissions: PermissionEntry[] }): Promise<TicketChannel>; }
export interface TicketRepository { findActive(guildId: string, creatorDiscordId: string): Promise<CreatedTicket[]>; create(ticket: CreatedTicket & { creatorDiscordId: string; referenceId?: string }): Promise<void>; delete(ticketId: string): Promise<void>; }
export interface TicketRoleResolver { getRoleId(guildId: string, logicalKey: string): Promise<string | null>; }
export class TicketCreationError extends Error {}
export class TicketCreationService {
  constructor(private readonly repository: TicketRepository, private readonly discord: TicketDiscordBoundary, private readonly roles: TicketRoleResolver, private readonly maxActive = 3) {}
  async create(input: TicketInput): Promise<CreatedTicket> {
    validate(input); const existing = await this.repository.findActive(input.guildId, input.creatorDiscordId); const same = existing.find((ticket) => ticket.category === input.category); if (same) throw new TicketCreationError(`An active ticket for this category already exists: <#${same.channelId}>`); if (existing.length >= this.maxActive) throw new TicketCreationError(`You already have the maximum of ${this.maxActive} active tickets.`);
    const id = randomUUID(); const ticket: CreatedTicket & { creatorDiscordId: string; referenceId?: string } = { id, guildId: input.guildId, channelId: '', channelName: `ticket-${id.replace(/-/g, '').slice(0, 6)}`, category: input.category, subject: sanitizeTicketText(input.subject), safeSummary: sanitizeTicketText(input.description), priority: priority(input.requestedUrgency), createdAt: new Date(), creatorDiscordId: input.creatorDiscordId, referenceId: input.referenceId ? sanitizeTicketText(input.referenceId) : undefined };
    const channel = await this.discord.createPrivateChannel({ name: ticket.channelName, creatorId: input.creatorDiscordId, permissions: await permissionMatrix(input.guildId, input.creatorDiscordId, input.category, this.roles) }); ticket.channelId = channel.id;
    try { await this.repository.create(ticket); } catch (error) { await channel.delete('Slice AI ticket persistence failed'); throw error; }
    try { await channel.sendOpening(ticket); } catch (error) { await this.repository.delete(ticket.id); await channel.delete('Slice AI ticket opening message failed'); throw error; }
    return ticket;
  }
}
export async function permissionMatrix(guildId: string, creatorId: string, category: string, roles: TicketRoleResolver): Promise<PermissionEntry[]> { const entries: PermissionEntry[] = [{ id: 'everyone', deny: ['ViewChannel'] }, { id: creatorId, allow: ['ViewChannel', 'SendMessages', 'ReadMessageHistory', 'AttachFiles'] }]; for (const key of staffRolesForCategory(category)) { const id = await roles.getRoleId(guildId, key); if (id) entries.push({ id, allow: ['ViewChannel', 'SendMessages', 'ReadMessageHistory', 'ManageMessages'] }); } return entries; }
function validate(input: TicketInput): void { if (!TICKET_CATEGORIES.includes(input.category as (typeof TICKET_CATEGORIES)[number])) throw new TicketCreationError('Invalid ticket category.'); if (!input.subject.trim() || input.subject.length > 120) throw new TicketCreationError('Subject must be between 1 and 120 characters.'); if (!input.description.trim() || input.description.length > 1800) throw new TicketCreationError('Description must be between 1 and 1800 characters.'); if (input.referenceId && input.referenceId.length > 120) throw new TicketCreationError('Reference ID is too long.'); if (input.requestedUrgency && !['LOW', 'NORMAL', 'HIGH', 'URGENT'].includes(input.requestedUrgency.toUpperCase())) throw new TicketCreationError('Invalid requested urgency.'); }
function priority(value?: string): TicketPriority { return value?.toUpperCase() === 'URGENT' ? 'HIGH' : value?.toUpperCase() === 'HIGH' ? 'NORMAL' : 'NORMAL'; }
export function ticketChecksum(ticket: CreatedTicket): string { return createHash('sha256').update(`${ticket.id}:${ticket.channelId}:${ticket.createdAt.toISOString()}`).digest('hex'); }
export class InMemoryTicketRepository implements TicketRepository { readonly tickets = new Map<string, CreatedTicket & { creatorDiscordId: string; referenceId?: string }>(); events: string[] = []; async findActive(guildId: string, creatorDiscordId: string): Promise<CreatedTicket[]> { return [...this.tickets.values()].filter((ticket) => ticket.guildId === guildId && ticket.creatorDiscordId === creatorDiscordId); } async create(ticket: CreatedTicket & { creatorDiscordId: string; referenceId?: string }): Promise<void> { this.tickets.set(ticket.id, ticket); this.events.push(`CREATED:${ticket.id}`); } async delete(ticketId: string): Promise<void> { this.tickets.delete(ticketId); this.events = this.events.filter((event) => event !== `CREATED:${ticketId}`); } }
