import { Client, Events, GatewayIntentBits } from 'discord.js';
import { createServer } from 'node:http';
import { PrismaClient } from '../generated/prisma/index.js';
import { loadConfig } from './config.js';
import { Logger } from './logger.js';
import { SliceEmbed } from './embeds/slice-embed.js';
import { PrismaTicketRepository } from './persistence/ticket-repository.js';
import { PrismaAdvancedTicketRepository } from './persistence/advanced-ticket-repository.js';
import { TicketInactivityService } from './ticket-inactivity.js';
import { TicketSlaService, type SlaTicket } from './ticket-sla.js';
import { TicketLifecycleService } from './ticket-lifecycle.js';
import { StaffTicketTranscriptService, TicketTranscriptService, type TicketHistory } from './ticket-transcripts.js';
import { PrismaCommunityRepository } from './persistence/community-repository.js';
import { PrismaSetupRepository } from './persistence/setup-repository.js';
import { pollPayload } from './commands/community.js';
import { PrismaDiscordDeliveryRepository } from './persistence/discord-delivery-repository.js';
import { DiscordDeliveryWorker } from './discord-delivery-worker.js';
import { SliceBackendClient } from './slice-backend-client.js';
import { SliceCustomerRouteBuilder } from './customer-routes.js';
import { lockTicketChannel, refreshTicketHeader } from './ticket-discord.js';
import { PrismaGiveawayRepository } from './persistence/giveaway-repository.js';
import { processDueGiveaways } from './giveaway-worker.js';
import { publishGiveawayCompletion } from './commands/giveaway.js';
import { PrismaMemeCompetitionRepository } from './persistence/meme-competition-repository.js';
import { MEME_COMPETITION_SYSTEM_ACTOR, processDueMemeCompetitions, publishMemeOpening, publishMemeResult, resolveMemeCompetition } from './meme-competition-worker.js';
import { WEEKLY_MEME_DURATION_MS } from './meme-competition.js';
import { runCommunityJob } from './community-scheduler.js';
import { MarketDigestWorker } from './market-digest-worker.js';
import { PriceAlertWorker } from './price-alert-worker.js';
import { SafeNewsFeedClient } from './news-feed.js';
import { PrismaNewsRepository } from './persistence/news-repository.js';
import { NewsFeedWorker } from './news-feed-worker.js';
import { PrismaEmbedRepository } from './persistence/embed-repository.js';
import { PrismaAnnouncementScheduleRepository } from './persistence/announcement-schedule-repository.js';
import { AnnouncementSchedulerWorker } from './announcement-scheduler-worker.js';
import { DiscordAnalyticsService } from './analytics.js';

const config = loadConfig(); const logger = new Logger(); const prisma = new PrismaClient({ datasources: { db: { url: config.DATABASE_URL } } }); const tickets = new PrismaTicketRepository(prisma); const advancedTickets = new PrismaAdvancedTicketRepository(prisma); const analytics = new DiscordAnalyticsService(prisma); const workerInstanceId = crypto.randomUUID(); const lifecycle = new TicketLifecycleService(tickets); const transcripts = new TicketTranscriptService(tickets); const staffTranscripts = new StaffTicketTranscriptService(tickets); const community = new PrismaCommunityRepository(prisma); const giveaways = new PrismaGiveawayRepository(prisma); const memes = new PrismaMemeCompetitionRepository(prisma); const setup = new PrismaSetupRepository(prisma); const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent] }); const backend = new SliceBackendClient({ baseUrl: config.SLICE_API_BASE_URL, serviceToken: config.SLICE_BOT_SERVICE_TOKEN }); const routes = new SliceCustomerRouteBuilder(config.SLICE_WEB_BASE_URL); const discordDeliveries = new PrismaDiscordDeliveryRepository(prisma); const deliveryWorker = new DiscordDeliveryWorker(backend, discordDeliveries, setup, client, routes, (event, fields) => logger.warn(event, fields)); const marketDigestWorker = new MarketDigestWorker(backend, discordDeliveries, setup, client, routes, config, (event, fields) => logger.warn(event, fields)); const priceAlertWorker = new PriceAlertWorker(backend, discordDeliveries, client, routes, config, (event, fields) => logger.warn(event, fields)); const newsFeedWorker = new NewsFeedWorker(new SafeNewsFeedClient(), new PrismaNewsRepository(prisma), setup, client, config, (event, fields) => logger.warn(event, fields)); const announcementScheduler = new AnnouncementSchedulerWorker(client, new PrismaAnnouncementScheduleRepository(prisma), new PrismaEmbedRepository(prisma), config.SCHEDULE_MISSED_RUN_GRACE_MINUTES, config.ANNOUNCEMENT_SCHEDULER_CONCURRENCY, (event, fields) => logger.warn(event, fields)); let scanning = false;
const server = createServer((request, response) => { const ready = request.url === '/ready'; response.writeHead(ready || request.url === '/health' ? 200 : 404, { 'content-type': 'application/json' }); response.end(JSON.stringify({ status: ready ? 'ready' : 'ok', process: 'worker' })); });
async function transcript(ticketId: string, guildId: string): Promise<void> { const guild = await client.guilds.fetch(guildId); const history: TicketHistory = { read: async (ticket) => { const channel = await guild.channels.fetch(ticket.channelId); if (!channel?.isTextBased() || !('messages' in channel)) throw new Error('Ticket history unavailable.'); const messages = await channel.messages.fetch({ limit: 100 }); return { partial: messages.size === 100, messages: [...messages.values()].map((message) => ({ id: message.id, createdAt: message.createdAt, authorId: message.author.id, authorLabel: message.author.tag, content: message.content, bot: message.author.bot, attachments: [] })) }; } }; await transcripts.generate(ticketId, guildId, history); await staffTranscripts.generate(ticketId, guildId, history); }
async function slaAlert(ticket: SlaTicket, kind: import('./persistence/advanced-ticket-repository.js').TicketSlaAlertKind): Promise<void> { const guild = await client.guilds.fetch(ticket.guildId); const resource = await setup.getResource(ticket.guildId, 'CHANNEL', 'alerts') ?? await setup.getResource(ticket.guildId, 'CHANNEL', 'support-log'); const channel = resource ? await guild.channels.fetch(resource.discordId).catch(() => null) : null; if (!channel?.isTextBased() || !('send' in channel)) throw new Error('Staff alert channel unavailable'); const label = kind.replace(/_/g, ' ').toLowerCase(); await channel.send({ embeds: [SliceEmbed.warning('Ticket SLA needs attention', `Ticket \`${ticket.id.slice(0, 8)}\` · **${ticket.category.replace(/-/g, ' ')}** is ${label}.\nRequester: <@${ticket.creatorDiscordId}>`)] }); }
async function scanSla(): Promise<void> { try { const result = await new TicketSlaService(advancedTickets, { alert: slaAlert }).scan(); if (result.risk || result.breached) logger.warn('ticket.sla_scan', result); } catch (error) { logger.warn('ticket.sla_scan_failed', { name: error instanceof Error ? error.name : 'unknown' }); } }
async function scan(): Promise<void> { if (scanning) return; scanning = true; try { const service = new TicketInactivityService(tickets, lifecycle, { warn: async (ticket) => { const guild = await client.guilds.fetch(ticket.guildId); const channel = await guild.channels.fetch(ticket.channelId); if (channel?.isTextBased() && 'send' in channel) await channel.send({ content: `<@${ticket.creatorId}>`, embeds: [SliceEmbed.warning('Ticket awaiting your response', 'This ticket is waiting for your response and may close automatically if no further response is received.')] }); }, closed: async (ticket) => { const guild = await client.guilds.fetch(ticket.guildId); await transcript(ticket.id, ticket.guildId); await refreshTicketHeader(guild, ticket); await lockTicketChannel(guild, ticket); } }, { enabled: config.TICKET_INACTIVITY_ENABLED, warningHours: config.TICKET_INACTIVITY_WARNING_HOURS, closeHours: config.TICKET_INACTIVITY_CLOSE_HOURS, batchSize: config.TICKET_INACTIVITY_BATCH_SIZE, forTicket: async (ticket) => { const policy = await advancedTickets.policy(ticket.guildId, ticket.category); return policy ? { warningHours: policy.inactivityWarningHours, closeHours: policy.inactivityCloseHours } : null; } }); const result = await service.scan(); logger.info('ticket.inactivity_scan', result); await analytics.capture(() => analytics.heartbeat({ workerName: 'slice-discord-worker', instanceId: workerInstanceId, successfulScan: true, metadata: result })); } catch (error) { logger.warn('ticket.inactivity_scan_failed', { name: error instanceof Error ? error.name : 'unknown' }); await analytics.capture(() => analytics.heartbeat({ workerName: 'slice-discord-worker', instanceId: workerInstanceId, failed: true })); } finally { scanning = false; } }
async function communityScan(): Promise<void> {
  try {
    const now = new Date(); const dayKey = now.toISOString().slice(0, 10); const weekKey = `${now.getUTCFullYear()}-${Math.ceil((((now.getTime() - Date.UTC(now.getUTCFullYear(), 0, 1)) / 86_400_000) + new Date(Date.UTC(now.getUTCFullYear(), 0, 1)).getUTCDay() + 1) / 7)}`;
    for (const row of await setup.listGuildConfigs()) {
      const guild = await client.guilds.fetch(row.guildId).catch(() => null); if (!guild) continue;
      const generalRef = await setup.getResource(guild.id, 'CHANNEL', 'general'); const general = generalRef ? await guild.channels.fetch(generalRef.discordId).catch(() => null) : null;
      if (!general?.isTextBased() || !('send' in general)) continue;
      if (config.BIRTHDAYS_ENABLED && config.BIRTHDAY_ANNOUNCEMENTS_ENABLED) for (const birthday of await community.birthdays(guild.id, now.getUTCMonth() + 1, now.getUTCDate())) await runCommunityJob('birthday_announcement', async () => { if (await community.markBirthdayAnnounced(guild.id, birthday.discordUserId, dayKey)) await general.send({ embeds: [SliceEmbed.success('Community birthday', `Happy birthday to <@${birthday.discordUserId}>!`)] }); }, logger.warn.bind(logger));
      if (config.DAILY_CONVERSATION_ENABLED && now.getUTCHours() === config.DAILY_CONVERSATION_HOUR) await runCommunityJob('daily_conversation', async () => { if (await community.claimSchedule(guild.id, 'daily-conversation', dayKey)) { const prompts = ['What collectible sparked your interest in the hobby?', 'What is one collecting story you still enjoy telling?', 'Which grading detail do you wish more collectors discussed?', 'What card, set, or collectible feels most nostalgic to you?']; await general.send({ embeds: [SliceEmbed.info('Today in the Slice community', prompts[now.getUTCDate() % prompts.length]) ] }); } }, logger.warn.bind(logger));
      if (config.WEEKLY_COMMUNITY_POST_ENABLED && now.getUTCDay() === config.WEEKLY_COMMUNITY_DAY) await runCommunityJob('weekly_community', async () => { if (await community.claimSchedule(guild.id, 'weekly-community', weekKey)) { if (config.MEME_COMPETITION_ENABLED) { const opened = await memes.openWeekly({ guildId: guild.id, channelId: general.id, periodKey: weekKey, startsAt: now, endsAt: new Date(now.getTime() + WEEKLY_MEME_DURATION_MS), rewardXp: config.MEME_COMPETITION_REWARD_XP }); if (!(await publishMemeOpening(client, memes, opened.competition, config.MEME_COMPETITION_VOTE_EMOJI))) logger.warn('meme.open_announcement_failed', { competitionId: opened.competition.id }); } else await general.send({ embeds: [SliceEmbed.info('Weekly community thread', 'Share a favorite meme, collecting moment, or hobby story from this week. Please keep it kind and community-safe.')] }); } }, logger.warn.bind(logger));
    }
    await runCommunityJob('meme_open_announcements', async () => { for (const competition of await memes.pendingOpenAnnouncements()) if (!(await publishMemeOpening(client, memes, competition, config.MEME_COMPETITION_VOTE_EMOJI))) logger.warn('meme.open_announcement_failed', { competitionId: competition.id }); }, logger.warn.bind(logger));
    await runCommunityJob('poll_close_announcements', async () => { for (const poll of await community.closeDuePolls()) await runCommunityJob('poll_close_announcement', async () => { if (!poll.channelId || !poll.messageId) return; const guild = await client.guilds.fetch(poll.guildId).catch(() => null); const channel = guild ? await guild.channels.fetch(poll.channelId).catch(() => null) : null; if (channel?.isTextBased() && 'messages' in channel) { const message = await channel.messages.fetch(poll.messageId).catch(() => null); if (message) await message.edit(pollPayload(poll, await community.pollCounts(poll.id, poll.options.length))); } }, logger.warn.bind(logger)); }, logger.warn.bind(logger));
    const giveawayResult = await runCommunityJob('due_giveaways', () => processDueGiveaways(giveaways, (giveaway) => publishGiveawayCompletion(client, giveaways, giveaway)), logger.warn.bind(logger)); if (giveawayResult && (giveawayResult.scanned || giveawayResult.published)) logger.info('giveaway.due_scan', giveawayResult);
    const memeResult = await runCommunityJob('due_meme_competitions', () => processDueMemeCompetitions(memes, (competition) => resolveMemeCompetition(client, memes, competition, MEME_COMPETITION_SYSTEM_ACTOR, true, config.MEME_COMPETITION_VOTE_EMOJI), (competition) => publishMemeResult(client, memes, competition, config.MEME_COMPETITION_VOTE_EMOJI)), logger.warn.bind(logger)); if (memeResult && (memeResult.scanned || memeResult.closed || memeResult.published)) logger.info('meme.competition_scan', memeResult);
  } catch (error) { logger.warn('community.scheduler_failed', { name: error instanceof Error ? error.name : 'unknown' }); }
}
client.once(Events.ClientReady, () => { void analytics.capture(() => analytics.heartbeat({ workerName: 'slice-discord-worker', instanceId: workerInstanceId, successfulScan: true })); void scan(); void scanSla(); void communityScan(); void deliveryWorker.scan(); void marketDigestWorker.scan(); void priceAlertWorker.scan(); void newsFeedWorker.scan(); if (config.ANNOUNCEMENT_SCHEDULER_ENABLED) void announcementScheduler.scan(); setInterval(() => void scan(), config.TICKET_INACTIVITY_SCAN_INTERVAL_MS); setInterval(() => void scanSla(), config.TICKET_INACTIVITY_SCAN_INTERVAL_MS); setInterval(() => void analytics.capture(() => analytics.heartbeat({ workerName: 'slice-discord-worker', instanceId: workerInstanceId, successfulScan: true })), 60_000); setInterval(() => void communityScan(), 15 * 60_000); setInterval(() => void deliveryWorker.scan(), 60_000); setInterval(() => void marketDigestWorker.scan(), 15 * 60_000); setInterval(() => void priceAlertWorker.scan(), config.PRICE_ALERT_SCAN_INTERVAL_MS); setInterval(() => void newsFeedWorker.scan(), config.NEWS_FEED_POLL_INTERVAL_MS); if (config.ANNOUNCEMENT_SCHEDULER_ENABLED) setInterval(() => void announcementScheduler.scan(), config.ANNOUNCEMENT_SCHEDULER_SCAN_INTERVAL_MS); logger.info('worker.started', { port: config.HEALTH_PORT + 1 }); });
await prisma.$connect(); server.listen(config.HEALTH_PORT + 1); await client.login(config.DISCORD_BOT_TOKEN);
