import { Client, Events, GatewayIntentBits } from 'discord.js';
import { createServer } from 'node:http';
import { PrismaClient } from '../generated/prisma/index.js';
import { loadConfig } from './config.js';
import { Logger } from './logger.js';
import { SliceEmbed } from './embeds/slice-embed.js';
import { PrismaTicketRepository } from './persistence/ticket-repository.js';
import { TicketInactivityService } from './ticket-inactivity.js';
import { TicketLifecycleService } from './ticket-lifecycle.js';
import { TicketTranscriptService, type TicketHistory } from './ticket-transcripts.js';
import { PrismaCommunityRepository } from './persistence/community-repository.js';
import { PrismaSetupRepository } from './persistence/setup-repository.js';
import { pollPayload } from './commands/community.js';
import { PrismaDiscordDeliveryRepository } from './persistence/discord-delivery-repository.js';
import { DiscordDeliveryWorker } from './discord-delivery-worker.js';
import { SliceBackendClient } from './slice-backend-client.js';
import { SliceCustomerRouteBuilder } from './customer-routes.js';
import { lockTicketChannel, refreshTicketHeader } from './ticket-discord.js';

const config = loadConfig(); const logger = new Logger(); const prisma = new PrismaClient({ datasources: { db: { url: config.DATABASE_URL } } }); const tickets = new PrismaTicketRepository(prisma); const lifecycle = new TicketLifecycleService(tickets); const transcripts = new TicketTranscriptService(tickets); const community = new PrismaCommunityRepository(prisma); const setup = new PrismaSetupRepository(prisma); const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent] }); const deliveryWorker = new DiscordDeliveryWorker(new SliceBackendClient({ baseUrl: config.SLICE_API_BASE_URL, serviceToken: config.SLICE_BOT_SERVICE_TOKEN }), new PrismaDiscordDeliveryRepository(prisma), setup, client, new SliceCustomerRouteBuilder(config.SLICE_WEB_BASE_URL), (event, fields) => logger.warn(event, fields)); let scanning = false;
const server = createServer((request, response) => { const ready = request.url === '/ready'; response.writeHead(ready || request.url === '/health' ? 200 : 404, { 'content-type': 'application/json' }); response.end(JSON.stringify({ status: ready ? 'ready' : 'ok', process: 'worker' })); });
async function transcript(ticketId: string, guildId: string): Promise<void> { const guild = await client.guilds.fetch(guildId); const history: TicketHistory = { read: async (ticket) => { const channel = await guild.channels.fetch(ticket.channelId); if (!channel?.isTextBased() || !('messages' in channel)) throw new Error('Ticket history unavailable.'); const messages = await channel.messages.fetch({ limit: 100 }); return { partial: messages.size === 100, messages: [...messages.values()].map((message) => ({ id: message.id, createdAt: message.createdAt, authorId: message.author.id, authorLabel: message.author.tag, content: message.content, bot: message.author.bot, attachments: [] })) }; } }; await transcripts.generate(ticketId, guildId, history); }
async function scan(): Promise<void> { if (scanning) return; scanning = true; try { const service = new TicketInactivityService(tickets, lifecycle, { warn: async (ticket) => { const guild = await client.guilds.fetch(ticket.guildId); const channel = await guild.channels.fetch(ticket.channelId); if (channel?.isTextBased() && 'send' in channel) await channel.send({ content: `<@${ticket.creatorId}>`, embeds: [SliceEmbed.warning('Ticket awaiting your response', 'This ticket is waiting for your response and may close automatically if no further response is received.')] }); }, closed: async (ticket) => { const guild = await client.guilds.fetch(ticket.guildId); await transcript(ticket.id, ticket.guildId); await refreshTicketHeader(guild, ticket); await lockTicketChannel(guild, ticket); } }, { enabled: config.TICKET_INACTIVITY_ENABLED, warningHours: config.TICKET_INACTIVITY_WARNING_HOURS, closeHours: config.TICKET_INACTIVITY_CLOSE_HOURS, batchSize: config.TICKET_INACTIVITY_BATCH_SIZE }); logger.info('ticket.inactivity_scan', await service.scan()); } catch (error) { logger.warn('ticket.inactivity_scan_failed', { name: error instanceof Error ? error.name : 'unknown' }); } finally { scanning = false; } }
async function communityScan(): Promise<void> { try { const now = new Date(); const dayKey = now.toISOString().slice(0, 10); const weekKey = `${now.getUTCFullYear()}-${Math.ceil((((now.getTime() - Date.UTC(now.getUTCFullYear(), 0, 1)) / 86_400_000) + new Date(Date.UTC(now.getUTCFullYear(), 0, 1)).getUTCDay() + 1) / 7)}`; for (const row of await setup.listGuildConfigs()) { const guild = await client.guilds.fetch(row.guildId).catch(() => null); if (!guild) continue; const generalRef = await setup.getResource(guild.id, 'CHANNEL', 'general'); const general = generalRef ? await guild.channels.fetch(generalRef.discordId).catch(() => null) : null; if (!general?.isTextBased() || !('send' in general)) continue; if (config.BIRTHDAYS_ENABLED && config.BIRTHDAY_ANNOUNCEMENTS_ENABLED) for (const birthday of await community.birthdays(guild.id, now.getUTCMonth() + 1, now.getUTCDate())) if (await community.markBirthdayAnnounced(guild.id, birthday.discordUserId, dayKey)) await general.send({ embeds: [SliceEmbed.success('Community birthday', `Happy birthday to <@${birthday.discordUserId}>!`)] }); if (config.DAILY_CONVERSATION_ENABLED && now.getUTCHours() === config.DAILY_CONVERSATION_HOUR && await community.claimSchedule(guild.id, 'daily-conversation', dayKey)) { const prompts = ['What collectible sparked your interest in the hobby?', 'What is one collecting story you still enjoy telling?', 'Which grading detail do you wish more collectors discussed?', 'What card, set, or collectible feels most nostalgic to you?']; await general.send({ embeds: [SliceEmbed.info('Today in the Slice community', prompts[now.getUTCDate() % prompts.length]) ] }); } if (config.WEEKLY_COMMUNITY_POST_ENABLED && now.getUTCDay() === config.WEEKLY_COMMUNITY_DAY && await community.claimSchedule(guild.id, 'weekly-community', weekKey)) await general.send({ embeds: [SliceEmbed.info('Weekly community thread', 'Share a favorite meme, collecting moment, or hobby story from this week. Please keep it kind and community-safe.')] }); } for (const poll of await community.closeDuePolls()) { if (!poll.channelId || !poll.messageId) continue; const guild = await client.guilds.fetch(poll.guildId).catch(() => null); const channel = guild ? await guild.channels.fetch(poll.channelId).catch(() => null) : null; if (channel?.isTextBased() && 'messages' in channel) { const message = await channel.messages.fetch(poll.messageId).catch(() => null); if (message) await message.edit(pollPayload(poll, await community.pollCounts(poll.id, poll.options.length))); } } } catch (error) { logger.warn('community.scheduler_failed', { name: error instanceof Error ? error.name : 'unknown' }); } }
client.once(Events.ClientReady, () => { void scan(); void communityScan(); void deliveryWorker.scan(); setInterval(() => void scan(), config.TICKET_INACTIVITY_SCAN_INTERVAL_MS); setInterval(() => void communityScan(), 15 * 60_000); setInterval(() => void deliveryWorker.scan(), 60_000); logger.info('worker.started', { port: config.HEALTH_PORT + 1 }); });
await prisma.$connect(); server.listen(config.HEALTH_PORT + 1); await client.login(config.DISCORD_BOT_TOKEN);
