/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CollectorWorkspaceRouteImport } from './routes/collector-workspace'
import { Route as CollectorsRouteImport } from './routes/collectors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ListRouteImport } from './routes/list'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as AllocateIdRouteImport } from './routes/allocate.$id'
import { Route as AssetIdRouteImport } from './routes/asset.$id'
import { Route as BuyIdRouteImport } from './routes/buy.$id'
import { Route as OperationsAssetsRouteImport } from './routes/operations.assets'
import { Route as OperationsSubmissionsRouteImport } from './routes/operations.submissions'
import { Route as SellIdRouteImport } from './routes/sell.$id'
import { Route as SubmissionsIdRouteImport } from './routes/submissions.$id'
import { Route as CollectorIdIndexRouteImport } from './routes/collector.$id.index'
import { Route as CollectorIdAssetsRouteImport } from './routes/collector.$id.assets'
import { Route as WalletBankSetupSuccessRouteImport } from './routes/wallet.bank.setup.success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorWorkspaceRoute = CollectorWorkspaceRouteImport.update({
  id: '/collector-workspace',
  path: '/collector-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorsRoute = CollectorsRouteImport.update({
  id: '/collectors',
  path: '/collectors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocateIdRoute = AllocateIdRouteImport.update({
  id: '/allocate/$id',
  path: '/allocate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetIdRoute = AssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIdRoute = BuyIdRouteImport.update({
  id: '/buy/$id',
  path: '/buy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsAssetsRoute = OperationsAssetsRouteImport.update({
  id: '/operations/assets',
  path: '/operations/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsSubmissionsRoute = OperationsSubmissionsRouteImport.update({
  id: '/operations/submissions',
  path: '/operations/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIdRoute = SellIdRouteImport.update({
  id: '/sell/$id',
  path: '/sell/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIdRoute = SubmissionsIdRouteImport.update({
  id: '/submissions/$id',
  path: '/submissions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorIdIndexRoute = CollectorIdIndexRouteImport.update({
  id: '/collector/$id/',
  path: '/collector/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorIdAssetsRoute = CollectorIdAssetsRouteImport.update({
  id: '/collector/$id/assets',
  path: '/collector/$id/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletBankSetupSuccessRoute = WalletBankSetupSuccessRouteImport.update({
  id: '/bank/setup/success',
  path: '/bank/setup/success',
  getParentRoute: () => WalletRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/collector-workspace': typeof CollectorWorkspaceRoute
  '/collectors': typeof CollectorsRoute
  '/dashboard': typeof DashboardRoute
  '/fees': typeof FeesRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/allocate/$id': typeof AllocateIdRoute
  '/asset/$id': typeof AssetIdRoute
  '/buy/$id': typeof BuyIdRoute
  '/operations/assets': typeof OperationsAssetsRoute
  '/operations/submissions': typeof OperationsSubmissionsRoute
  '/sell/$id': typeof SellIdRoute
  '/submissions/$id': typeof SubmissionsIdRoute
  '/collector/$id/assets': typeof CollectorIdAssetsRoute
  '/collector/$id/': typeof CollectorIdIndexRoute
  '/wallet/bank/setup/success': typeof WalletBankSetupSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/collector-workspace': typeof CollectorWorkspaceRoute
  '/collectors': typeof CollectorsRoute
  '/dashboard': typeof DashboardRoute
  '/fees': typeof FeesRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/allocate/$id': typeof AllocateIdRoute
  '/asset/$id': typeof AssetIdRoute
  '/buy/$id': typeof BuyIdRoute
  '/operations/assets': typeof OperationsAssetsRoute
  '/operations/submissions': typeof OperationsSubmissionsRoute
  '/sell/$id': typeof SellIdRoute
  '/submissions/$id': typeof SubmissionsIdRoute
  '/collector/$id/assets': typeof CollectorIdAssetsRoute
  '/collector/$id': typeof CollectorIdIndexRoute
  '/wallet/bank/setup/success': typeof WalletBankSetupSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/collector-workspace': typeof CollectorWorkspaceRoute
  '/collectors': typeof CollectorsRoute
  '/dashboard': typeof DashboardRoute
  '/fees': typeof FeesRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/allocate/$id': typeof AllocateIdRoute
  '/asset/$id': typeof AssetIdRoute
  '/buy/$id': typeof BuyIdRoute
  '/operations/assets': typeof OperationsAssetsRoute
  '/operations/submissions': typeof OperationsSubmissionsRoute
  '/sell/$id': typeof SellIdRoute
  '/submissions/$id': typeof SubmissionsIdRoute
  '/collector/$id/assets': typeof CollectorIdAssetsRoute
  '/collector/$id/': typeof CollectorIdIndexRoute
  '/wallet/bank/setup/success': typeof WalletBankSetupSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/collector-workspace'
    | '/collectors'
    | '/dashboard'
    | '/fees'
    | '/help'
    | '/how-it-works'
    | '/list'
    | '/login'
    | '/marketplace'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/portfolio'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/staff'
    | '/verify-email'
    | '/wallet'
    | '/watchlist'
    | '/allocate/$id'
    | '/asset/$id'
    | '/buy/$id'
    | '/operations/assets'
    | '/operations/submissions'
    | '/sell/$id'
    | '/submissions/$id'
    | '/collector/$id/assets'
    | '/collector/$id/'
    | '/wallet/bank/setup/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/collector-workspace'
    | '/collectors'
    | '/dashboard'
    | '/fees'
    | '/help'
    | '/how-it-works'
    | '/list'
    | '/login'
    | '/marketplace'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/portfolio'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/staff'
    | '/verify-email'
    | '/wallet'
    | '/watchlist'
    | '/allocate/$id'
    | '/asset/$id'
    | '/buy/$id'
    | '/operations/assets'
    | '/operations/submissions'
    | '/sell/$id'
    | '/submissions/$id'
    | '/collector/$id/assets'
    | '/collector/$id'
    | '/wallet/bank/setup/success'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/collector-workspace'
    | '/collectors'
    | '/dashboard'
    | '/fees'
    | '/help'
    | '/how-it-works'
    | '/list'
    | '/login'
    | '/marketplace'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/portfolio'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/staff'
    | '/verify-email'
    | '/wallet'
    | '/watchlist'
    | '/allocate/$id'
    | '/asset/$id'
    | '/buy/$id'
    | '/operations/assets'
    | '/operations/submissions'
    | '/sell/$id'
    | '/submissions/$id'
    | '/collector/$id/assets'
    | '/collector/$id/'
    | '/wallet/bank/setup/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CollectorWorkspaceRoute: typeof CollectorWorkspaceRoute
  CollectorsRoute: typeof CollectorsRoute
  DashboardRoute: typeof DashboardRoute
  FeesRoute: typeof FeesRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListRoute: typeof ListRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  PortfolioRoute: typeof PortfolioRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  StaffRoute: typeof StaffRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WalletRoute: typeof WalletRouteWithChildren
  WatchlistRoute: typeof WatchlistRoute
  AllocateIdRoute: typeof AllocateIdRoute
  AssetIdRoute: typeof AssetIdRoute
  BuyIdRoute: typeof BuyIdRoute
  OperationsAssetsRoute: typeof OperationsAssetsRoute
  OperationsSubmissionsRoute: typeof OperationsSubmissionsRoute
  SellIdRoute: typeof SellIdRoute
  SubmissionsIdRoute: typeof SubmissionsIdRoute
  CollectorIdAssetsRoute: typeof CollectorIdAssetsRoute
  CollectorIdIndexRoute: typeof CollectorIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector-workspace': {
      id: '/collector-workspace'
      path: '/collector-workspace'
      fullPath: '/collector-workspace'
      preLoaderRoute: typeof CollectorWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collectors': {
      id: '/collectors'
      path: '/collectors'
      fullPath: '/collectors'
      preLoaderRoute: typeof CollectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocate/$id': {
      id: '/allocate/$id'
      path: '/allocate/$id'
      fullPath: '/allocate/$id'
      preLoaderRoute: typeof AllocateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$id': {
      id: '/asset/$id'
      path: '/asset/$id'
      fullPath: '/asset/$id'
      preLoaderRoute: typeof AssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$id': {
      id: '/buy/$id'
      path: '/buy/$id'
      fullPath: '/buy/$id'
      preLoaderRoute: typeof BuyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/assets': {
      id: '/operations/assets'
      path: '/operations/assets'
      fullPath: '/operations/assets'
      preLoaderRoute: typeof OperationsAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/submissions': {
      id: '/operations/submissions'
      path: '/operations/submissions'
      fullPath: '/operations/submissions'
      preLoaderRoute: typeof OperationsSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/$id': {
      id: '/sell/$id'
      path: '/sell/$id'
      fullPath: '/sell/$id'
      preLoaderRoute: typeof SellIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$id': {
      id: '/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/submissions/$id'
      preLoaderRoute: typeof SubmissionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/$id/': {
      id: '/collector/$id/'
      path: '/collector/$id'
      fullPath: '/collector/$id/'
      preLoaderRoute: typeof CollectorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/$id/assets': {
      id: '/collector/$id/assets'
      path: '/collector/$id/assets'
      fullPath: '/collector/$id/assets'
      preLoaderRoute: typeof CollectorIdAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/bank/setup/success': {
      id: '/wallet/bank/setup/success'
      path: '/bank/setup/success'
      fullPath: '/wallet/bank/setup/success'
      preLoaderRoute: typeof WalletBankSetupSuccessRouteImport
      parentRoute: typeof WalletRoute
    }
  }
}

interface WalletRouteChildren {
  WalletBankSetupSuccessRoute: typeof WalletBankSetupSuccessRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletBankSetupSuccessRoute: WalletBankSetupSuccessRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CollectorWorkspaceRoute: CollectorWorkspaceRoute,
  CollectorsRoute: CollectorsRoute,
  DashboardRoute: DashboardRoute,
  FeesRoute: FeesRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListRoute: ListRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  PortfolioRoute: PortfolioRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  StaffRoute: StaffRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WalletRoute: WalletRouteWithChildren,
  WatchlistRoute: WatchlistRoute,
  AllocateIdRoute: AllocateIdRoute,
  AssetIdRoute: AssetIdRoute,
  BuyIdRoute: BuyIdRoute,
  OperationsAssetsRoute: OperationsAssetsRoute,
  OperationsSubmissionsRoute: OperationsSubmissionsRoute,
  SellIdRoute: SellIdRoute,
  SubmissionsIdRoute: SubmissionsIdRoute,
  CollectorIdAssetsRoute: CollectorIdAssetsRoute,
  CollectorIdIndexRoute: CollectorIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
